/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Church API
 * OpenAPI spec version: 1.0.0
 */
import type {
  GetActiveChurchStatus200,
  ListActiveChurchOptions200,
  SelectActiveChurch200,
  SelectActiveChurchBody
} from './churchAPI.schemas';

import { apiClient } from '../../utils/api-client';




  export const getActiveChurch = () => {
/**
 * Resolve the session Active Church, returning its status or a selection_required result when none is set yet.
 * @summary Get the Active Church status
 */
const getActiveChurchStatus = (

 ) => {
      return apiClient<GetActiveChurchStatus200>(
      {url: `/api/v1/active-church/status`, method: 'GET'
    },
      );
    }
  /**
 * List the Churches the current User holds Church Membership in and may select as their Active Church.
 * @summary List selectable Churches
 */
const listActiveChurchOptions = (

 ) => {
      return apiClient<ListActiveChurchOptions200>(
      {url: `/api/v1/active-church/options`, method: 'GET'
    },
      );
    }
  /**
 * Set the session's Active Church to a Church the current User holds Church Membership in.
 * @summary Select the Active Church
 */
const selectActiveChurch = (
    selectActiveChurchBody: SelectActiveChurchBody,
 ) => {
      return apiClient<SelectActiveChurch200>(
      {url: `/api/v1/active-church/select`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: selectActiveChurchBody
    },
      );
    }
  return {getActiveChurchStatus,listActiveChurchOptions,selectActiveChurch}};
export type GetActiveChurchStatusResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getActiveChurch>['getActiveChurchStatus']>>>
export type ListActiveChurchOptionsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getActiveChurch>['listActiveChurchOptions']>>>
export type SelectActiveChurchResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getActiveChurch>['selectActiveChurch']>>>
