/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Church API
 * OpenAPI spec version: 1.0.0
 */
import type {
  GetActiveChurchStatus200,
  ListActiveChurchOptions200,
  SelectActiveChurch200,
  SelectActiveChurchBody
} from './churchAPI.schemas';

import { apiClient } from '../../utils/api-client';




  export const getActiveChurch = () => {
const getActiveChurchStatus = (

 ) => {
      return apiClient<GetActiveChurchStatus200>(
      {url: `/api/v1/active-church/status`, method: 'GET'
    },
      );
    }
  const listActiveChurchOptions = (

 ) => {
      return apiClient<ListActiveChurchOptions200>(
      {url: `/api/v1/active-church/options`, method: 'GET'
    },
      );
    }
  const selectActiveChurch = (
    selectActiveChurchBody: SelectActiveChurchBody,
 ) => {
      return apiClient<SelectActiveChurch200>(
      {url: `/api/v1/active-church/select`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: selectActiveChurchBody
    },
      );
    }
  return {getActiveChurchStatus,listActiveChurchOptions,selectActiveChurch}};
export type GetActiveChurchStatusResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getActiveChurch>['getActiveChurchStatus']>>>
export type ListActiveChurchOptionsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getActiveChurch>['listActiveChurchOptions']>>>
export type SelectActiveChurchResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getActiveChurch>['selectActiveChurch']>>>
