/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Church API
 * OpenAPI spec version: 1.0.0
 */
import type {
  ApplyPlanningTemplates201,
  ApplyPlanningTemplatesBody,
  CreateAssignment201,
  CreateAssignmentBody,
  CreateEventTemplate201,
  CreateEventTemplateBody,
  CreateParticipationAssignment201,
  CreateParticipationAssignmentBody,
  CreatePlanningCycle201,
  CreatePlanningCycleBody,
  CreatePlanningEvent201,
  CreatePlanningEventBody,
  CreatePlanningEventSlot201,
  CreatePlanningEventSlotBody,
  CreateSlot201,
  CreateSlotBody,
  DeleteParticipationAssignment204,
  FireAvailability202,
  GenerateSlots201,
  GenerateSlotsBody,
  GetAssignmentAudit200,
  GetAvailabilityStatus200,
  GetCycleAvailabilityStatus200,
  GetCycleAvailabilityStatusParams,
  GetCycleParticipation200,
  GetCycleParticipationParams,
  GetMinistryServingProfile200,
  GetParticipationCompletion200,
  GetPlanningCycle200,
  GetScheduleBuilderData200,
  GetScheduleBuilderDataParams,
  ListEligibleVolunteers200,
  ListEventTemplates200,
  ListEvents200,
  ListEventsParams,
  ListMinistries200,
  ListMinistryCycleSummaries200,
  ListPlanningCycles200,
  ListPlanningCyclesParams,
  OverrideAssignment201,
  OverrideAssignmentBody,
  PublishParticipation204,
  PublishParticipationBody,
  ReassignParticipationAssignment200,
  ReassignParticipationAssignmentBody,
  SetMinistryDefaultDirection200,
  SetMinistryDefaultDirectionBody,
  SetParticipationInclusionsBody,
  SplitParticipationShifts201,
  SplitParticipationShiftsBody,
  UpdateEventTemplate200,
  UpdateEventTemplateBody,
  UpdatePlanningEvent200,
  UpdatePlanningEventBody,
  UpdatePlanningEventSlot200,
  UpdatePlanningEventSlotBody,
  UpdateShift200,
  UpdateShiftBody,
  UpdateSlot200,
  UpdateSlotBody,
  UpsertMinistryServingProfile200,
  UpsertMinistryServingProfileBody,
  UpsertShiftRequirement200,
  UpsertShiftRequirementBody,
  UpsertSlotRequirement200,
  UpsertSlotRequirementBody
} from './churchAPI.schemas';

import { apiClient } from '../../utils/api-client';




  export const getAdmin = () => {
const listMinistries = (

 ) => {
      return apiClient<ListMinistries200>(
      {url: `/api/v1/admin/ministries`, method: 'GET'
    },
      );
    }
  const getScheduleBuilderData = (
    params: GetScheduleBuilderDataParams,
 ) => {
      return apiClient<GetScheduleBuilderData200>(
      {url: `/api/v1/admin/schedule-builder`, method: 'GET',
        params
    },
      );
    }
  const listEvents = (
    params: ListEventsParams,
 ) => {
      return apiClient<ListEvents200>(
      {url: `/api/v1/admin/events`, method: 'GET',
        params
    },
      );
    }
  const cancelEvent = (
    eventId: string,
 ) => {
      return apiClient<void>(
      {url: `/api/v1/admin/events/${eventId}/cancel`, method: 'POST'
    },
      );
    }
  const sendReminders = (
    eventId: string,
 ) => {
      return apiClient<void>(
      {url: `/api/v1/admin/events/${eventId}/reminders`, method: 'POST'
    },
      );
    }
  const createSlot = (
    eventId: string,
    createSlotBody: CreateSlotBody,
 ) => {
      return apiClient<CreateSlot201>(
      {url: `/api/v1/admin/events/${eventId}/slots`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createSlotBody
    },
      );
    }
  const updateSlot = (
    eventId: string,
    slotId: string,
    updateSlotBody: UpdateSlotBody,
 ) => {
      return apiClient<UpdateSlot200>(
      {url: `/api/v1/admin/events/${eventId}/slots/${slotId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateSlotBody
    },
      );
    }
  const deleteSlot = (
    eventId: string,
    slotId: string,
 ) => {
      return apiClient<void>(
      {url: `/api/v1/admin/events/${eventId}/slots/${slotId}`, method: 'DELETE'
    },
      );
    }
  const overrideAssignment = (
    assignmentId: string,
    overrideAssignmentBody: OverrideAssignmentBody,
 ) => {
      return apiClient<OverrideAssignment201>(
      {url: `/api/v1/admin/assignments/${assignmentId}/override`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: overrideAssignmentBody
    },
      );
    }
  const generateSlots = (
    eventId: string,
    generateSlotsBody: GenerateSlotsBody,
 ) => {
      return apiClient<GenerateSlots201>(
      {url: `/api/v1/admin/events/${eventId}/slots/generate`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: generateSlotsBody
    },
      );
    }
  const upsertSlotRequirement = (
    eventId: string,
    slotId: string,
    upsertSlotRequirementBody: UpsertSlotRequirementBody,
 ) => {
      return apiClient<UpsertSlotRequirement200>(
      {url: `/api/v1/admin/events/${eventId}/slots/${slotId}/requirements`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: upsertSlotRequirementBody
    },
      );
    }
  const createAssignment = (
    createAssignmentBody: CreateAssignmentBody,
 ) => {
      return apiClient<CreateAssignment201>(
      {url: `/api/v1/admin/assignments`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createAssignmentBody
    },
      );
    }
  const deleteAssignment = (
    assignmentId: string,
 ) => {
      return apiClient<void>(
      {url: `/api/v1/admin/assignments/${assignmentId}`, method: 'DELETE'
    },
      );
    }
  const getAssignmentAudit = (
    assignmentId: string,
 ) => {
      return apiClient<GetAssignmentAudit200>(
      {url: `/api/v1/admin/assignments/${assignmentId}/audit`, method: 'GET'
    },
      );
    }
  const createPlanningCycle = (
    createPlanningCycleBody: CreatePlanningCycleBody,
 ) => {
      return apiClient<CreatePlanningCycle201>(
      {url: `/api/v1/admin/planning-cycles`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createPlanningCycleBody
    },
      );
    }
  const listPlanningCycles = (
    params?: ListPlanningCyclesParams,
 ) => {
      return apiClient<ListPlanningCycles200>(
      {url: `/api/v1/admin/planning-cycles`, method: 'GET',
        params
    },
      );
    }
  const getPlanningCycle = (
    cycleId: string,
 ) => {
      return apiClient<GetPlanningCycle200>(
      {url: `/api/v1/admin/planning-cycles/${cycleId}`, method: 'GET'
    },
      );
    }
  const lockPlanningCycle = (
    cycleId: string,
 ) => {
      return apiClient<void>(
      {url: `/api/v1/admin/planning-cycles/${cycleId}/lock`, method: 'POST'
    },
      );
    }
  const reopenPlanningEvent = (
    cycleId: string,
    eventId: string,
 ) => {
      return apiClient<void>(
      {url: `/api/v1/admin/planning-cycles/${cycleId}/events/${eventId}/reopen`, method: 'POST'
    },
      );
    }
  const createEventTemplate = (
    createEventTemplateBody: CreateEventTemplateBody,
 ) => {
      return apiClient<CreateEventTemplate201>(
      {url: `/api/v1/admin/event-templates`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createEventTemplateBody
    },
      );
    }
  const listEventTemplates = (

 ) => {
      return apiClient<ListEventTemplates200>(
      {url: `/api/v1/admin/event-templates`, method: 'GET'
    },
      );
    }
  const updateEventTemplate = (
    templateId: string,
    updateEventTemplateBody: UpdateEventTemplateBody,
 ) => {
      return apiClient<UpdateEventTemplate200>(
      {url: `/api/v1/admin/event-templates/${templateId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateEventTemplateBody
    },
      );
    }
  const deleteEventTemplate = (
    templateId: string,
 ) => {
      return apiClient<void>(
      {url: `/api/v1/admin/event-templates/${templateId}`, method: 'DELETE'
    },
      );
    }
  const applyPlanningTemplates = (
    cycleId: string,
    applyPlanningTemplatesBody: ApplyPlanningTemplatesBody,
 ) => {
      return apiClient<ApplyPlanningTemplates201>(
      {url: `/api/v1/admin/planning-cycles/${cycleId}/apply-templates`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: applyPlanningTemplatesBody
    },
      );
    }
  const createPlanningEvent = (
    cycleId: string,
    createPlanningEventBody: CreatePlanningEventBody,
 ) => {
      return apiClient<CreatePlanningEvent201>(
      {url: `/api/v1/admin/planning-cycles/${cycleId}/events`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createPlanningEventBody
    },
      );
    }
  const updatePlanningEvent = (
    cycleId: string,
    eventId: string,
    updatePlanningEventBody: UpdatePlanningEventBody,
 ) => {
      return apiClient<UpdatePlanningEvent200>(
      {url: `/api/v1/admin/planning-cycles/${cycleId}/events/${eventId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updatePlanningEventBody
    },
      );
    }
  const cancelPlanningEvent = (
    cycleId: string,
    eventId: string,
 ) => {
      return apiClient<void>(
      {url: `/api/v1/admin/planning-cycles/${cycleId}/events/${eventId}/cancel`, method: 'POST'
    },
      );
    }
  const createPlanningEventSlot = (
    cycleId: string,
    eventId: string,
    createPlanningEventSlotBody: CreatePlanningEventSlotBody,
 ) => {
      return apiClient<CreatePlanningEventSlot201>(
      {url: `/api/v1/admin/planning-cycles/${cycleId}/events/${eventId}/slots`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createPlanningEventSlotBody
    },
      );
    }
  const updatePlanningEventSlot = (
    cycleId: string,
    eventId: string,
    slotId: string,
    updatePlanningEventSlotBody: UpdatePlanningEventSlotBody,
 ) => {
      return apiClient<UpdatePlanningEventSlot200>(
      {url: `/api/v1/admin/planning-cycles/${cycleId}/events/${eventId}/slots/${slotId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updatePlanningEventSlotBody
    },
      );
    }
  const deletePlanningEventSlot = (
    cycleId: string,
    eventId: string,
    slotId: string,
 ) => {
      return apiClient<void>(
      {url: `/api/v1/admin/planning-cycles/${cycleId}/events/${eventId}/slots/${slotId}`, method: 'DELETE'
    },
      );
    }
  /**
 * Get the serving profile for a specific ministry, including roles and teams.
 * @summary getMinistryServingProfile
 */
const getMinistryServingProfile = (
    ministryId: string,
 ) => {
      return apiClient<GetMinistryServingProfile200>(
      {url: `/api/v1/admin/ministries/${ministryId}/serving-profile`, method: 'GET'
    },
      );
    }
  const upsertMinistryServingProfile = (
    ministryId: string,
    upsertMinistryServingProfileBody: UpsertMinistryServingProfileBody,
 ) => {
      return apiClient<UpsertMinistryServingProfile200>(
      {url: `/api/v1/admin/ministries/${ministryId}/serving-profile`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: upsertMinistryServingProfileBody
    },
      );
    }
  const setMinistryDefaultDirection = (
    ministryId: string,
    setMinistryDefaultDirectionBody: SetMinistryDefaultDirectionBody,
 ) => {
      return apiClient<SetMinistryDefaultDirection200>(
      {url: `/api/v1/admin/ministries/${ministryId}/default-direction`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: setMinistryDefaultDirectionBody
    },
      );
    }
  const getCycleParticipation = (
    cycleId: string,
    params: GetCycleParticipationParams,
 ) => {
      return apiClient<GetCycleParticipation200>(
      {url: `/api/v1/leader/cycles/${cycleId}/participation`, method: 'GET',
        params
    },
      );
    }
  const listMinistryCycleSummaries = (
    ministryId: string,
 ) => {
      return apiClient<ListMinistryCycleSummaries200>(
      {url: `/api/v1/leader/ministries/${ministryId}/cycles-summary`, method: 'GET'
    },
      );
    }
  const setParticipationInclusions = (
    participationId: string,
    setParticipationInclusionsBody: SetParticipationInclusionsBody,
 ) => {
      return apiClient<void>(
      {url: `/api/v1/leader/participations/${participationId}/inclusions`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: setParticipationInclusionsBody
    },
      );
    }
  const splitParticipationShifts = (
    participationId: string,
    timeSlotId: string,
    splitParticipationShiftsBody: SplitParticipationShiftsBody,
 ) => {
      return apiClient<SplitParticipationShifts201>(
      {url: `/api/v1/leader/participations/${participationId}/slots/${timeSlotId}/shifts`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: splitParticipationShiftsBody
    },
      );
    }
  const updateShift = (
    shiftId: string,
    updateShiftBody: UpdateShiftBody,
 ) => {
      return apiClient<UpdateShift200>(
      {url: `/api/v1/leader/shifts/${shiftId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateShiftBody
    },
      );
    }
  const deleteShift = (
    shiftId: string,
 ) => {
      return apiClient<void>(
      {url: `/api/v1/leader/shifts/${shiftId}`, method: 'DELETE'
    },
      );
    }
  const upsertShiftRequirement = (
    shiftId: string,
    upsertShiftRequirementBody: UpsertShiftRequirementBody,
 ) => {
      return apiClient<UpsertShiftRequirement200>(
      {url: `/api/v1/leader/shifts/${shiftId}/requirements`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: upsertShiftRequirementBody
    },
      );
    }
  const fireAvailability = (
    participationId: string,
 ) => {
      return apiClient<FireAvailability202>(
      {url: `/api/v1/leader/participations/${participationId}/fire-availability`, method: 'POST'
    },
      );
    }
  const getCycleAvailabilityStatus = (
    cycleId: string,
    params: GetCycleAvailabilityStatusParams,
 ) => {
      return apiClient<GetCycleAvailabilityStatus200>(
      {url: `/api/v1/leader/cycles/${cycleId}/availability-status`, method: 'GET',
        params
    },
      );
    }
  const getAvailabilityStatus = (
    participationId: string,
 ) => {
      return apiClient<GetAvailabilityStatus200>(
      {url: `/api/v1/leader/participations/${participationId}/availability-status`, method: 'GET'
    },
      );
    }
  const resendAvailabilityReminder = (
    participationId: string,
 ) => {
      return apiClient<void>(
      {url: `/api/v1/leader/participations/${participationId}/resend-availability`, method: 'POST'
    },
      );
    }
  const listEligibleVolunteers = (
    shiftId: string,
 ) => {
      return apiClient<ListEligibleVolunteers200>(
      {url: `/api/v1/leader/shifts/${shiftId}/eligible-volunteers`, method: 'GET'
    },
      );
    }
  const createParticipationAssignment = (
    shiftId: string,
    createParticipationAssignmentBody: CreateParticipationAssignmentBody,
 ) => {
      return apiClient<CreateParticipationAssignment201>(
      {url: `/api/v1/leader/shifts/${shiftId}/assignments`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createParticipationAssignmentBody
    },
      );
    }
  const deleteParticipationAssignment = (
    assignmentId: string,
 ) => {
      return apiClient<DeleteParticipationAssignment204>(
      {url: `/api/v1/leader/assignments/${assignmentId}`, method: 'DELETE'
    },
      );
    }
  const reassignParticipationAssignment = (
    assignmentId: string,
    reassignParticipationAssignmentBody: ReassignParticipationAssignmentBody,
 ) => {
      return apiClient<ReassignParticipationAssignment200>(
      {url: `/api/v1/leader/assignments/${assignmentId}/reassign`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: reassignParticipationAssignmentBody
    },
      );
    }
  const getParticipationCompletion = (
    participationId: string,
 ) => {
      return apiClient<GetParticipationCompletion200>(
      {url: `/api/v1/leader/participations/${participationId}/completion`, method: 'GET'
    },
      );
    }
  const publishParticipation = (
    participationId: string,
    publishParticipationBody: PublishParticipationBody,
 ) => {
      return apiClient<PublishParticipation204>(
      {url: `/api/v1/leader/participations/${participationId}/publish`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: publishParticipationBody
    },
      );
    }
  return {listMinistries,getScheduleBuilderData,listEvents,cancelEvent,sendReminders,createSlot,updateSlot,deleteSlot,overrideAssignment,generateSlots,upsertSlotRequirement,createAssignment,deleteAssignment,getAssignmentAudit,createPlanningCycle,listPlanningCycles,getPlanningCycle,lockPlanningCycle,reopenPlanningEvent,createEventTemplate,listEventTemplates,updateEventTemplate,deleteEventTemplate,applyPlanningTemplates,createPlanningEvent,updatePlanningEvent,cancelPlanningEvent,createPlanningEventSlot,updatePlanningEventSlot,deletePlanningEventSlot,getMinistryServingProfile,upsertMinistryServingProfile,setMinistryDefaultDirection,getCycleParticipation,listMinistryCycleSummaries,setParticipationInclusions,splitParticipationShifts,updateShift,deleteShift,upsertShiftRequirement,fireAvailability,getCycleAvailabilityStatus,getAvailabilityStatus,resendAvailabilityReminder,listEligibleVolunteers,createParticipationAssignment,deleteParticipationAssignment,reassignParticipationAssignment,getParticipationCompletion,publishParticipation}};
export type ListMinistriesResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['listMinistries']>>>
export type GetScheduleBuilderDataResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['getScheduleBuilderData']>>>
export type ListEventsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['listEvents']>>>
export type CancelEventResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['cancelEvent']>>>
export type SendRemindersResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['sendReminders']>>>
export type CreateSlotResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['createSlot']>>>
export type UpdateSlotResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['updateSlot']>>>
export type DeleteSlotResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['deleteSlot']>>>
export type OverrideAssignmentResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['overrideAssignment']>>>
export type GenerateSlotsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['generateSlots']>>>
export type UpsertSlotRequirementResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['upsertSlotRequirement']>>>
export type CreateAssignmentResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['createAssignment']>>>
export type DeleteAssignmentResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['deleteAssignment']>>>
export type GetAssignmentAuditResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['getAssignmentAudit']>>>
export type CreatePlanningCycleResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['createPlanningCycle']>>>
export type ListPlanningCyclesResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['listPlanningCycles']>>>
export type GetPlanningCycleResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['getPlanningCycle']>>>
export type LockPlanningCycleResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['lockPlanningCycle']>>>
export type ReopenPlanningEventResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['reopenPlanningEvent']>>>
export type CreateEventTemplateResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['createEventTemplate']>>>
export type ListEventTemplatesResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['listEventTemplates']>>>
export type UpdateEventTemplateResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['updateEventTemplate']>>>
export type DeleteEventTemplateResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['deleteEventTemplate']>>>
export type ApplyPlanningTemplatesResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['applyPlanningTemplates']>>>
export type CreatePlanningEventResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['createPlanningEvent']>>>
export type UpdatePlanningEventResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['updatePlanningEvent']>>>
export type CancelPlanningEventResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['cancelPlanningEvent']>>>
export type CreatePlanningEventSlotResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['createPlanningEventSlot']>>>
export type UpdatePlanningEventSlotResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['updatePlanningEventSlot']>>>
export type DeletePlanningEventSlotResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['deletePlanningEventSlot']>>>
export type GetMinistryServingProfileResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['getMinistryServingProfile']>>>
export type UpsertMinistryServingProfileResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['upsertMinistryServingProfile']>>>
export type SetMinistryDefaultDirectionResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['setMinistryDefaultDirection']>>>
export type GetCycleParticipationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['getCycleParticipation']>>>
export type ListMinistryCycleSummariesResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['listMinistryCycleSummaries']>>>
export type SetParticipationInclusionsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['setParticipationInclusions']>>>
export type SplitParticipationShiftsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['splitParticipationShifts']>>>
export type UpdateShiftResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['updateShift']>>>
export type DeleteShiftResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['deleteShift']>>>
export type UpsertShiftRequirementResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['upsertShiftRequirement']>>>
export type FireAvailabilityResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['fireAvailability']>>>
export type GetCycleAvailabilityStatusResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['getCycleAvailabilityStatus']>>>
export type GetAvailabilityStatusResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['getAvailabilityStatus']>>>
export type ResendAvailabilityReminderResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['resendAvailabilityReminder']>>>
export type ListEligibleVolunteersResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['listEligibleVolunteers']>>>
export type CreateParticipationAssignmentResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['createParticipationAssignment']>>>
export type DeleteParticipationAssignmentResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['deleteParticipationAssignment']>>>
export type ReassignParticipationAssignmentResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['reassignParticipationAssignment']>>>
export type GetParticipationCompletionResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['getParticipationCompletion']>>>
export type PublishParticipationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['publishParticipation']>>>
