/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Church API
 * OpenAPI spec version: 1.0.0
 */
import type {
  ApplyPlanningTemplates201,
  ApplyPlanningTemplatesBody,
  CreateAssignment201,
  CreateAssignmentBody,
  CreateEventTemplate201,
  CreateEventTemplateBody,
  CreatePlanningCycle201,
  CreatePlanningCycleBody,
  CreatePlanningEvent201,
  CreatePlanningEventBody,
  CreateSlot201,
  CreateSlotBody,
  GenerateSlots201,
  GenerateSlotsBody,
  GetAssignmentAudit200,
  GetPlanningCycle200,
  GetScheduleBuilderData200,
  GetScheduleBuilderDataParams,
  ListEventTemplates200,
  ListEvents200,
  ListEventsParams,
  ListMinistries200,
  ListPlanningCycles200,
  ListPlanningCyclesParams,
  OverrideAssignment201,
  OverrideAssignmentBody,
  UpdateEventTemplate200,
  UpdateEventTemplateBody,
  UpdatePlanningEvent200,
  UpdatePlanningEventBody,
  UpdateSlot200,
  UpdateSlotBody,
  UpsertSlotRequirement200,
  UpsertSlotRequirementBody
} from './churchAPI.schemas';

import { apiClient } from '../../utils/api-client';




  export const getAdmin = () => {
const listMinistries = (

 ) => {
      return apiClient<ListMinistries200>(
      {url: `/api/v1/admin/ministries`, method: 'GET'
    },
      );
    }
  const getScheduleBuilderData = (
    params: GetScheduleBuilderDataParams,
 ) => {
      return apiClient<GetScheduleBuilderData200>(
      {url: `/api/v1/admin/schedule-builder`, method: 'GET',
        params
    },
      );
    }
  const listEvents = (
    params: ListEventsParams,
 ) => {
      return apiClient<ListEvents200>(
      {url: `/api/v1/admin/events`, method: 'GET',
        params
    },
      );
    }
  const cancelEvent = (
    eventId: string,
 ) => {
      return apiClient<void>(
      {url: `/api/v1/admin/events/${eventId}/cancel`, method: 'POST'
    },
      );
    }
  const sendReminders = (
    eventId: string,
 ) => {
      return apiClient<void>(
      {url: `/api/v1/admin/events/${eventId}/reminders`, method: 'POST'
    },
      );
    }
  const createSlot = (
    eventId: string,
    createSlotBody: CreateSlotBody,
 ) => {
      return apiClient<CreateSlot201>(
      {url: `/api/v1/admin/events/${eventId}/slots`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createSlotBody
    },
      );
    }
  const updateSlot = (
    eventId: string,
    slotId: string,
    updateSlotBody: UpdateSlotBody,
 ) => {
      return apiClient<UpdateSlot200>(
      {url: `/api/v1/admin/events/${eventId}/slots/${slotId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateSlotBody
    },
      );
    }
  const deleteSlot = (
    eventId: string,
    slotId: string,
 ) => {
      return apiClient<void>(
      {url: `/api/v1/admin/events/${eventId}/slots/${slotId}`, method: 'DELETE'
    },
      );
    }
  const overrideAssignment = (
    assignmentId: string,
    overrideAssignmentBody: OverrideAssignmentBody,
 ) => {
      return apiClient<OverrideAssignment201>(
      {url: `/api/v1/admin/assignments/${assignmentId}/override`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: overrideAssignmentBody
    },
      );
    }
  const generateSlots = (
    eventId: string,
    generateSlotsBody: GenerateSlotsBody,
 ) => {
      return apiClient<GenerateSlots201>(
      {url: `/api/v1/admin/events/${eventId}/slots/generate`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: generateSlotsBody
    },
      );
    }
  const upsertSlotRequirement = (
    eventId: string,
    slotId: string,
    upsertSlotRequirementBody: UpsertSlotRequirementBody,
 ) => {
      return apiClient<UpsertSlotRequirement200>(
      {url: `/api/v1/admin/events/${eventId}/slots/${slotId}/requirements`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: upsertSlotRequirementBody
    },
      );
    }
  const createAssignment = (
    createAssignmentBody: CreateAssignmentBody,
 ) => {
      return apiClient<CreateAssignment201>(
      {url: `/api/v1/admin/assignments`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createAssignmentBody
    },
      );
    }
  const deleteAssignment = (
    assignmentId: string,
 ) => {
      return apiClient<void>(
      {url: `/api/v1/admin/assignments/${assignmentId}`, method: 'DELETE'
    },
      );
    }
  const getAssignmentAudit = (
    assignmentId: string,
 ) => {
      return apiClient<GetAssignmentAudit200>(
      {url: `/api/v1/admin/assignments/${assignmentId}/audit`, method: 'GET'
    },
      );
    }
  const createPlanningCycle = (
    createPlanningCycleBody: CreatePlanningCycleBody,
 ) => {
      return apiClient<CreatePlanningCycle201>(
      {url: `/api/v1/admin/planning-cycles`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createPlanningCycleBody
    },
      );
    }
  const listPlanningCycles = (
    params?: ListPlanningCyclesParams,
 ) => {
      return apiClient<ListPlanningCycles200>(
      {url: `/api/v1/admin/planning-cycles`, method: 'GET',
        params
    },
      );
    }
  const getPlanningCycle = (
    cycleId: string,
 ) => {
      return apiClient<GetPlanningCycle200>(
      {url: `/api/v1/admin/planning-cycles/${cycleId}`, method: 'GET'
    },
      );
    }
  const lockPlanningCycle = (
    cycleId: string,
 ) => {
      return apiClient<void>(
      {url: `/api/v1/admin/planning-cycles/${cycleId}/lock`, method: 'POST'
    },
      );
    }
  const reopenPlanningEvent = (
    cycleId: string,
    eventId: string,
 ) => {
      return apiClient<void>(
      {url: `/api/v1/admin/planning-cycles/${cycleId}/events/${eventId}/reopen`, method: 'POST'
    },
      );
    }
  const createEventTemplate = (
    createEventTemplateBody: CreateEventTemplateBody,
 ) => {
      return apiClient<CreateEventTemplate201>(
      {url: `/api/v1/admin/event-templates`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createEventTemplateBody
    },
      );
    }
  const listEventTemplates = (

 ) => {
      return apiClient<ListEventTemplates200>(
      {url: `/api/v1/admin/event-templates`, method: 'GET'
    },
      );
    }
  const updateEventTemplate = (
    templateId: string,
    updateEventTemplateBody: UpdateEventTemplateBody,
 ) => {
      return apiClient<UpdateEventTemplate200>(
      {url: `/api/v1/admin/event-templates/${templateId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateEventTemplateBody
    },
      );
    }
  const deleteEventTemplate = (
    templateId: string,
 ) => {
      return apiClient<void>(
      {url: `/api/v1/admin/event-templates/${templateId}`, method: 'DELETE'
    },
      );
    }
  const applyPlanningTemplates = (
    cycleId: string,
    applyPlanningTemplatesBody: ApplyPlanningTemplatesBody,
 ) => {
      return apiClient<ApplyPlanningTemplates201>(
      {url: `/api/v1/admin/planning-cycles/${cycleId}/apply-templates`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: applyPlanningTemplatesBody
    },
      );
    }
  const createPlanningEvent = (
    cycleId: string,
    createPlanningEventBody: CreatePlanningEventBody,
 ) => {
      return apiClient<CreatePlanningEvent201>(
      {url: `/api/v1/admin/planning-cycles/${cycleId}/events`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createPlanningEventBody
    },
      );
    }
  const updatePlanningEvent = (
    cycleId: string,
    eventId: string,
    updatePlanningEventBody: UpdatePlanningEventBody,
 ) => {
      return apiClient<UpdatePlanningEvent200>(
      {url: `/api/v1/admin/planning-cycles/${cycleId}/events/${eventId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updatePlanningEventBody
    },
      );
    }
  const cancelPlanningEvent = (
    cycleId: string,
    eventId: string,
 ) => {
      return apiClient<void>(
      {url: `/api/v1/admin/planning-cycles/${cycleId}/events/${eventId}/cancel`, method: 'POST'
    },
      );
    }
  return {listMinistries,getScheduleBuilderData,listEvents,cancelEvent,sendReminders,createSlot,updateSlot,deleteSlot,overrideAssignment,generateSlots,upsertSlotRequirement,createAssignment,deleteAssignment,getAssignmentAudit,createPlanningCycle,listPlanningCycles,getPlanningCycle,lockPlanningCycle,reopenPlanningEvent,createEventTemplate,listEventTemplates,updateEventTemplate,deleteEventTemplate,applyPlanningTemplates,createPlanningEvent,updatePlanningEvent,cancelPlanningEvent}};
export type ListMinistriesResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['listMinistries']>>>
export type GetScheduleBuilderDataResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['getScheduleBuilderData']>>>
export type ListEventsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['listEvents']>>>
export type CancelEventResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['cancelEvent']>>>
export type SendRemindersResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['sendReminders']>>>
export type CreateSlotResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['createSlot']>>>
export type UpdateSlotResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['updateSlot']>>>
export type DeleteSlotResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['deleteSlot']>>>
export type OverrideAssignmentResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['overrideAssignment']>>>
export type GenerateSlotsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['generateSlots']>>>
export type UpsertSlotRequirementResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['upsertSlotRequirement']>>>
export type CreateAssignmentResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['createAssignment']>>>
export type DeleteAssignmentResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['deleteAssignment']>>>
export type GetAssignmentAuditResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['getAssignmentAudit']>>>
export type CreatePlanningCycleResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['createPlanningCycle']>>>
export type ListPlanningCyclesResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['listPlanningCycles']>>>
export type GetPlanningCycleResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['getPlanningCycle']>>>
export type LockPlanningCycleResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['lockPlanningCycle']>>>
export type ReopenPlanningEventResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['reopenPlanningEvent']>>>
export type CreateEventTemplateResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['createEventTemplate']>>>
export type ListEventTemplatesResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['listEventTemplates']>>>
export type UpdateEventTemplateResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['updateEventTemplate']>>>
export type DeleteEventTemplateResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['deleteEventTemplate']>>>
export type ApplyPlanningTemplatesResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['applyPlanningTemplates']>>>
export type CreatePlanningEventResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['createPlanningEvent']>>>
export type UpdatePlanningEventResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['updatePlanningEvent']>>>
export type CancelPlanningEventResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['cancelPlanningEvent']>>>
