/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Church API
 * OpenAPI spec version: 1.0.0
 */
import type {
  CreateAssignment201,
  CreateAssignmentBody,
  CreateEvent201,
  CreateEventBody,
  CreateSlot201,
  CreateSlotBody,
  GenerateSlots201,
  GenerateSlotsBody,
  GetAssignmentAudit200,
  GetScheduleBuilderData200,
  ListEvents200,
  ListEventsParams,
  ListMinistries200,
  ListRoleTemplates200,
  UpdateSlot200,
  UpdateSlotBody,
  UpsertRoleTemplate200,
  UpsertRoleTemplateBody,
  UpsertSlotRequirement200,
  UpsertSlotRequirementBody
} from './churchAPI.schemas';

import { apiClient } from '../../utils/api-client';




  export const getAdmin = () => {
const listMinistries = (

 ) => {
      return apiClient<ListMinistries200>(
      {url: `/api/v1/admin/ministries`, method: 'GET'
    },
      );
    }
  const getScheduleBuilderData = (

 ) => {
      return apiClient<GetScheduleBuilderData200>(
      {url: `/api/v1/admin/schedule-builder`, method: 'GET'
    },
      );
    }
  const listEvents = (
    params: ListEventsParams,
 ) => {
      return apiClient<ListEvents200>(
      {url: `/api/v1/admin/events`, method: 'GET',
        params
    },
      );
    }
  const createEvent = (
    createEventBody: CreateEventBody,
 ) => {
      return apiClient<CreateEvent201>(
      {url: `/api/v1/admin/events`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createEventBody
    },
      );
    }
  const publishEvent = (
    eventId: string,
 ) => {
      return apiClient<void>(
      {url: `/api/v1/admin/events/${eventId}/publish`, method: 'POST'
    },
      );
    }
  const cancelEvent = (
    eventId: string,
 ) => {
      return apiClient<void>(
      {url: `/api/v1/admin/events/${eventId}/cancel`, method: 'POST'
    },
      );
    }
  const sendReminders = (
    eventId: string,
 ) => {
      return apiClient<void>(
      {url: `/api/v1/admin/events/${eventId}/reminders`, method: 'POST'
    },
      );
    }
  const createSlot = (
    eventId: string,
    createSlotBody: CreateSlotBody,
 ) => {
      return apiClient<CreateSlot201>(
      {url: `/api/v1/admin/events/${eventId}/slots`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createSlotBody
    },
      );
    }
  const updateSlot = (
    eventId: string,
    slotId: string,
    updateSlotBody: UpdateSlotBody,
 ) => {
      return apiClient<UpdateSlot200>(
      {url: `/api/v1/admin/events/${eventId}/slots/${slotId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateSlotBody
    },
      );
    }
  const deleteSlot = (
    eventId: string,
    slotId: string,
 ) => {
      return apiClient<void>(
      {url: `/api/v1/admin/events/${eventId}/slots/${slotId}`, method: 'DELETE'
    },
      );
    }
  const generateSlots = (
    eventId: string,
    generateSlotsBody: GenerateSlotsBody,
 ) => {
      return apiClient<GenerateSlots201>(
      {url: `/api/v1/admin/events/${eventId}/slots/generate`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: generateSlotsBody
    },
      );
    }
  const upsertSlotRequirement = (
    eventId: string,
    slotId: string,
    upsertSlotRequirementBody: UpsertSlotRequirementBody,
 ) => {
      return apiClient<UpsertSlotRequirement200>(
      {url: `/api/v1/admin/events/${eventId}/slots/${slotId}/requirements`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: upsertSlotRequirementBody
    },
      );
    }
  const createAssignment = (
    createAssignmentBody: CreateAssignmentBody,
 ) => {
      return apiClient<CreateAssignment201>(
      {url: `/api/v1/admin/assignments`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createAssignmentBody
    },
      );
    }
  const deleteAssignment = (
    assignmentId: string,
 ) => {
      return apiClient<void>(
      {url: `/api/v1/admin/assignments/${assignmentId}`, method: 'DELETE'
    },
      );
    }
  const getAssignmentAudit = (
    assignmentId: string,
 ) => {
      return apiClient<GetAssignmentAudit200>(
      {url: `/api/v1/admin/assignments/${assignmentId}/audit`, method: 'GET'
    },
      );
    }
  const listRoleTemplates = (

 ) => {
      return apiClient<ListRoleTemplates200>(
      {url: `/api/v1/admin/role-templates`, method: 'GET'
    },
      );
    }
  const upsertRoleTemplate = (
    templateId: string,
    upsertRoleTemplateBody: UpsertRoleTemplateBody,
 ) => {
      return apiClient<UpsertRoleTemplate200>(
      {url: `/api/v1/admin/role-templates/${templateId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: upsertRoleTemplateBody
    },
      );
    }
  const deleteRoleTemplate = (
    templateId: string,
 ) => {
      return apiClient<void>(
      {url: `/api/v1/admin/role-templates/${templateId}`, method: 'DELETE'
    },
      );
    }
  return {listMinistries,getScheduleBuilderData,listEvents,createEvent,publishEvent,cancelEvent,sendReminders,createSlot,updateSlot,deleteSlot,generateSlots,upsertSlotRequirement,createAssignment,deleteAssignment,getAssignmentAudit,listRoleTemplates,upsertRoleTemplate,deleteRoleTemplate}};
export type ListMinistriesResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['listMinistries']>>>
export type GetScheduleBuilderDataResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['getScheduleBuilderData']>>>
export type ListEventsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['listEvents']>>>
export type CreateEventResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['createEvent']>>>
export type PublishEventResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['publishEvent']>>>
export type CancelEventResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['cancelEvent']>>>
export type SendRemindersResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['sendReminders']>>>
export type CreateSlotResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['createSlot']>>>
export type UpdateSlotResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['updateSlot']>>>
export type DeleteSlotResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['deleteSlot']>>>
export type GenerateSlotsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['generateSlots']>>>
export type UpsertSlotRequirementResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['upsertSlotRequirement']>>>
export type CreateAssignmentResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['createAssignment']>>>
export type DeleteAssignmentResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['deleteAssignment']>>>
export type GetAssignmentAuditResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['getAssignmentAudit']>>>
export type ListRoleTemplatesResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['listRoleTemplates']>>>
export type UpsertRoleTemplateResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['upsertRoleTemplate']>>>
export type DeleteRoleTemplateResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['deleteRoleTemplate']>>>
