/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Church API
 * OpenAPI spec version: 1.0.0
 */
import type {
  CreateAssignment201,
  CreateAssignmentBody,
  GetAssignmentAudit200,
  OverrideAssignment201,
  OverrideAssignmentBody
} from './churchAPI.schemas';

import { apiClient } from '../../utils/api-client';




  export const getAssignments = () => {
/**
 * Assign a Volunteer to a Role within a TimeSlot, rejecting the request if the caller does not manage that TimeSlot.
 * @summary Create an Assignment
 */
const createAssignment = (
    createAssignmentBody: CreateAssignmentBody,
 ) => {
      return apiClient<CreateAssignment201>(
      {url: `/api/v1/assignments/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createAssignmentBody
    },
      );
    }
  /**
 * Record an override reason against an existing Assignment in its audit log.
 * @summary Override an Assignment
 */
const overrideAssignment = (
    assignmentId: string,
    overrideAssignmentBody: OverrideAssignmentBody,
 ) => {
      return apiClient<OverrideAssignment201>(
      {url: `/api/v1/assignments/${assignmentId}/override`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: overrideAssignmentBody
    },
      );
    }
  /**
 * Remove a Volunteer Assignment from its TimeSlot.
 * @summary Delete an Assignment
 */
const deleteAssignment = (
    assignmentId: string,
 ) => {
      return apiClient<void>(
      {url: `/api/v1/assignments/${assignmentId}`, method: 'DELETE'
    },
      );
    }
  /**
 * List the recorded audit entries for a single Assignment.
 * @summary Get an Assignment's audit log
 */
const getAssignmentAudit = (
    assignmentId: string,
 ) => {
      return apiClient<GetAssignmentAudit200>(
      {url: `/api/v1/assignments/${assignmentId}/audit`, method: 'GET'
    },
      );
    }
  return {createAssignment,overrideAssignment,deleteAssignment,getAssignmentAudit}};
export type CreateAssignmentResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAssignments>['createAssignment']>>>
export type OverrideAssignmentResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAssignments>['overrideAssignment']>>>
export type DeleteAssignmentResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAssignments>['deleteAssignment']>>>
export type GetAssignmentAuditResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAssignments>['getAssignmentAudit']>>>
