/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Church API
 * OpenAPI spec version: 1.0.0
 */
export type ListMinistries200MinistriesItemEnforcementType = typeof ListMinistries200MinistriesItemEnforcementType[keyof typeof ListMinistries200MinistriesItemEnforcementType];


export const ListMinistries200MinistriesItemEnforcementType = {
  soft: 'soft',
  hard: 'hard',
} as const;

export type ListMinistries200MinistriesItem = {
  id: string;
  churchId: string;
  name: string;
  description?: string;
  enforcementType: ListMinistries200MinistriesItemEnforcementType;
  createdAt: string;
  updatedAt: string;
};

export type ListMinistries200 = {
  ministries: ListMinistries200MinistriesItem[];
};

export type GetScheduleBuilderDataParams = {
eventId: string;
};

export type GetScheduleBuilderData200EventsItemEventStatus = typeof GetScheduleBuilderData200EventsItemEventStatus[keyof typeof GetScheduleBuilderData200EventsItemEventStatus];


export const GetScheduleBuilderData200EventsItemEventStatus = {
  draft: 'draft',
  scheduled: 'scheduled',
  cancelled: 'cancelled',
  past: 'past',
} as const;

export type GetScheduleBuilderData200EventsItemEventEventType = typeof GetScheduleBuilderData200EventsItemEventEventType[keyof typeof GetScheduleBuilderData200EventsItemEventEventType];


export const GetScheduleBuilderData200EventsItemEventEventType = {
  hourly: 'hourly',
  day_based: 'day_based',
} as const;

export type GetScheduleBuilderData200EventsItemEvent = {
  id: string;
  churchId: string;
  planningCycleId: string;
  sourceTemplateId?: string;
  title: string;
  description?: string;
  location?: string;
  startDate: string;
  endDate: string;
  status: GetScheduleBuilderData200EventsItemEventStatus;
  eventType: GetScheduleBuilderData200EventsItemEventEventType;
  createdAt: string;
  updatedAt: string;
};

export type GetScheduleBuilderData200EventsItemSlotsItemStatus = typeof GetScheduleBuilderData200EventsItemSlotsItemStatus[keyof typeof GetScheduleBuilderData200EventsItemSlotsItemStatus];


export const GetScheduleBuilderData200EventsItemSlotsItemStatus = {
  active: 'active',
  cancelled: 'cancelled',
} as const;

export type GetScheduleBuilderData200EventsItemSlotsItemRequirementsItem = {
  id: string;
  slotId: string;
  roleId: string;
  teamId?: string;
  requiredCount: number;
  notes?: string;
};

export type GetScheduleBuilderData200EventsItemSlotsItem = {
  id: string;
  churchId: string;
  eventId: string;
  startTime: string;
  endTime: string;
  label?: string;
  status: GetScheduleBuilderData200EventsItemSlotsItemStatus;
  requirements: GetScheduleBuilderData200EventsItemSlotsItemRequirementsItem[];
};

export type GetScheduleBuilderData200EventsItem = {
  event: GetScheduleBuilderData200EventsItemEvent;
  slots: GetScheduleBuilderData200EventsItemSlotsItem[];
};

export type GetScheduleBuilderData200AssignmentsItemStatus = typeof GetScheduleBuilderData200AssignmentsItemStatus[keyof typeof GetScheduleBuilderData200AssignmentsItemStatus];


export const GetScheduleBuilderData200AssignmentsItemStatus = {
  draft: 'draft',
  pending: 'pending',
  confirmed: 'confirmed',
  declined: 'declined',
  cancelled: 'cancelled',
} as const;

export type GetScheduleBuilderData200AssignmentsItem = {
  id: string;
  churchId: string;
  slotId: string;
  volunteerId: string;
  roleId: string;
  status: GetScheduleBuilderData200AssignmentsItemStatus;
  reason?: string;
  assignedAt: string;
  assignedBy?: string;
};

export type GetScheduleBuilderData200AvailabilityItemType = typeof GetScheduleBuilderData200AvailabilityItemType[keyof typeof GetScheduleBuilderData200AvailabilityItemType];


export const GetScheduleBuilderData200AvailabilityItemType = {
  available: 'available',
  unavailable: 'unavailable',
} as const;

export type GetScheduleBuilderData200AvailabilityItem = {
  id: string;
  volunteerId: string;
  type: GetScheduleBuilderData200AvailabilityItemType;
  startTime: string;
  endTime: string;
  isAllDay: boolean;
};

export type GetScheduleBuilderData200VolunteersItem = {
  id: string;
  name: string;
};

export type GetScheduleBuilderData200RolesItem = {
  id: string;
  name: string;
};

export type GetScheduleBuilderData200 = {
  events: GetScheduleBuilderData200EventsItem[];
  assignments: GetScheduleBuilderData200AssignmentsItem[];
  availability: GetScheduleBuilderData200AvailabilityItem[];
  volunteers: GetScheduleBuilderData200VolunteersItem[];
  roles: GetScheduleBuilderData200RolesItem[];
  /** @nullable */
  callerTeamId: string | null;
};

export type ListEventsParams = {
ministryId: string;
status?: ListEventsStatus;
};

export type ListEventsStatus = typeof ListEventsStatus[keyof typeof ListEventsStatus];


export const ListEventsStatus = {
  draft: 'draft',
  scheduled: 'scheduled',
  cancelled: 'cancelled',
  past: 'past',
} as const;

export type ListEvents200EventsItemStatus = typeof ListEvents200EventsItemStatus[keyof typeof ListEvents200EventsItemStatus];


export const ListEvents200EventsItemStatus = {
  draft: 'draft',
  scheduled: 'scheduled',
  cancelled: 'cancelled',
  past: 'past',
} as const;

export type ListEvents200EventsItemEventType = typeof ListEvents200EventsItemEventType[keyof typeof ListEvents200EventsItemEventType];


export const ListEvents200EventsItemEventType = {
  hourly: 'hourly',
  day_based: 'day_based',
} as const;

export type ListEvents200EventsItem = {
  id: string;
  churchId: string;
  planningCycleId: string;
  sourceTemplateId?: string;
  title: string;
  description?: string;
  location?: string;
  startDate: string;
  endDate: string;
  status: ListEvents200EventsItemStatus;
  eventType: ListEvents200EventsItemEventType;
  createdAt: string;
  updatedAt: string;
};

export type ListEvents200 = {
  events: ListEvents200EventsItem[];
};

export type CreateSlotBody = {
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$ */
  startTime: string;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$ */
  endTime: string;
  label?: string;
};

export type CreateSlot201Status = typeof CreateSlot201Status[keyof typeof CreateSlot201Status];


export const CreateSlot201Status = {
  active: 'active',
  cancelled: 'cancelled',
} as const;

export type CreateSlot201RequirementsItem = {
  id: string;
  slotId: string;
  roleId: string;
  teamId?: string;
  requiredCount: number;
  notes?: string;
};

export type CreateSlot201 = {
  id: string;
  churchId: string;
  eventId: string;
  startTime: string;
  endTime: string;
  label?: string;
  status: CreateSlot201Status;
  requirements: CreateSlot201RequirementsItem[];
};

export type UpdateSlotBody = {
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$ */
  startTime?: string;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$ */
  endTime?: string;
  label?: string;
};

export type UpdateSlot200Status = typeof UpdateSlot200Status[keyof typeof UpdateSlot200Status];


export const UpdateSlot200Status = {
  active: 'active',
  cancelled: 'cancelled',
} as const;

export type UpdateSlot200RequirementsItem = {
  id: string;
  slotId: string;
  roleId: string;
  teamId?: string;
  requiredCount: number;
  notes?: string;
};

export type UpdateSlot200 = {
  id: string;
  churchId: string;
  eventId: string;
  startTime: string;
  endTime: string;
  label?: string;
  status: UpdateSlot200Status;
  requirements: UpdateSlot200RequirementsItem[];
};

export type OverrideAssignmentBody = {
  /** @minLength 10 */
  reason: string;
};

export type OverrideAssignment201 = {
  overridden: true;
};

export type GenerateSlotsBodyStrategy = {
  kind: 'equal-split';
  /** @maximum 9007199254740991 */
  slotDurationMinutes: number;
} | {
  kind: 'template-based';
  periods: ({
  label: string;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$ */
  startTime: string;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$ */
  endTime: string;
  requirements?: {
  roleId: string;
  teamId?: string;
  /** @maximum 9007199254740991 */
  requiredCount: number;
  notes?: string;
}[];
})[];
};

export type GenerateSlotsBody = {
  strategy: GenerateSlotsBodyStrategy;
};

export type GenerateSlots201SlotsItemStatus = typeof GenerateSlots201SlotsItemStatus[keyof typeof GenerateSlots201SlotsItemStatus];


export const GenerateSlots201SlotsItemStatus = {
  active: 'active',
  cancelled: 'cancelled',
} as const;

export type GenerateSlots201SlotsItemRequirementsItem = {
  id: string;
  slotId: string;
  roleId: string;
  teamId?: string;
  requiredCount: number;
  notes?: string;
};

export type GenerateSlots201SlotsItem = {
  id: string;
  churchId: string;
  eventId: string;
  startTime: string;
  endTime: string;
  label?: string;
  status: GenerateSlots201SlotsItemStatus;
  requirements: GenerateSlots201SlotsItemRequirementsItem[];
};

export type GenerateSlots201 = {
  slots: GenerateSlots201SlotsItem[];
};

export type UpsertSlotRequirementBody = {
  roleId: string;
  teamId?: string;
  /**
     * @minimum 1
     * @maximum 9007199254740991
     */
  requiredCount: number;
  notes?: string;
};

export type UpsertSlotRequirement200 = {
  id: string;
  slotId: string;
  roleId: string;
  teamId?: string;
  requiredCount: number;
  notes?: string;
};

export type CreateAssignmentBody = {
  slotId: string;
  volunteerId: string;
  roleId: string;
  reason?: string;
};

export type CreateAssignment201Status = typeof CreateAssignment201Status[keyof typeof CreateAssignment201Status];


export const CreateAssignment201Status = {
  draft: 'draft',
  pending: 'pending',
  confirmed: 'confirmed',
  declined: 'declined',
  cancelled: 'cancelled',
} as const;

export type CreateAssignment201 = {
  id: string;
  churchId: string;
  slotId: string;
  volunteerId: string;
  roleId: string;
  status: CreateAssignment201Status;
  reason?: string;
  assignedAt: string;
  assignedBy?: string;
};

export type GetAssignmentAudit200ItemsItemAction = typeof GetAssignmentAudit200ItemsItemAction[keyof typeof GetAssignmentAudit200ItemsItemAction];


export const GetAssignmentAudit200ItemsItemAction = {
  created: 'created',
  updated: 'updated',
  deleted: 'deleted',
  status_change: 'status_change',
  event_published: 'event_published',
  event_cancelled: 'event_cancelled',
} as const;

export type GetAssignmentAudit200ItemsItem = {
  id: string;
  assignmentId: string;
  actorId: string;
  action: GetAssignmentAudit200ItemsItemAction;
  reason?: string;
  timestamp: string;
};

export type GetAssignmentAudit200 = {
  items: GetAssignmentAudit200ItemsItem[];
};

export type CreatePlanningCycleBody = {
  /** @minLength 1 */
  name: string;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))$ */
  startDate: string;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))$ */
  endDate: string;
};

export type CreatePlanningCycle201State = typeof CreatePlanningCycle201State[keyof typeof CreatePlanningCycle201State];


export const CreatePlanningCycle201State = {
  draft: 'draft',
  locked: 'locked',
  archived: 'archived',
} as const;

export type CreatePlanningCycle201 = {
  id: string;
  churchId: string;
  name: string;
  startDate: string;
  endDate: string;
  state: CreatePlanningCycle201State;
  createdAt: string;
  updatedAt: string;
};

export type ListPlanningCyclesParams = {
state?: ListPlanningCyclesState;
};

export type ListPlanningCyclesState = typeof ListPlanningCyclesState[keyof typeof ListPlanningCyclesState];


export const ListPlanningCyclesState = {
  draft: 'draft',
  locked: 'locked',
  archived: 'archived',
} as const;

export type ListPlanningCycles200CyclesItemState = typeof ListPlanningCycles200CyclesItemState[keyof typeof ListPlanningCycles200CyclesItemState];


export const ListPlanningCycles200CyclesItemState = {
  draft: 'draft',
  locked: 'locked',
  archived: 'archived',
} as const;

export type ListPlanningCycles200CyclesItem = {
  id: string;
  churchId: string;
  name: string;
  startDate: string;
  endDate: string;
  state: ListPlanningCycles200CyclesItemState;
  createdAt: string;
  updatedAt: string;
};

export type ListPlanningCycles200 = {
  cycles: ListPlanningCycles200CyclesItem[];
};

export type GetPlanningCycle200CycleState = typeof GetPlanningCycle200CycleState[keyof typeof GetPlanningCycle200CycleState];


export const GetPlanningCycle200CycleState = {
  draft: 'draft',
  locked: 'locked',
  archived: 'archived',
} as const;

export type GetPlanningCycle200Cycle = {
  id: string;
  churchId: string;
  name: string;
  startDate: string;
  endDate: string;
  state: GetPlanningCycle200CycleState;
  createdAt: string;
  updatedAt: string;
};

export type GetPlanningCycle200EventsItemEventStatus = typeof GetPlanningCycle200EventsItemEventStatus[keyof typeof GetPlanningCycle200EventsItemEventStatus];


export const GetPlanningCycle200EventsItemEventStatus = {
  draft: 'draft',
  scheduled: 'scheduled',
  cancelled: 'cancelled',
  past: 'past',
} as const;

export type GetPlanningCycle200EventsItemEventEventType = typeof GetPlanningCycle200EventsItemEventEventType[keyof typeof GetPlanningCycle200EventsItemEventEventType];


export const GetPlanningCycle200EventsItemEventEventType = {
  hourly: 'hourly',
  day_based: 'day_based',
} as const;

export type GetPlanningCycle200EventsItemEvent = {
  id: string;
  churchId: string;
  planningCycleId: string;
  sourceTemplateId?: string;
  title: string;
  description?: string;
  location?: string;
  startDate: string;
  endDate: string;
  status: GetPlanningCycle200EventsItemEventStatus;
  eventType: GetPlanningCycle200EventsItemEventEventType;
  createdAt: string;
  updatedAt: string;
};

export type GetPlanningCycle200EventsItemSlotsItemStatus = typeof GetPlanningCycle200EventsItemSlotsItemStatus[keyof typeof GetPlanningCycle200EventsItemSlotsItemStatus];


export const GetPlanningCycle200EventsItemSlotsItemStatus = {
  active: 'active',
  cancelled: 'cancelled',
} as const;

export type GetPlanningCycle200EventsItemSlotsItemRequirementsItem = {
  id: string;
  slotId: string;
  roleId: string;
  teamId?: string;
  requiredCount: number;
  notes?: string;
};

export type GetPlanningCycle200EventsItemSlotsItem = {
  id: string;
  churchId: string;
  eventId: string;
  startTime: string;
  endTime: string;
  label?: string;
  status: GetPlanningCycle200EventsItemSlotsItemStatus;
  requirements: GetPlanningCycle200EventsItemSlotsItemRequirementsItem[];
};

export type GetPlanningCycle200EventsItem = {
  event: GetPlanningCycle200EventsItemEvent;
  slots: GetPlanningCycle200EventsItemSlotsItem[];
};

export type GetPlanningCycle200 = {
  cycle: GetPlanningCycle200Cycle;
  events: GetPlanningCycle200EventsItem[];
};

export type CreateEventTemplateBodyBlocksItem = {
  /** @minLength 1 */
  label: string;
  /** @pattern ^\d{2}:\d{2}(:\d{2})?$ */
  startTime: string;
  /** @pattern ^\d{2}:\d{2}(:\d{2})?$ */
  endTime: string;
  /**
     * @minimum 0
     * @maximum 9007199254740991
     */
  order: number;
};

export type CreateEventTemplateBody = {
  /** @minLength 1 */
  name: string;
  /**
     * @minimum 0
     * @maximum 6
     */
  weekday: number;
  blocks: CreateEventTemplateBodyBlocksItem[];
};

export type CreateEventTemplate201BlocksItem = {
  id: string;
  churchId: string;
  templateId: string;
  label: string;
  startTime: string;
  endTime: string;
  order: number;
};

export type CreateEventTemplate201 = {
  id: string;
  churchId: string;
  name: string;
  weekday: number;
  blocks: CreateEventTemplate201BlocksItem[];
  createdAt: string;
  updatedAt: string;
};

export type ListEventTemplates200TemplatesItemBlocksItem = {
  id: string;
  churchId: string;
  templateId: string;
  label: string;
  startTime: string;
  endTime: string;
  order: number;
};

export type ListEventTemplates200TemplatesItem = {
  id: string;
  churchId: string;
  name: string;
  weekday: number;
  blocks: ListEventTemplates200TemplatesItemBlocksItem[];
  createdAt: string;
  updatedAt: string;
};

export type ListEventTemplates200 = {
  templates: ListEventTemplates200TemplatesItem[];
};

export type UpdateEventTemplateBodyBlocksItem = {
  /** @minLength 1 */
  label: string;
  /** @pattern ^\d{2}:\d{2}(:\d{2})?$ */
  startTime: string;
  /** @pattern ^\d{2}:\d{2}(:\d{2})?$ */
  endTime: string;
  /**
     * @minimum 0
     * @maximum 9007199254740991
     */
  order: number;
};

export type UpdateEventTemplateBody = {
  /** @minLength 1 */
  name: string;
  /**
     * @minimum 0
     * @maximum 6
     */
  weekday: number;
  blocks: UpdateEventTemplateBodyBlocksItem[];
};

export type UpdateEventTemplate200BlocksItem = {
  id: string;
  churchId: string;
  templateId: string;
  label: string;
  startTime: string;
  endTime: string;
  order: number;
};

export type UpdateEventTemplate200 = {
  id: string;
  churchId: string;
  name: string;
  weekday: number;
  blocks: UpdateEventTemplate200BlocksItem[];
  createdAt: string;
  updatedAt: string;
};

export type ApplyPlanningTemplatesBody = {
  /** @minItems 1 */
  templateIds: string[];
};

export type ApplyPlanningTemplates201 = {
  generatedEventCount: number;
  generatedSlotCount: number;
};

export type CreatePlanningEventBodyEventType = typeof CreatePlanningEventBodyEventType[keyof typeof CreatePlanningEventBodyEventType];


export const CreatePlanningEventBodyEventType = {
  hourly: 'hourly',
  day_based: 'day_based',
} as const;

export type CreatePlanningEventBody = {
  /** @minLength 1 */
  title: string;
  description?: string;
  location?: string;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$ */
  startDate: string;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$ */
  endDate: string;
  eventType?: CreatePlanningEventBodyEventType;
};

export type CreatePlanningEvent201Status = typeof CreatePlanningEvent201Status[keyof typeof CreatePlanningEvent201Status];


export const CreatePlanningEvent201Status = {
  draft: 'draft',
  scheduled: 'scheduled',
  cancelled: 'cancelled',
  past: 'past',
} as const;

export type CreatePlanningEvent201EventType = typeof CreatePlanningEvent201EventType[keyof typeof CreatePlanningEvent201EventType];


export const CreatePlanningEvent201EventType = {
  hourly: 'hourly',
  day_based: 'day_based',
} as const;

export type CreatePlanningEvent201 = {
  id: string;
  churchId: string;
  planningCycleId: string;
  sourceTemplateId?: string;
  title: string;
  description?: string;
  location?: string;
  startDate: string;
  endDate: string;
  status: CreatePlanningEvent201Status;
  eventType: CreatePlanningEvent201EventType;
  createdAt: string;
  updatedAt: string;
};

export type UpdatePlanningEventBodyEventType = typeof UpdatePlanningEventBodyEventType[keyof typeof UpdatePlanningEventBodyEventType];


export const UpdatePlanningEventBodyEventType = {
  hourly: 'hourly',
  day_based: 'day_based',
} as const;

export type UpdatePlanningEventBody = {
  /** @minLength 1 */
  title?: string;
  description?: string;
  location?: string;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$ */
  startDate?: string;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$ */
  endDate?: string;
  eventType?: UpdatePlanningEventBodyEventType;
};

export type UpdatePlanningEvent200Status = typeof UpdatePlanningEvent200Status[keyof typeof UpdatePlanningEvent200Status];


export const UpdatePlanningEvent200Status = {
  draft: 'draft',
  scheduled: 'scheduled',
  cancelled: 'cancelled',
  past: 'past',
} as const;

export type UpdatePlanningEvent200EventType = typeof UpdatePlanningEvent200EventType[keyof typeof UpdatePlanningEvent200EventType];


export const UpdatePlanningEvent200EventType = {
  hourly: 'hourly',
  day_based: 'day_based',
} as const;

export type UpdatePlanningEvent200 = {
  id: string;
  churchId: string;
  planningCycleId: string;
  sourceTemplateId?: string;
  title: string;
  description?: string;
  location?: string;
  startDate: string;
  endDate: string;
  status: UpdatePlanningEvent200Status;
  eventType: UpdatePlanningEvent200EventType;
  createdAt: string;
  updatedAt: string;
};

export type ListFeatureFlags200Flags = {[key: string]: boolean};

export type ListFeatureFlags200 = {
  flags: ListFeatureFlags200Flags;
};

export type GetVolunteerDashboard200AvailabilityTasksItemEventType = typeof GetVolunteerDashboard200AvailabilityTasksItemEventType[keyof typeof GetVolunteerDashboard200AvailabilityTasksItemEventType];


export const GetVolunteerDashboard200AvailabilityTasksItemEventType = {
  hourly: 'hourly',
  day_based: 'day_based',
} as const;

export type GetVolunteerDashboard200AvailabilityTasksItemCompletionState = typeof GetVolunteerDashboard200AvailabilityTasksItemCompletionState[keyof typeof GetVolunteerDashboard200AvailabilityTasksItemCompletionState];


export const GetVolunteerDashboard200AvailabilityTasksItemCompletionState = {
  missing: 'missing',
  partial: 'partial',
  complete: 'complete',
} as const;

export type GetVolunteerDashboard200AvailabilityTasksItem = {
  eventId: string;
  eventTitle: string;
  ministryId: string;
  ministryName: string;
  eventType: GetVolunteerDashboard200AvailabilityTasksItemEventType;
  eventStart: string;
  eventEnd: string;
  completionState: GetVolunteerDashboard200AvailabilityTasksItemCompletionState;
};

export type GetVolunteerDashboard200UpcomingAssignmentGroupsItemAggregateResponseState = typeof GetVolunteerDashboard200UpcomingAssignmentGroupsItemAggregateResponseState[keyof typeof GetVolunteerDashboard200UpcomingAssignmentGroupsItemAggregateResponseState];


export const GetVolunteerDashboard200UpcomingAssignmentGroupsItemAggregateResponseState = {
  pending: 'pending',
  confirmed: 'confirmed',
  mixed: 'mixed',
  declined: 'declined',
} as const;

export type GetVolunteerDashboard200UpcomingAssignmentGroupsItemAssignmentsItemStatus = typeof GetVolunteerDashboard200UpcomingAssignmentGroupsItemAssignmentsItemStatus[keyof typeof GetVolunteerDashboard200UpcomingAssignmentGroupsItemAssignmentsItemStatus];


export const GetVolunteerDashboard200UpcomingAssignmentGroupsItemAssignmentsItemStatus = {
  pending: 'pending',
  confirmed: 'confirmed',
  declined: 'declined',
} as const;

export type GetVolunteerDashboard200UpcomingAssignmentGroupsItemAssignmentsItemTimingState = typeof GetVolunteerDashboard200UpcomingAssignmentGroupsItemAssignmentsItemTimingState[keyof typeof GetVolunteerDashboard200UpcomingAssignmentGroupsItemAssignmentsItemTimingState];


export const GetVolunteerDashboard200UpcomingAssignmentGroupsItemAssignmentsItemTimingState = {
  in_progress: 'in_progress',
  upcoming: 'upcoming',
} as const;

export type GetVolunteerDashboard200UpcomingAssignmentGroupsItemAssignmentsItem = {
  assignmentId: string;
  slotId: string;
  roleId: string;
  roleName: string;
  teamId?: string;
  teamName?: string;
  startTime: string;
  endTime: string;
  status: GetVolunteerDashboard200UpcomingAssignmentGroupsItemAssignmentsItemStatus;
  timingState: GetVolunteerDashboard200UpcomingAssignmentGroupsItemAssignmentsItemTimingState;
  canRespond: boolean;
};

export type GetVolunteerDashboard200UpcomingAssignmentGroupsItem = {
  eventId: string;
  eventTitle: string;
  ministryId: string;
  ministryName: string;
  eventStart: string;
  aggregateResponseState: GetVolunteerDashboard200UpcomingAssignmentGroupsItemAggregateResponseState;
  hasPendingResponse: boolean;
  assignments: GetVolunteerDashboard200UpcomingAssignmentGroupsItemAssignmentsItem[];
};

export type GetVolunteerDashboard200NotificationPreviewItem = {
  id: string;
  type: string;
  title: string;
  body: string;
  readAt?: string;
  createdAt: string;
};

export type GetVolunteerDashboard200MinistryOptionsItem = {
  id: string;
  name: string;
};

export type GetVolunteerDashboard200 = {
  availabilityTasks: GetVolunteerDashboard200AvailabilityTasksItem[];
  upcomingAssignmentGroups: GetVolunteerDashboard200UpcomingAssignmentGroupsItem[];
  unreadNotificationCount: number;
  notificationPreview: GetVolunteerDashboard200NotificationPreviewItem[];
  defaultMinistryId?: string;
  ministryOptions: GetVolunteerDashboard200MinistryOptionsItem[];
};

export type GetMyAssignments200AssignmentsItemStatus = typeof GetMyAssignments200AssignmentsItemStatus[keyof typeof GetMyAssignments200AssignmentsItemStatus];


export const GetMyAssignments200AssignmentsItemStatus = {
  draft: 'draft',
  pending: 'pending',
  confirmed: 'confirmed',
  declined: 'declined',
  cancelled: 'cancelled',
} as const;

export type GetMyAssignments200AssignmentsItem = {
  id: string;
  churchId: string;
  slotId: string;
  volunteerId: string;
  roleId: string;
  status: GetMyAssignments200AssignmentsItemStatus;
  reason?: string;
  assignedAt: string;
  assignedBy?: string;
};

export type GetMyAssignments200 = {
  assignments: GetMyAssignments200AssignmentsItem[];
};

export type GetMinistrySchedule200EventsItemRowsItemConfirmationState = typeof GetMinistrySchedule200EventsItemRowsItemConfirmationState[keyof typeof GetMinistrySchedule200EventsItemRowsItemConfirmationState];


export const GetMinistrySchedule200EventsItemRowsItemConfirmationState = {
  pending: 'pending',
  confirmed: 'confirmed',
  declined: 'declined',
  open: 'open',
} as const;

export type GetMinistrySchedule200EventsItemRowsItem = {
  slotId: string;
  slotLabel: string;
  roleName: string;
  teamName?: string;
  volunteerDisplayName?: string;
  confirmationState: GetMinistrySchedule200EventsItemRowsItemConfirmationState;
};

export type GetMinistrySchedule200EventsItem = {
  eventId: string;
  title: string;
  startDate: string;
  endDate: string;
  assignmentCount: number;
  rows: GetMinistrySchedule200EventsItemRowsItem[];
};

export type GetMinistrySchedule200 = {
  ministryId: string;
  ministryName: string;
  events: GetMinistrySchedule200EventsItem[];
};

export type GetMyAvailability200AvailabilityItemType = typeof GetMyAvailability200AvailabilityItemType[keyof typeof GetMyAvailability200AvailabilityItemType];


export const GetMyAvailability200AvailabilityItemType = {
  available: 'available',
  unavailable: 'unavailable',
} as const;

export type GetMyAvailability200AvailabilityItem = {
  id: string;
  churchId: string;
  volunteerId: string;
  eventId?: string;
  type: GetMyAvailability200AvailabilityItemType;
  startTime: string;
  endTime: string;
  isAllDay: boolean;
  reason?: string;
  repeatRule?: string;
};

export type GetMyAvailability200 = {
  availability: GetMyAvailability200AvailabilityItem[];
};

export type RespondToAssignmentBodyResponse = typeof RespondToAssignmentBodyResponse[keyof typeof RespondToAssignmentBodyResponse];


export const RespondToAssignmentBodyResponse = {
  accepted: 'accepted',
  declined: 'declined',
} as const;

export type RespondToAssignmentBody = {
  response: RespondToAssignmentBodyResponse;
  reason?: string;
};

export type RespondToAssignment200Status = typeof RespondToAssignment200Status[keyof typeof RespondToAssignment200Status];


export const RespondToAssignment200Status = {
  draft: 'draft',
  pending: 'pending',
  confirmed: 'confirmed',
  declined: 'declined',
  cancelled: 'cancelled',
} as const;

export type RespondToAssignment200 = {
  id: string;
  churchId: string;
  slotId: string;
  volunteerId: string;
  roleId: string;
  status: RespondToAssignment200Status;
  reason?: string;
  assignedAt: string;
  assignedBy?: string;
};

export type GetNotifications200ItemsItemType = typeof GetNotifications200ItemsItemType[keyof typeof GetNotifications200ItemsItemType];


export const GetNotifications200ItemsItemType = {
  schedule_published: 'schedule_published',
  assignment_added: 'assignment_added',
  assignment_changed: 'assignment_changed',
  assignment_removed: 'assignment_removed',
  availability_reminder: 'availability_reminder',
  assignment_reminder: 'assignment_reminder',
} as const;

export type GetNotifications200ItemsItemPayload = {[key: string]: string | null};

export type GetNotifications200ItemsItem = {
  id: string;
  volunteerId: string;
  ministryId?: string;
  eventId?: string;
  assignmentId?: string;
  type: GetNotifications200ItemsItemType;
  title: string;
  body: string;
  payload: GetNotifications200ItemsItemPayload;
  readAt?: string;
  createdAt: string;
};

export type GetNotifications200 = {
  items: GetNotifications200ItemsItem[];
  nextCursor?: string;
};

export type MarkNotificationRead200 = {
  marked: boolean;
};

