/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Church API
 * OpenAPI spec version: 1.0.0
 */
import type {
  GetScheduleBuilderData200,
  GetScheduleBuilderDataParams,
  ListEvents200,
  ListEventsParams
} from './churchAPI.schemas';

import { apiClient } from '../../utils/api-client';




  export const getEvents = () => {
/**
 * Get the TimeSlots, Shifts, and eligible Volunteers needed to build a schedule for an Event.
 * @summary Get schedule builder data for an Event
 */
const getScheduleBuilderData = (
    params: GetScheduleBuilderDataParams,
 ) => {
      return apiClient<GetScheduleBuilderData200>(
      {url: `/api/v1/events/schedule-builder`, method: 'GET',
        params
    },
      );
    }
  /**
 * List Events for a Ministry, optionally filtered by status.
 * @summary List a Ministry's Events
 */
const listEvents = (
    params: ListEventsParams,
 ) => {
      return apiClient<ListEvents200>(
      {url: `/api/v1/events/`, method: 'GET',
        params
    },
      );
    }
  /**
 * Cancel an Event.
 * @summary Cancel an Event
 */
const cancelEvent = (
    eventId: string,
 ) => {
      return apiClient<void>(
      {url: `/api/v1/events/${eventId}/cancel`, method: 'POST'
    },
      );
    }
  /**
 * Send an availability reminder VolunteerNotification for an Event.
 * @summary Send Event reminders
 */
const sendReminders = (
    eventId: string,
 ) => {
      return apiClient<void>(
      {url: `/api/v1/events/${eventId}/reminders`, method: 'POST'
    },
      );
    }
  return {getScheduleBuilderData,listEvents,cancelEvent,sendReminders}};
export type GetScheduleBuilderDataResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEvents>['getScheduleBuilderData']>>>
export type ListEventsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEvents>['listEvents']>>>
export type CancelEventResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEvents>['cancelEvent']>>>
export type SendRemindersResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEvents>['sendReminders']>>>
