/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Church API
 * OpenAPI spec version: 1.0.0
 */
import type {
  GetScheduleBuilderData200,
  GetScheduleBuilderDataParams,
  ListEvents200,
  ListEventsParams
} from './churchAPI.schemas';

import { apiClient } from '../../utils/api-client';




  export const getEvents = () => {
const getScheduleBuilderData = (
    params: GetScheduleBuilderDataParams,
 ) => {
      return apiClient<GetScheduleBuilderData200>(
      {url: `/api/v1/events/schedule-builder`, method: 'GET',
        params
    },
      );
    }
  const listEvents = (
    params: ListEventsParams,
 ) => {
      return apiClient<ListEvents200>(
      {url: `/api/v1/events/`, method: 'GET',
        params
    },
      );
    }
  const cancelEvent = (
    eventId: string,
 ) => {
      return apiClient<void>(
      {url: `/api/v1/events/${eventId}/cancel`, method: 'POST'
    },
      );
    }
  const sendReminders = (
    eventId: string,
 ) => {
      return apiClient<void>(
      {url: `/api/v1/events/${eventId}/reminders`, method: 'POST'
    },
      );
    }
  return {getScheduleBuilderData,listEvents,cancelEvent,sendReminders}};
export type GetScheduleBuilderDataResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEvents>['getScheduleBuilderData']>>>
export type ListEventsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEvents>['listEvents']>>>
export type CancelEventResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEvents>['cancelEvent']>>>
export type SendRemindersResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEvents>['sendReminders']>>>
