/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Church API
 * OpenAPI spec version: 1.0.0
 */
import type {
  GetFeatureFlags200
} from './churchAPI.schemas';

import { apiClient } from '../../utils/api-client';




  export const getFeatureFlags = () => {
const getFeatureFlags = (

 ) => {
      return apiClient<GetFeatureFlags200>(
      {url: `/api/v1/feature-flags/`, method: 'GET'
    },
      );
    }
  return {getFeatureFlags}};
export type GetFeatureFlagsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getFeatureFlags>['getFeatureFlags']>>>
