/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Church API
 * OpenAPI spec version: 1.0.0
 */
import type {
  ListMinistries200,
  MintMinistryInvitation201,
  MintMinistryInvitationBody,
  ResendMinistryInvitation200
} from './churchAPI.schemas';

import { apiClient } from '../../utils/api-client';




  export const getMinistries = () => {
/**
 * List the Ministries the current Volunteer leads within the Active Church.
 * @summary List the caller's led Ministries
 */
const listMinistries = (

 ) => {
      return apiClient<ListMinistries200>(
      {url: `/api/v1/ministries/`, method: 'GET'
    },
      );
    }
  /**
 * Create a Ministry Invitation granting a Ministry Access Level and Roles to an emailed recipient.
 * @summary Mint a Ministry Invitation
 */
const mintMinistryInvitation = (
    ministryId: string,
    mintMinistryInvitationBody: MintMinistryInvitationBody,
 ) => {
      return apiClient<MintMinistryInvitation201>(
      {url: `/api/v1/ministries/${ministryId}/invitations`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: mintMinistryInvitationBody
    },
      );
    }
  /**
 * Resend the delivery email for a Ministry Invitation.
 * @summary Resend a Ministry Invitation
 */
const resendMinistryInvitation = (
    ministryId: string,
    invitationId: string,
 ) => {
      return apiClient<ResendMinistryInvitation200>(
      {url: `/api/v1/ministries/${ministryId}/invitations/${invitationId}/resend`, method: 'POST'
    },
      );
    }
  return {listMinistries,mintMinistryInvitation,resendMinistryInvitation}};
export type ListMinistriesResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMinistries>['listMinistries']>>>
export type MintMinistryInvitationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMinistries>['mintMinistryInvitation']>>>
export type ResendMinistryInvitationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMinistries>['resendMinistryInvitation']>>>
