/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Church API
 * OpenAPI spec version: 1.0.0
 */
import type {
  ApplyPlanningTemplates201,
  ApplyPlanningTemplatesBody,
  CreateEventTemplate201,
  CreateEventTemplateBody,
  CreatePlanningCycle201,
  CreatePlanningCycleBody,
  CreatePlanningEvent201,
  CreatePlanningEventBody,
  CreatePlanningEventSlot201,
  CreatePlanningEventSlotBody,
  GetMinistryServingProfile200,
  GetPlanningCycle200,
  ListEventTemplates200,
  ListPlanningCycles200,
  ListPlanningCyclesParams,
  SetMinistryDefaultDirection200,
  SetMinistryDefaultDirectionBody,
  UpdateEventTemplate200,
  UpdateEventTemplateBody,
  UpdatePlanningEvent200,
  UpdatePlanningEventBody,
  UpdatePlanningEventSlot200,
  UpdatePlanningEventSlotBody,
  UpsertMinistryServingProfile200,
  UpsertMinistryServingProfileBody
} from './churchAPI.schemas';

import { apiClient } from '../../utils/api-client';




  export const getPlanning = () => {
const createPlanningCycle = (
    createPlanningCycleBody: CreatePlanningCycleBody,
 ) => {
      return apiClient<CreatePlanningCycle201>(
      {url: `/api/v1/admin/planning-cycles`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createPlanningCycleBody
    },
      );
    }
  const listPlanningCycles = (
    params?: ListPlanningCyclesParams,
 ) => {
      return apiClient<ListPlanningCycles200>(
      {url: `/api/v1/admin/planning-cycles`, method: 'GET',
        params
    },
      );
    }
  const getPlanningCycle = (
    cycleId: string,
 ) => {
      return apiClient<GetPlanningCycle200>(
      {url: `/api/v1/admin/planning-cycles/${cycleId}`, method: 'GET'
    },
      );
    }
  const lockPlanningCycle = (
    cycleId: string,
 ) => {
      return apiClient<void>(
      {url: `/api/v1/admin/planning-cycles/${cycleId}/lock`, method: 'POST'
    },
      );
    }
  const reopenPlanningEvent = (
    cycleId: string,
    eventId: string,
 ) => {
      return apiClient<void>(
      {url: `/api/v1/admin/planning-cycles/${cycleId}/events/${eventId}/reopen`, method: 'POST'
    },
      );
    }
  const createEventTemplate = (
    createEventTemplateBody: CreateEventTemplateBody,
 ) => {
      return apiClient<CreateEventTemplate201>(
      {url: `/api/v1/admin/event-templates`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createEventTemplateBody
    },
      );
    }
  const listEventTemplates = (

 ) => {
      return apiClient<ListEventTemplates200>(
      {url: `/api/v1/admin/event-templates`, method: 'GET'
    },
      );
    }
  const updateEventTemplate = (
    templateId: string,
    updateEventTemplateBody: UpdateEventTemplateBody,
 ) => {
      return apiClient<UpdateEventTemplate200>(
      {url: `/api/v1/admin/event-templates/${templateId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateEventTemplateBody
    },
      );
    }
  const deleteEventTemplate = (
    templateId: string,
 ) => {
      return apiClient<void>(
      {url: `/api/v1/admin/event-templates/${templateId}`, method: 'DELETE'
    },
      );
    }
  const applyPlanningTemplates = (
    cycleId: string,
    applyPlanningTemplatesBody: ApplyPlanningTemplatesBody,
 ) => {
      return apiClient<ApplyPlanningTemplates201>(
      {url: `/api/v1/admin/planning-cycles/${cycleId}/apply-templates`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: applyPlanningTemplatesBody
    },
      );
    }
  const createPlanningEvent = (
    cycleId: string,
    createPlanningEventBody: CreatePlanningEventBody,
 ) => {
      return apiClient<CreatePlanningEvent201>(
      {url: `/api/v1/admin/planning-cycles/${cycleId}/events`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createPlanningEventBody
    },
      );
    }
  const updatePlanningEvent = (
    cycleId: string,
    eventId: string,
    updatePlanningEventBody: UpdatePlanningEventBody,
 ) => {
      return apiClient<UpdatePlanningEvent200>(
      {url: `/api/v1/admin/planning-cycles/${cycleId}/events/${eventId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updatePlanningEventBody
    },
      );
    }
  const cancelPlanningEvent = (
    cycleId: string,
    eventId: string,
 ) => {
      return apiClient<void>(
      {url: `/api/v1/admin/planning-cycles/${cycleId}/events/${eventId}/cancel`, method: 'POST'
    },
      );
    }
  const createPlanningEventSlot = (
    cycleId: string,
    eventId: string,
    createPlanningEventSlotBody: CreatePlanningEventSlotBody,
 ) => {
      return apiClient<CreatePlanningEventSlot201>(
      {url: `/api/v1/admin/planning-cycles/${cycleId}/events/${eventId}/slots`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createPlanningEventSlotBody
    },
      );
    }
  const updatePlanningEventSlot = (
    cycleId: string,
    eventId: string,
    slotId: string,
    updatePlanningEventSlotBody: UpdatePlanningEventSlotBody,
 ) => {
      return apiClient<UpdatePlanningEventSlot200>(
      {url: `/api/v1/admin/planning-cycles/${cycleId}/events/${eventId}/slots/${slotId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updatePlanningEventSlotBody
    },
      );
    }
  const deletePlanningEventSlot = (
    cycleId: string,
    eventId: string,
    slotId: string,
 ) => {
      return apiClient<void>(
      {url: `/api/v1/admin/planning-cycles/${cycleId}/events/${eventId}/slots/${slotId}`, method: 'DELETE'
    },
      );
    }
  /**
 * Get the serving profile for a specific ministry, including roles and teams.
 * @summary getMinistryServingProfile
 */
const getMinistryServingProfile = (
    ministryId: string,
 ) => {
      return apiClient<GetMinistryServingProfile200>(
      {url: `/api/v1/admin/ministries/${ministryId}/serving-profile`, method: 'GET'
    },
      );
    }
  const upsertMinistryServingProfile = (
    ministryId: string,
    upsertMinistryServingProfileBody: UpsertMinistryServingProfileBody,
 ) => {
      return apiClient<UpsertMinistryServingProfile200>(
      {url: `/api/v1/admin/ministries/${ministryId}/serving-profile`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: upsertMinistryServingProfileBody
    },
      );
    }
  const setMinistryDefaultDirection = (
    ministryId: string,
    setMinistryDefaultDirectionBody: SetMinistryDefaultDirectionBody,
 ) => {
      return apiClient<SetMinistryDefaultDirection200>(
      {url: `/api/v1/admin/ministries/${ministryId}/default-direction`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: setMinistryDefaultDirectionBody
    },
      );
    }
  return {createPlanningCycle,listPlanningCycles,getPlanningCycle,lockPlanningCycle,reopenPlanningEvent,createEventTemplate,listEventTemplates,updateEventTemplate,deleteEventTemplate,applyPlanningTemplates,createPlanningEvent,updatePlanningEvent,cancelPlanningEvent,createPlanningEventSlot,updatePlanningEventSlot,deletePlanningEventSlot,getMinistryServingProfile,upsertMinistryServingProfile,setMinistryDefaultDirection}};
export type CreatePlanningCycleResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getPlanning>['createPlanningCycle']>>>
export type ListPlanningCyclesResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getPlanning>['listPlanningCycles']>>>
export type GetPlanningCycleResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getPlanning>['getPlanningCycle']>>>
export type LockPlanningCycleResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getPlanning>['lockPlanningCycle']>>>
export type ReopenPlanningEventResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getPlanning>['reopenPlanningEvent']>>>
export type CreateEventTemplateResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getPlanning>['createEventTemplate']>>>
export type ListEventTemplatesResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getPlanning>['listEventTemplates']>>>
export type UpdateEventTemplateResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getPlanning>['updateEventTemplate']>>>
export type DeleteEventTemplateResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getPlanning>['deleteEventTemplate']>>>
export type ApplyPlanningTemplatesResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getPlanning>['applyPlanningTemplates']>>>
export type CreatePlanningEventResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getPlanning>['createPlanningEvent']>>>
export type UpdatePlanningEventResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getPlanning>['updatePlanningEvent']>>>
export type CancelPlanningEventResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getPlanning>['cancelPlanningEvent']>>>
export type CreatePlanningEventSlotResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getPlanning>['createPlanningEventSlot']>>>
export type UpdatePlanningEventSlotResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getPlanning>['updatePlanningEventSlot']>>>
export type DeletePlanningEventSlotResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getPlanning>['deletePlanningEventSlot']>>>
export type GetMinistryServingProfileResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getPlanning>['getMinistryServingProfile']>>>
export type UpsertMinistryServingProfileResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getPlanning>['upsertMinistryServingProfile']>>>
export type SetMinistryDefaultDirectionResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getPlanning>['setMinistryDefaultDirection']>>>
