/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Church API
 * OpenAPI spec version: 1.0.0
 */
import type {
  ApplyPlanningTemplates201,
  ApplyPlanningTemplatesBody,
  CreateEventTemplate201,
  CreateEventTemplateBody,
  CreatePlanningCycle201,
  CreatePlanningCycleBody,
  CreatePlanningEvent201,
  CreatePlanningEventBody,
  CreatePlanningEventSlot201,
  CreatePlanningEventSlotBody,
  GetMinistryServingProfile200,
  GetPlanningCycle200,
  ListEventTemplates200,
  ListPlanningCycles200,
  ListPlanningCyclesParams,
  SetMinistryDefaultDirection200,
  SetMinistryDefaultDirectionBody,
  UpdateEventTemplate200,
  UpdateEventTemplateBody,
  UpdatePlanningEvent200,
  UpdatePlanningEventBody,
  UpdatePlanningEventSlot200,
  UpdatePlanningEventSlotBody,
  UpsertMinistryServingProfile200,
  UpsertMinistryServingProfileBody
} from './churchAPI.schemas';

import { apiClient } from '../../utils/api-client';




  export const getPlanning = () => {
/**
 * Create a new PlanningCycle spanning a CalendarDay range for the Church.
 * @summary Create a PlanningCycle
 */
const createPlanningCycle = (
    createPlanningCycleBody: CreatePlanningCycleBody,
 ) => {
      return apiClient<CreatePlanningCycle201>(
      {url: `/api/v1/admin/planning-cycles`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createPlanningCycleBody
    },
      );
    }
  /**
 * List the Church PlanningCycles, optionally filtered by state.
 * @summary List PlanningCycles
 */
const listPlanningCycles = (
    params?: ListPlanningCyclesParams,
 ) => {
      return apiClient<ListPlanningCycles200>(
      {url: `/api/v1/admin/planning-cycles`, method: 'GET',
        params
    },
      );
    }
  /**
 * Get the details of a single PlanningCycle.
 * @summary Get a PlanningCycle
 */
const getPlanningCycle = (
    cycleId: string,
 ) => {
      return apiClient<GetPlanningCycle200>(
      {url: `/api/v1/admin/planning-cycles/${cycleId}`, method: 'GET'
    },
      );
    }
  /**
 * Lock a PlanningCycle, transitioning its Events from draft to scheduled.
 * @summary Lock a PlanningCycle
 */
const lockPlanningCycle = (
    cycleId: string,
 ) => {
      return apiClient<void>(
      {url: `/api/v1/admin/planning-cycles/${cycleId}/lock`, method: 'POST'
    },
      );
    }
  /**
 * Move a scheduled Event in a locked PlanningCycle back to draft so it can be edited.
 * @summary Reopen an Event for editing
 */
const reopenPlanningEvent = (
    cycleId: string,
    eventId: string,
 ) => {
      return apiClient<void>(
      {url: `/api/v1/admin/planning-cycles/${cycleId}/events/${eventId}/reopen`, method: 'POST'
    },
      );
    }
  /**
 * Create a church-owned EventTemplate with its ordered TimeBlocks for a given weekday.
 * @summary Create an EventTemplate
 */
const createEventTemplate = (
    createEventTemplateBody: CreateEventTemplateBody,
 ) => {
      return apiClient<CreateEventTemplate201>(
      {url: `/api/v1/admin/event-templates`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createEventTemplateBody
    },
      );
    }
  /**
 * List the Church EventTemplates.
 * @summary List EventTemplates
 */
const listEventTemplates = (

 ) => {
      return apiClient<ListEventTemplates200>(
      {url: `/api/v1/admin/event-templates`, method: 'GET'
    },
      );
    }
  /**
 * Replace an EventTemplate's name, weekday, and TimeBlocks.
 * @summary Update an EventTemplate
 */
const updateEventTemplate = (
    templateId: string,
    updateEventTemplateBody: UpdateEventTemplateBody,
 ) => {
      return apiClient<UpdateEventTemplate200>(
      {url: `/api/v1/admin/event-templates/${templateId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateEventTemplateBody
    },
      );
    }
  /**
 * Delete an EventTemplate from the Church.
 * @summary Delete an EventTemplate
 */
const deleteEventTemplate = (
    templateId: string,
 ) => {
      return apiClient<void>(
      {url: `/api/v1/admin/event-templates/${templateId}`, method: 'DELETE'
    },
      );
    }
  /**
 * Generate one Event per matching CalendarDay in the PlanningCycle for each selected EventTemplate, with one TimeSlot per TimeBlock.
 * @summary Apply EventTemplates to a PlanningCycle
 */
const applyPlanningTemplates = (
    cycleId: string,
    applyPlanningTemplatesBody: ApplyPlanningTemplatesBody,
 ) => {
      return apiClient<ApplyPlanningTemplates201>(
      {url: `/api/v1/admin/planning-cycles/${cycleId}/apply-templates`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: applyPlanningTemplatesBody
    },
      );
    }
  /**
 * Create a one-off Event within a PlanningCycle without using an EventTemplate.
 * @summary Create a manual Event
 */
const createPlanningEvent = (
    cycleId: string,
    createPlanningEventBody: CreatePlanningEventBody,
 ) => {
      return apiClient<CreatePlanningEvent201>(
      {url: `/api/v1/admin/planning-cycles/${cycleId}/events`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createPlanningEventBody
    },
      );
    }
  /**
 * Update an Event's title, description, location, or scheduled Instants.
 * @summary Update an Event
 */
const updatePlanningEvent = (
    cycleId: string,
    eventId: string,
    updatePlanningEventBody: UpdatePlanningEventBody,
 ) => {
      return apiClient<UpdatePlanningEvent200>(
      {url: `/api/v1/admin/planning-cycles/${cycleId}/events/${eventId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updatePlanningEventBody
    },
      );
    }
  /**
 * Cancel an Event within its PlanningCycle.
 * @summary Cancel an Event
 */
const cancelPlanningEvent = (
    cycleId: string,
    eventId: string,
 ) => {
      return apiClient<void>(
      {url: `/api/v1/admin/planning-cycles/${cycleId}/events/${eventId}/cancel`, method: 'POST'
    },
      );
    }
  /**
 * Create a church-level TimeSlot within an Event.
 * @summary Create a TimeSlot on an Event
 */
const createPlanningEventSlot = (
    cycleId: string,
    eventId: string,
    createPlanningEventSlotBody: CreatePlanningEventSlotBody,
 ) => {
      return apiClient<CreatePlanningEventSlot201>(
      {url: `/api/v1/admin/planning-cycles/${cycleId}/events/${eventId}/slots`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createPlanningEventSlotBody
    },
      );
    }
  /**
 * Update a TimeSlot's bounds or label.
 * @summary Update a TimeSlot
 */
const updatePlanningEventSlot = (
    cycleId: string,
    eventId: string,
    slotId: string,
    updatePlanningEventSlotBody: UpdatePlanningEventSlotBody,
 ) => {
      return apiClient<UpdatePlanningEventSlot200>(
      {url: `/api/v1/admin/planning-cycles/${cycleId}/events/${eventId}/slots/${slotId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updatePlanningEventSlotBody
    },
      );
    }
  /**
 * Delete a TimeSlot from an Event.
 * @summary Delete a TimeSlot
 */
const deletePlanningEventSlot = (
    cycleId: string,
    eventId: string,
    slotId: string,
 ) => {
      return apiClient<void>(
      {url: `/api/v1/admin/planning-cycles/${cycleId}/events/${eventId}/slots/${slotId}`, method: 'DELETE'
    },
      );
    }
  /**
 * Get a Ministry's MinistryServingProfile, the standing rule declaring which EventTemplate TimeBlocks it always serves.
 * @summary Get a Ministry's serving profile
 */
const getMinistryServingProfile = (
    ministryId: string,
 ) => {
      return apiClient<GetMinistryServingProfile200>(
      {url: `/api/v1/admin/ministries/${ministryId}/serving-profile`, method: 'GET'
    },
      );
    }
  /**
 * Replace a Ministry's MinistryServingProfile entries, including which TimeBlocks it serves, its Shift split, and headcounts.
 * @summary Set a Ministry's serving profile
 */
const upsertMinistryServingProfile = (
    ministryId: string,
    upsertMinistryServingProfileBody: UpsertMinistryServingProfileBody,
 ) => {
      return apiClient<UpsertMinistryServingProfile200>(
      {url: `/api/v1/admin/ministries/${ministryId}/serving-profile`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: upsertMinistryServingProfileBody
    },
      );
    }
  /**
 * Set a Ministry's defaultDirection (all-in or all-out), deciding whether it starts opted into every TimeSlot of a cycle by default.
 * @summary Set a Ministry's default direction
 */
const setMinistryDefaultDirection = (
    ministryId: string,
    setMinistryDefaultDirectionBody: SetMinistryDefaultDirectionBody,
 ) => {
      return apiClient<SetMinistryDefaultDirection200>(
      {url: `/api/v1/admin/ministries/${ministryId}/default-direction`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: setMinistryDefaultDirectionBody
    },
      );
    }
  return {createPlanningCycle,listPlanningCycles,getPlanningCycle,lockPlanningCycle,reopenPlanningEvent,createEventTemplate,listEventTemplates,updateEventTemplate,deleteEventTemplate,applyPlanningTemplates,createPlanningEvent,updatePlanningEvent,cancelPlanningEvent,createPlanningEventSlot,updatePlanningEventSlot,deletePlanningEventSlot,getMinistryServingProfile,upsertMinistryServingProfile,setMinistryDefaultDirection}};
export type CreatePlanningCycleResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getPlanning>['createPlanningCycle']>>>
export type ListPlanningCyclesResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getPlanning>['listPlanningCycles']>>>
export type GetPlanningCycleResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getPlanning>['getPlanningCycle']>>>
export type LockPlanningCycleResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getPlanning>['lockPlanningCycle']>>>
export type ReopenPlanningEventResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getPlanning>['reopenPlanningEvent']>>>
export type CreateEventTemplateResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getPlanning>['createEventTemplate']>>>
export type ListEventTemplatesResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getPlanning>['listEventTemplates']>>>
export type UpdateEventTemplateResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getPlanning>['updateEventTemplate']>>>
export type DeleteEventTemplateResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getPlanning>['deleteEventTemplate']>>>
export type ApplyPlanningTemplatesResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getPlanning>['applyPlanningTemplates']>>>
export type CreatePlanningEventResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getPlanning>['createPlanningEvent']>>>
export type UpdatePlanningEventResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getPlanning>['updatePlanningEvent']>>>
export type CancelPlanningEventResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getPlanning>['cancelPlanningEvent']>>>
export type CreatePlanningEventSlotResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getPlanning>['createPlanningEventSlot']>>>
export type UpdatePlanningEventSlotResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getPlanning>['updatePlanningEventSlot']>>>
export type DeletePlanningEventSlotResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getPlanning>['deletePlanningEventSlot']>>>
export type GetMinistryServingProfileResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getPlanning>['getMinistryServingProfile']>>>
export type UpsertMinistryServingProfileResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getPlanning>['upsertMinistryServingProfile']>>>
export type SetMinistryDefaultDirectionResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getPlanning>['setMinistryDefaultDirection']>>>
