/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Church API
 * OpenAPI spec version: 1.0.0
 */
import type {
  PreviewChurchInvitation200,
  RedeemChurchInvitation200,
  RedeemChurchInvitationBody,
  RequestChurchInvitationVerificationCode200
} from './churchAPI.schemas';

import { apiClient } from '../../utils/api-client';




  export const getRedemption = () => {
const previewChurchInvitation = (
    invitationId: string,
 ) => {
      return apiClient<PreviewChurchInvitation200>(
      {url: `/api/v1/redemption/church/${invitationId}`, method: 'GET'
    },
      );
    }
  const requestChurchInvitationVerificationCode = (
    invitationId: string,
 ) => {
      return apiClient<RequestChurchInvitationVerificationCode200>(
      {url: `/api/v1/redemption/church/${invitationId}/code`, method: 'POST'
    },
      );
    }
  const redeemChurchInvitation = (
    invitationId: string,
    redeemChurchInvitationBody: RedeemChurchInvitationBody,
 ) => {
      return apiClient<RedeemChurchInvitation200>(
      {url: `/api/v1/redemption/church/${invitationId}/redeem`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: redeemChurchInvitationBody
    },
      );
    }
  return {previewChurchInvitation,requestChurchInvitationVerificationCode,redeemChurchInvitation}};
export type PreviewChurchInvitationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRedemption>['previewChurchInvitation']>>>
export type RequestChurchInvitationVerificationCodeResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRedemption>['requestChurchInvitationVerificationCode']>>>
export type RedeemChurchInvitationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRedemption>['redeemChurchInvitation']>>>
