/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Church API
 * OpenAPI spec version: 1.0.0
 */
import type {
  CreateParticipationAssignment201,
  CreateParticipationAssignmentBody,
  DeleteParticipationAssignment204,
  DeleteParticipationAssignmentParams,
  GetCycleAuditLog200,
  GetCycleAuditLogParams,
  GetCycleBuilderData200,
  GetCycleBuilderDataParams,
  GetParticipationCompletion200,
  ListEligibleVolunteers200,
  ListTeamRosterCycles200,
  ListTeamRosterCyclesParams,
  PublishCycle200,
  PublishCycleBody,
  PublishCycleParams,
  PublishParticipation204,
  PublishParticipationBody,
  ReassignParticipationAssignment200,
  ReassignParticipationAssignmentBody
} from './churchAPI.schemas';

import { apiClient } from '../../utils/api-client';




  export const getRostering = () => {
/**
 * List the locked PlanningCycles in a Ministry that a TeamLeader may open as a read-only roster.
 * @summary List a Team's readable roster cycles
 */
const listTeamRosterCycles = (
    teamId: string,
    params: ListTeamRosterCyclesParams,
 ) => {
      return apiClient<ListTeamRosterCycles200>(
      {url: `/api/v1/rostering/teams/${teamId}/cycles-summary`, method: 'GET',
        params
    },
      );
    }
  /**
 * Get a Ministry's roster-building view of a PlanningCycle: its MinistryParticipations, Shifts, SlotRequirements, and Assignments.
 * @summary Get cycle builder data for a Ministry
 */
const getCycleBuilderData = (
    cycleId: string,
    params: GetCycleBuilderDataParams,
 ) => {
      return apiClient<GetCycleBuilderData200>(
      {url: `/api/v1/rostering/cycles/${cycleId}/builder`, method: 'GET',
        params
    },
      );
    }
  /**
 * List a Ministry's Assignment audit entries across an entire PlanningCycle.
 * @summary Get a Ministry's Assignment audit log for a cycle
 */
const getCycleAuditLog = (
    cycleId: string,
    params: GetCycleAuditLogParams,
 ) => {
      return apiClient<GetCycleAuditLog200>(
      {url: `/api/v1/rostering/cycles/${cycleId}/audit`, method: 'GET',
        params
    },
      );
    }
  /**
 * Publish every eligible MinistryParticipation in a PlanningCycle for a Ministry in one batch, making its rosters visible to Volunteers.
 * @summary Publish a Ministry's roster for a cycle
 */
const publishCycle = (
    cycleId: string,
    publishCycleBody: PublishCycleBody,
    params: PublishCycleParams,
 ) => {
      return apiClient<PublishCycle200>(
      {url: `/api/v1/rostering/cycles/${cycleId}/publish`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: publishCycleBody,
        params
    },
      );
    }
  /**
 * List the Volunteers eligible to be assigned to a Shift, for the roster builder.
 * @summary List eligible Volunteers for a Shift
 */
const listEligibleVolunteers = (
    shiftId: string,
 ) => {
      return apiClient<ListEligibleVolunteers200>(
      {url: `/api/v1/rostering/shifts/${shiftId}/eligible-volunteers`, method: 'GET'
    },
      );
    }
  /**
 * Assign a Volunteer to a Role (and optional Team) within a Shift, optionally overriding a detected conflict.
 * @summary Assign a Volunteer to a Shift
 */
const createParticipationAssignment = (
    shiftId: string,
    createParticipationAssignmentBody: CreateParticipationAssignmentBody,
 ) => {
      return apiClient<CreateParticipationAssignment201>(
      {url: `/api/v1/rostering/shifts/${shiftId}/assignments`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createParticipationAssignmentBody
    },
      );
    }
  /**
 * Remove a Volunteer Assignment from its Shift.
 * @summary Delete an Assignment
 */
const deleteParticipationAssignment = (
    assignmentId: string,
    params?: DeleteParticipationAssignmentParams,
 ) => {
      return apiClient<DeleteParticipationAssignment204>(
      {url: `/api/v1/rostering/assignments/${assignmentId}`, method: 'DELETE',
        params
    },
      );
    }
  /**
 * Replace the Volunteer on an existing Assignment, keeping its Shift and Role, and record the reason.
 * @summary Reassign an Assignment to another Volunteer
 */
const reassignParticipationAssignment = (
    assignmentId: string,
    reassignParticipationAssignmentBody: ReassignParticipationAssignmentBody,
 ) => {
      return apiClient<ReassignParticipationAssignment200>(
      {url: `/api/v1/rostering/assignments/${assignmentId}/reassign`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: reassignParticipationAssignmentBody
    },
      );
    }
  /**
 * Get how fully a MinistryParticipation is staffed against its SlotRequirements.
 * @summary Get a MinistryParticipation's staffing completion
 */
const getParticipationCompletion = (
    participationId: string,
 ) => {
      return apiClient<GetParticipationCompletion200>(
      {url: `/api/v1/rostering/participations/${participationId}/completion`, method: 'GET'
    },
      );
    }
  /**
 * Publish one Ministry's roster for an Event, making its slice of the schedule visible to its Volunteers.
 * @summary Publish a single MinistryParticipation
 */
const publishParticipation = (
    participationId: string,
    publishParticipationBody: PublishParticipationBody,
 ) => {
      return apiClient<PublishParticipation204>(
      {url: `/api/v1/rostering/participations/${participationId}/publish`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: publishParticipationBody
    },
      );
    }
  return {listTeamRosterCycles,getCycleBuilderData,getCycleAuditLog,publishCycle,listEligibleVolunteers,createParticipationAssignment,deleteParticipationAssignment,reassignParticipationAssignment,getParticipationCompletion,publishParticipation}};
export type ListTeamRosterCyclesResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRostering>['listTeamRosterCycles']>>>
export type GetCycleBuilderDataResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRostering>['getCycleBuilderData']>>>
export type GetCycleAuditLogResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRostering>['getCycleAuditLog']>>>
export type PublishCycleResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRostering>['publishCycle']>>>
export type ListEligibleVolunteersResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRostering>['listEligibleVolunteers']>>>
export type CreateParticipationAssignmentResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRostering>['createParticipationAssignment']>>>
export type DeleteParticipationAssignmentResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRostering>['deleteParticipationAssignment']>>>
export type ReassignParticipationAssignmentResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRostering>['reassignParticipationAssignment']>>>
export type GetParticipationCompletionResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRostering>['getParticipationCompletion']>>>
export type PublishParticipationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRostering>['publishParticipation']>>>
