/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Church API
 * OpenAPI spec version: 1.0.0
 */
import type {
  GetSchedulingCapability200
} from './churchAPI.schemas';

import { apiClient } from '../../utils/api-client';




  export const getSchedulingCapability = () => {
/**
 * Return whether the current caller may enter Scheduling in the Active Church. This is navigation data, not an authorization grant.
 * @summary Get Scheduling capability for the Active Church
 */
const getSchedulingCapability = (

 ) => {
      return apiClient<GetSchedulingCapability200>(
      {url: `/api/v1/scheduling/capability`, method: 'GET'
    },
      );
    }
  return {getSchedulingCapability}};
export type GetSchedulingCapabilityResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSchedulingCapability>['getSchedulingCapability']>>>
