/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Church API
 * OpenAPI spec version: 1.0.0
 */
import type {
  FireAvailability202,
  GetAvailabilityStatus200,
  GetCycleAvailabilityStatus200,
  GetCycleAvailabilityStatusParams,
  GetCycleParticipation200,
  GetCycleParticipationParams,
  ListMinistryCycleSummaries200,
  SetParticipationInclusionsBody,
  SplitParticipationShifts201,
  SplitParticipationShiftsBody,
  UpdateShift200,
  UpdateShiftBody,
  UpsertShiftRequirement200,
  UpsertShiftRequirementBody
} from './churchAPI.schemas';

import { apiClient } from '../../utils/api-client';




  export const getTailoring = () => {
/**
 * Get a Ministry's MinistryParticipation tailoring state across every Event in a PlanningCycle.
 * @summary Get a Ministry's tailoring view of a cycle
 */
const getCycleParticipation = (
    cycleId: string,
    params: GetCycleParticipationParams,
 ) => {
      return apiClient<GetCycleParticipation200>(
      {url: `/api/v1/tailoring/cycles/${cycleId}/participation`, method: 'GET',
        params
    },
      );
    }
  /**
 * List summaries of a Ministry's MinistryParticipation tailoring progress across its PlanningCycles.
 * @summary List a Ministry's cycle tailoring summaries
 */
const listMinistryCycleSummaries = (
    ministryId: string,
 ) => {
      return apiClient<ListMinistryCycleSummaries200>(
      {url: `/api/v1/tailoring/ministries/${ministryId}/cycles-summary`, method: 'GET'
    },
      );
    }
  /**
 * Replace the set of TimeSlots a Ministry is opted into for a MinistryParticipation.
 * @summary Set a MinistryParticipation's included TimeSlots
 */
const setParticipationInclusions = (
    participationId: string,
    setParticipationInclusionsBody: SetParticipationInclusionsBody,
 ) => {
      return apiClient<void>(
      {url: `/api/v1/tailoring/participations/${participationId}/inclusions`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: setParticipationInclusionsBody
    },
      );
    }
  /**
 * Split a MinistryParticipation's TimeSlot into Shifts, either into equal parts or by manually-set spans.
 * @summary Split a TimeSlot into Shifts
 */
const splitParticipationShifts = (
    participationId: string,
    timeSlotId: string,
    splitParticipationShiftsBody: SplitParticipationShiftsBody,
 ) => {
      return apiClient<SplitParticipationShifts201>(
      {url: `/api/v1/tailoring/participations/${participationId}/slots/${timeSlotId}/shifts`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: splitParticipationShiftsBody
    },
      );
    }
  /**
 * Update a Shift's bounds or label.
 * @summary Update a Shift
 */
const updateShift = (
    shiftId: string,
    updateShiftBody: UpdateShiftBody,
 ) => {
      return apiClient<UpdateShift200>(
      {url: `/api/v1/tailoring/shifts/${shiftId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateShiftBody
    },
      );
    }
  /**
 * Delete a Shift from its MinistryParticipation.
 * @summary Delete a Shift
 */
const deleteShift = (
    shiftId: string,
 ) => {
      return apiClient<void>(
      {url: `/api/v1/tailoring/shifts/${shiftId}`, method: 'DELETE'
    },
      );
    }
  /**
 * Set the SlotRequirement headcount for a Role (and optional Team) within a Shift.
 * @summary Set a Shift staffing requirement
 */
const upsertShiftRequirement = (
    shiftId: string,
    upsertShiftRequirementBody: UpsertShiftRequirementBody,
 ) => {
      return apiClient<UpsertShiftRequirement200>(
      {url: `/api/v1/tailoring/shifts/${shiftId}/requirements`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: upsertShiftRequirementBody
    },
      );
    }
  /**
 * Spawn AvailabilityChecks for a MinistryParticipation's Volunteers and move it into availability_fired.
 * @summary Fire availability for a MinistryParticipation
 */
const fireAvailability = (
    participationId: string,
 ) => {
      return apiClient<FireAvailability202>(
      {url: `/api/v1/tailoring/participations/${participationId}/fire-availability`, method: 'POST'
    },
      );
    }
  /**
 * List a Ministry's Volunteers' AvailabilityCheck states across a PlanningCycle.
 * @summary Get a Ministry's AvailabilityCheck status for a cycle
 */
const getCycleAvailabilityStatus = (
    cycleId: string,
    params: GetCycleAvailabilityStatusParams,
 ) => {
      return apiClient<GetCycleAvailabilityStatus200>(
      {url: `/api/v1/tailoring/cycles/${cycleId}/availability-status`, method: 'GET',
        params
    },
      );
    }
  /**
 * List the AvailabilityCheck states of a MinistryParticipation's Volunteers.
 * @summary Get a MinistryParticipation's AvailabilityCheck status
 */
const getAvailabilityStatus = (
    participationId: string,
 ) => {
      return apiClient<GetAvailabilityStatus200>(
      {url: `/api/v1/tailoring/participations/${participationId}/availability-status`, method: 'GET'
    },
      );
    }
  /**
 * Resend the availability reminder VolunteerNotification to a MinistryParticipation's unconfirmed Volunteers.
 * @summary Resend an availability reminder
 */
const resendAvailabilityReminder = (
    participationId: string,
 ) => {
      return apiClient<void>(
      {url: `/api/v1/tailoring/participations/${participationId}/resend-availability`, method: 'POST'
    },
      );
    }
  return {getCycleParticipation,listMinistryCycleSummaries,setParticipationInclusions,splitParticipationShifts,updateShift,deleteShift,upsertShiftRequirement,fireAvailability,getCycleAvailabilityStatus,getAvailabilityStatus,resendAvailabilityReminder}};
export type GetCycleParticipationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getTailoring>['getCycleParticipation']>>>
export type ListMinistryCycleSummariesResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getTailoring>['listMinistryCycleSummaries']>>>
export type SetParticipationInclusionsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getTailoring>['setParticipationInclusions']>>>
export type SplitParticipationShiftsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getTailoring>['splitParticipationShifts']>>>
export type UpdateShiftResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getTailoring>['updateShift']>>>
export type DeleteShiftResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getTailoring>['deleteShift']>>>
export type UpsertShiftRequirementResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getTailoring>['upsertShiftRequirement']>>>
export type FireAvailabilityResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getTailoring>['fireAvailability']>>>
export type GetCycleAvailabilityStatusResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getTailoring>['getCycleAvailabilityStatus']>>>
export type GetAvailabilityStatusResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getTailoring>['getAvailabilityStatus']>>>
export type ResendAvailabilityReminderResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getTailoring>['resendAvailabilityReminder']>>>
