/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Church API
 * OpenAPI spec version: 1.0.0
 */
import type {
  FireAvailability202,
  GetAvailabilityStatus200,
  GetCycleAvailabilityStatus200,
  GetCycleAvailabilityStatusParams,
  GetCycleParticipation200,
  GetCycleParticipationParams,
  ListMinistryCycleSummaries200,
  SetParticipationInclusionsBody,
  SplitParticipationShifts201,
  SplitParticipationShiftsBody,
  UpdateShift200,
  UpdateShiftBody,
  UpsertShiftRequirement200,
  UpsertShiftRequirementBody
} from './churchAPI.schemas';

import { apiClient } from '../../utils/api-client';




  export const getTailoring = () => {
const getCycleParticipation = (
    cycleId: string,
    params: GetCycleParticipationParams,
 ) => {
      return apiClient<GetCycleParticipation200>(
      {url: `/api/v1/tailoring/cycles/${cycleId}/participation`, method: 'GET',
        params
    },
      );
    }
  const listMinistryCycleSummaries = (
    ministryId: string,
 ) => {
      return apiClient<ListMinistryCycleSummaries200>(
      {url: `/api/v1/tailoring/ministries/${ministryId}/cycles-summary`, method: 'GET'
    },
      );
    }
  const setParticipationInclusions = (
    participationId: string,
    setParticipationInclusionsBody: SetParticipationInclusionsBody,
 ) => {
      return apiClient<void>(
      {url: `/api/v1/tailoring/participations/${participationId}/inclusions`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: setParticipationInclusionsBody
    },
      );
    }
  const splitParticipationShifts = (
    participationId: string,
    timeSlotId: string,
    splitParticipationShiftsBody: SplitParticipationShiftsBody,
 ) => {
      return apiClient<SplitParticipationShifts201>(
      {url: `/api/v1/tailoring/participations/${participationId}/slots/${timeSlotId}/shifts`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: splitParticipationShiftsBody
    },
      );
    }
  const updateShift = (
    shiftId: string,
    updateShiftBody: UpdateShiftBody,
 ) => {
      return apiClient<UpdateShift200>(
      {url: `/api/v1/tailoring/shifts/${shiftId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateShiftBody
    },
      );
    }
  const deleteShift = (
    shiftId: string,
 ) => {
      return apiClient<void>(
      {url: `/api/v1/tailoring/shifts/${shiftId}`, method: 'DELETE'
    },
      );
    }
  const upsertShiftRequirement = (
    shiftId: string,
    upsertShiftRequirementBody: UpsertShiftRequirementBody,
 ) => {
      return apiClient<UpsertShiftRequirement200>(
      {url: `/api/v1/tailoring/shifts/${shiftId}/requirements`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: upsertShiftRequirementBody
    },
      );
    }
  const fireAvailability = (
    participationId: string,
 ) => {
      return apiClient<FireAvailability202>(
      {url: `/api/v1/tailoring/participations/${participationId}/fire-availability`, method: 'POST'
    },
      );
    }
  const getCycleAvailabilityStatus = (
    cycleId: string,
    params: GetCycleAvailabilityStatusParams,
 ) => {
      return apiClient<GetCycleAvailabilityStatus200>(
      {url: `/api/v1/tailoring/cycles/${cycleId}/availability-status`, method: 'GET',
        params
    },
      );
    }
  const getAvailabilityStatus = (
    participationId: string,
 ) => {
      return apiClient<GetAvailabilityStatus200>(
      {url: `/api/v1/tailoring/participations/${participationId}/availability-status`, method: 'GET'
    },
      );
    }
  const resendAvailabilityReminder = (
    participationId: string,
 ) => {
      return apiClient<void>(
      {url: `/api/v1/tailoring/participations/${participationId}/resend-availability`, method: 'POST'
    },
      );
    }
  return {getCycleParticipation,listMinistryCycleSummaries,setParticipationInclusions,splitParticipationShifts,updateShift,deleteShift,upsertShiftRequirement,fireAvailability,getCycleAvailabilityStatus,getAvailabilityStatus,resendAvailabilityReminder}};
export type GetCycleParticipationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getTailoring>['getCycleParticipation']>>>
export type ListMinistryCycleSummariesResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getTailoring>['listMinistryCycleSummaries']>>>
export type SetParticipationInclusionsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getTailoring>['setParticipationInclusions']>>>
export type SplitParticipationShiftsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getTailoring>['splitParticipationShifts']>>>
export type UpdateShiftResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getTailoring>['updateShift']>>>
export type DeleteShiftResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getTailoring>['deleteShift']>>>
export type UpsertShiftRequirementResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getTailoring>['upsertShiftRequirement']>>>
export type FireAvailabilityResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getTailoring>['fireAvailability']>>>
export type GetCycleAvailabilityStatusResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getTailoring>['getCycleAvailabilityStatus']>>>
export type GetAvailabilityStatusResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getTailoring>['getAvailabilityStatus']>>>
export type ResendAvailabilityReminderResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getTailoring>['resendAvailabilityReminder']>>>
