/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Church API
 * OpenAPI spec version: 1.0.0
 */
import type {
  CreateSlot201,
  CreateSlotBody,
  GenerateSlots201,
  GenerateSlotsBody,
  UpdateSlot200,
  UpdateSlotBody,
  UpsertSlotRequirement200,
  UpsertSlotRequirementBody
} from './churchAPI.schemas';

import { apiClient } from '../../utils/api-client';




  export const getTimeSlots = () => {
/**
 * Create a TimeSlot within an Event.
 * @summary Create a TimeSlot on an Event
 */
const createSlot = (
    eventId: string,
    createSlotBody: CreateSlotBody,
 ) => {
      return apiClient<CreateSlot201>(
      {url: `/api/v1/events/${eventId}/slots`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createSlotBody
    },
      );
    }
  /**
 * Update a TimeSlot's bounds or label.
 * @summary Update a TimeSlot
 */
const updateSlot = (
    eventId: string,
    slotId: string,
    updateSlotBody: UpdateSlotBody,
 ) => {
      return apiClient<UpdateSlot200>(
      {url: `/api/v1/events/${eventId}/slots/${slotId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateSlotBody
    },
      );
    }
  /**
 * Delete a TimeSlot from an Event.
 * @summary Delete a TimeSlot
 */
const deleteSlot = (
    eventId: string,
    slotId: string,
 ) => {
      return apiClient<void>(
      {url: `/api/v1/events/${eventId}/slots/${slotId}`, method: 'DELETE'
    },
      );
    }
  /**
 * Generate TimeSlots for an Event, either as an equal split or from a set of manually labelled TimeSlots with their own requirements.
 * @summary Generate TimeSlots for an Event
 */
const generateSlots = (
    eventId: string,
    generateSlotsBody: GenerateSlotsBody,
 ) => {
      return apiClient<GenerateSlots201>(
      {url: `/api/v1/events/${eventId}/slots/generate`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: generateSlotsBody
    },
      );
    }
  /**
 * Set the staffing headcount for a Role (and optional Team) within a TimeSlot.
 * @summary Set a TimeSlot staffing requirement
 */
const upsertSlotRequirement = (
    eventId: string,
    slotId: string,
    upsertSlotRequirementBody: UpsertSlotRequirementBody,
 ) => {
      return apiClient<UpsertSlotRequirement200>(
      {url: `/api/v1/events/${eventId}/slots/${slotId}/requirements`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: upsertSlotRequirementBody
    },
      );
    }
  return {createSlot,updateSlot,deleteSlot,generateSlots,upsertSlotRequirement}};
export type CreateSlotResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getTimeSlots>['createSlot']>>>
export type UpdateSlotResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getTimeSlots>['updateSlot']>>>
export type DeleteSlotResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getTimeSlots>['deleteSlot']>>>
export type GenerateSlotsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getTimeSlots>['generateSlots']>>>
export type UpsertSlotRequirementResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getTimeSlots>['upsertSlotRequirement']>>>
