/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Church API
 * OpenAPI spec version: 1.0.0
 */
import type {
  CancelOwnAssignment204,
  GetAvailabilityCheck200,
  GetMinistrySchedule200,
  GetMyAssignments200,
  GetNotifications200,
  GetNotificationsParams,
  GetPublishedVolunteerSchedule200,
  GetVolunteerDashboard200,
  ListAvailabilityChecks200,
  MarkNotificationRead200,
  RespondToAssignment200,
  RespondToAssignmentBody,
  SetUnavailabilityMarks200,
  SetUnavailabilityMarksBody
} from './churchAPI.schemas';

import { apiClient } from '../../utils/api-client';




  export const getVolunteer = () => {
/**
 * Get the current Volunteer's dashboard summary for the Active Church.
 * @summary Get the caller's Volunteer dashboard
 */
const getVolunteerDashboard = (

 ) => {
      return apiClient<GetVolunteerDashboard200>(
      {url: `/api/v1/volunteer/dashboard`, method: 'GET'
    },
      );
    }
  /**
 * List the current Volunteer's upcoming Assignments.
 * @summary Get the caller's upcoming Assignments
 */
const getMyAssignments = (

 ) => {
      return apiClient<GetMyAssignments200>(
      {url: `/api/v1/volunteer/assignments`, method: 'GET'
    },
      );
    }
  /**
 * Get the current Volunteer's published schedule within one Ministry.
 * @summary Get the caller's published Ministry schedule
 */
const getMinistrySchedule = (
    ministryId: string,
 ) => {
      return apiClient<GetMinistrySchedule200>(
      {url: `/api/v1/volunteer/ministries/${ministryId}/schedule`, method: 'GET'
    },
      );
    }
  /**
 * List the current Volunteer's AvailabilityChecks.
 * @summary List the caller's AvailabilityChecks
 */
const listAvailabilityChecks = (

 ) => {
      return apiClient<ListAvailabilityChecks200>(
      {url: `/api/v1/volunteer/availability-checks`, method: 'GET'
    },
      );
    }
  /**
 * Get the detail of a single AvailabilityCheck belonging to the current Volunteer.
 * @summary Get one of the caller's AvailabilityChecks
 */
const getAvailabilityCheck = (
    checkId: string,
 ) => {
      return apiClient<GetAvailabilityCheck200>(
      {url: `/api/v1/volunteer/availability-checks/${checkId}`, method: 'GET'
    },
      );
    }
  /**
 * Record the current Volunteer's unavailability marks — by Shift or by whole CalendarDay — against an AvailabilityCheck.
 * @summary Set unavailability marks on an AvailabilityCheck
 */
const setUnavailabilityMarks = (
    checkId: string,
    setUnavailabilityMarksBody: SetUnavailabilityMarksBody,
 ) => {
      return apiClient<SetUnavailabilityMarks200>(
      {url: `/api/v1/volunteer/availability-checks/${checkId}/marks`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: setUnavailabilityMarksBody
    },
      );
    }
  /**
 * Confirm the current Volunteer's AvailabilityCheck, recording confirmedAt even when no marks were left.
 * @summary Confirm an AvailabilityCheck
 */
const confirmAvailabilityCheck = (
    checkId: string,
 ) => {
      return apiClient<void>(
      {url: `/api/v1/volunteer/availability-checks/${checkId}/confirm`, method: 'POST'
    },
      );
    }
  /**
 * Record the current Volunteer's accept/decline response to one of their own Assignments.
 * @summary Respond to an Assignment
 */
const respondToAssignment = (
    assignmentId: string,
    respondToAssignmentBody: RespondToAssignmentBody,
 ) => {
      return apiClient<RespondToAssignment200>(
      {url: `/api/v1/volunteer/assignments/${assignmentId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: respondToAssignmentBody
    },
      );
    }
  /**
 * Cancel one of the current Volunteer's own Assignments.
 * @summary Cancel one of the caller's Assignments
 */
const cancelOwnAssignment = (
    assignmentId: string,
 ) => {
      return apiClient<CancelOwnAssignment204>(
      {url: `/api/v1/volunteer/assignments/${assignmentId}/cancel`, method: 'POST'
    },
      );
    }
  /**
 * List the current Volunteer's VolunteerNotifications, paginated by cursor.
 * @summary List the caller's VolunteerNotifications
 */
const getNotifications = (
    params?: GetNotificationsParams,
 ) => {
      return apiClient<GetNotifications200>(
      {url: `/api/v1/volunteer/notifications`, method: 'GET',
        params
    },
      );
    }
  /**
 * Mark one of the current Volunteer's VolunteerNotifications as read.
 * @summary Mark a VolunteerNotification read
 */
const markNotificationRead = (
    notificationId: string,
 ) => {
      return apiClient<MarkNotificationRead200>(
      {url: `/api/v1/volunteer/notifications/${notificationId}`, method: 'PATCH'
    },
      );
    }
  /**
 * Mark every one of the current Volunteer's VolunteerNotifications as read.
 * @summary Mark all VolunteerNotifications read
 */
const markAllNotificationsRead = (

 ) => {
      return apiClient<void>(
      {url: `/api/v1/volunteer/notifications/read-all`, method: 'POST'
    },
      );
    }
  /**
 * List the current Volunteer's Assignments from published MinistryParticipations.
 * @summary Get the caller's published schedule
 */
const getPublishedVolunteerSchedule = (

 ) => {
      return apiClient<GetPublishedVolunteerSchedule200>(
      {url: `/api/v1/volunteer/schedule`, method: 'GET'
    },
      );
    }
  return {getVolunteerDashboard,getMyAssignments,getMinistrySchedule,listAvailabilityChecks,getAvailabilityCheck,setUnavailabilityMarks,confirmAvailabilityCheck,respondToAssignment,cancelOwnAssignment,getNotifications,markNotificationRead,markAllNotificationsRead,getPublishedVolunteerSchedule}};
export type GetVolunteerDashboardResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getVolunteer>['getVolunteerDashboard']>>>
export type GetMyAssignmentsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getVolunteer>['getMyAssignments']>>>
export type GetMinistryScheduleResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getVolunteer>['getMinistrySchedule']>>>
export type ListAvailabilityChecksResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getVolunteer>['listAvailabilityChecks']>>>
export type GetAvailabilityCheckResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getVolunteer>['getAvailabilityCheck']>>>
export type SetUnavailabilityMarksResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getVolunteer>['setUnavailabilityMarks']>>>
export type ConfirmAvailabilityCheckResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getVolunteer>['confirmAvailabilityCheck']>>>
export type RespondToAssignmentResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getVolunteer>['respondToAssignment']>>>
export type CancelOwnAssignmentResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getVolunteer>['cancelOwnAssignment']>>>
export type GetNotificationsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getVolunteer>['getNotifications']>>>
export type MarkNotificationReadResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getVolunteer>['markNotificationRead']>>>
export type MarkAllNotificationsReadResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getVolunteer>['markAllNotificationsRead']>>>
export type GetPublishedVolunteerScheduleResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getVolunteer>['getPublishedVolunteerSchedule']>>>
