/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Church API
 * OpenAPI spec version: 1.0.0
 */
import type {
  CancelOwnAssignment204,
  GetAvailabilityCheck200,
  GetMinistrySchedule200,
  GetMyAssignments200,
  GetNotifications200,
  GetPublishedVolunteerSchedule200,
  GetVolunteerDashboard200,
  ListAvailabilityChecks200,
  MarkNotificationRead200,
  RespondToAssignment200,
  RespondToAssignmentBody,
  SetUnavailabilityMarks200,
  SetUnavailabilityMarksBody
} from './churchAPI.schemas';

import { apiClient } from '../../utils/api-client';




  export const getVolunteer = () => {
const getVolunteerDashboard = (

 ) => {
      return apiClient<GetVolunteerDashboard200>(
      {url: `/api/v1/volunteer/dashboard`, method: 'GET'
    },
      );
    }
  const getMyAssignments = (

 ) => {
      return apiClient<GetMyAssignments200>(
      {url: `/api/v1/volunteer/assignments`, method: 'GET'
    },
      );
    }
  const getMinistrySchedule = (
    ministryId: string,
 ) => {
      return apiClient<GetMinistrySchedule200>(
      {url: `/api/v1/volunteer/ministries/${ministryId}/schedule`, method: 'GET'
    },
      );
    }
  const listAvailabilityChecks = (

 ) => {
      return apiClient<ListAvailabilityChecks200>(
      {url: `/api/v1/volunteer/availability-checks`, method: 'GET'
    },
      );
    }
  const getAvailabilityCheck = (
    checkId: string,
 ) => {
      return apiClient<GetAvailabilityCheck200>(
      {url: `/api/v1/volunteer/availability-checks/${checkId}`, method: 'GET'
    },
      );
    }
  const setUnavailabilityMarks = (
    checkId: string,
    setUnavailabilityMarksBody: SetUnavailabilityMarksBody,
 ) => {
      return apiClient<SetUnavailabilityMarks200>(
      {url: `/api/v1/volunteer/availability-checks/${checkId}/marks`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: setUnavailabilityMarksBody
    },
      );
    }
  const confirmAvailabilityCheck = (
    checkId: string,
 ) => {
      return apiClient<void>(
      {url: `/api/v1/volunteer/availability-checks/${checkId}/confirm`, method: 'POST'
    },
      );
    }
  const respondToAssignment = (
    assignmentId: string,
    respondToAssignmentBody: RespondToAssignmentBody,
 ) => {
      return apiClient<RespondToAssignment200>(
      {url: `/api/v1/volunteer/assignments/${assignmentId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: respondToAssignmentBody
    },
      );
    }
  const cancelOwnAssignment = (
    assignmentId: string,
 ) => {
      return apiClient<CancelOwnAssignment204>(
      {url: `/api/v1/volunteer/assignments/${assignmentId}/cancel`, method: 'POST'
    },
      );
    }
  const getNotifications = (

 ) => {
      return apiClient<GetNotifications200>(
      {url: `/api/v1/volunteer/notifications`, method: 'GET'
    },
      );
    }
  const markNotificationRead = (
    notificationId: string,
 ) => {
      return apiClient<MarkNotificationRead200>(
      {url: `/api/v1/volunteer/notifications/${notificationId}`, method: 'PATCH'
    },
      );
    }
  const markAllNotificationsRead = (

 ) => {
      return apiClient<void>(
      {url: `/api/v1/volunteer/notifications/read-all`, method: 'POST'
    },
      );
    }
  const getPublishedVolunteerSchedule = (

 ) => {
      return apiClient<GetPublishedVolunteerSchedule200>(
      {url: `/api/v1/volunteer/schedule`, method: 'GET'
    },
      );
    }
  return {getVolunteerDashboard,getMyAssignments,getMinistrySchedule,listAvailabilityChecks,getAvailabilityCheck,setUnavailabilityMarks,confirmAvailabilityCheck,respondToAssignment,cancelOwnAssignment,getNotifications,markNotificationRead,markAllNotificationsRead,getPublishedVolunteerSchedule}};
export type GetVolunteerDashboardResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getVolunteer>['getVolunteerDashboard']>>>
export type GetMyAssignmentsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getVolunteer>['getMyAssignments']>>>
export type GetMinistryScheduleResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getVolunteer>['getMinistrySchedule']>>>
export type ListAvailabilityChecksResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getVolunteer>['listAvailabilityChecks']>>>
export type GetAvailabilityCheckResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getVolunteer>['getAvailabilityCheck']>>>
export type SetUnavailabilityMarksResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getVolunteer>['setUnavailabilityMarks']>>>
export type ConfirmAvailabilityCheckResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getVolunteer>['confirmAvailabilityCheck']>>>
export type RespondToAssignmentResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getVolunteer>['respondToAssignment']>>>
export type CancelOwnAssignmentResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getVolunteer>['cancelOwnAssignment']>>>
export type GetNotificationsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getVolunteer>['getNotifications']>>>
export type MarkNotificationReadResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getVolunteer>['markNotificationRead']>>>
export type MarkAllNotificationsReadResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getVolunteer>['markAllNotificationsRead']>>>
export type GetPublishedVolunteerScheduleResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getVolunteer>['getPublishedVolunteerSchedule']>>>
