/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Church API
 * OpenAPI spec version: 1.0.0
 */
import type {
  GetMinistrySchedule200,
  GetMyAssignments200,
  GetMyAvailability200,
  GetNotifications200,
  GetVolunteerDashboard200,
  MarkNotificationRead200,
  RespondToAssignment200,
  RespondToAssignmentBody,
  UpsertAvailability200,
  UpsertAvailabilityBody
} from './churchAPI.schemas';

import { apiClient } from '../../utils/api-client';




  export const getVolunteer = () => {
const getVolunteerDashboard = (

 ) => {
      return apiClient<GetVolunteerDashboard200>(
      {url: `/api/v1/volunteer/dashboard`, method: 'GET'
    },
      );
    }
  const getMyAssignments = (

 ) => {
      return apiClient<GetMyAssignments200>(
      {url: `/api/v1/volunteer/assignments`, method: 'GET'
    },
      );
    }
  const getMinistrySchedule = (
    ministryId: string,
 ) => {
      return apiClient<GetMinistrySchedule200>(
      {url: `/api/v1/volunteer/ministries/${ministryId}/schedule`, method: 'GET'
    },
      );
    }
  const getMyAvailability = (

 ) => {
      return apiClient<GetMyAvailability200>(
      {url: `/api/v1/volunteer/availability`, method: 'GET'
    },
      );
    }
  const upsertAvailability = (
    upsertAvailabilityBody: UpsertAvailabilityBody,
 ) => {
      return apiClient<UpsertAvailability200>(
      {url: `/api/v1/volunteer/availability`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: upsertAvailabilityBody
    },
      );
    }
  const deleteAvailability = (
    availabilityId: string,
 ) => {
      return apiClient<void>(
      {url: `/api/v1/volunteer/availability/${availabilityId}`, method: 'DELETE'
    },
      );
    }
  const respondToAssignment = (
    assignmentId: string,
    respondToAssignmentBody: RespondToAssignmentBody,
 ) => {
      return apiClient<RespondToAssignment200>(
      {url: `/api/v1/volunteer/assignments/${assignmentId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: respondToAssignmentBody
    },
      );
    }
  const getNotifications = (

 ) => {
      return apiClient<GetNotifications200>(
      {url: `/api/v1/volunteer/notifications`, method: 'GET'
    },
      );
    }
  const markNotificationRead = (
    notificationId: string,
 ) => {
      return apiClient<MarkNotificationRead200>(
      {url: `/api/v1/volunteer/notifications/${notificationId}`, method: 'PATCH'
    },
      );
    }
  const markAllNotificationsRead = (

 ) => {
      return apiClient<void>(
      {url: `/api/v1/volunteer/notifications/read-all`, method: 'POST'
    },
      );
    }
  return {getVolunteerDashboard,getMyAssignments,getMinistrySchedule,getMyAvailability,upsertAvailability,deleteAvailability,respondToAssignment,getNotifications,markNotificationRead,markAllNotificationsRead}};
export type GetVolunteerDashboardResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getVolunteer>['getVolunteerDashboard']>>>
export type GetMyAssignmentsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getVolunteer>['getMyAssignments']>>>
export type GetMinistryScheduleResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getVolunteer>['getMinistrySchedule']>>>
export type GetMyAvailabilityResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getVolunteer>['getMyAvailability']>>>
export type UpsertAvailabilityResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getVolunteer>['upsertAvailability']>>>
export type DeleteAvailabilityResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getVolunteer>['deleteAvailability']>>>
export type RespondToAssignmentResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getVolunteer>['respondToAssignment']>>>
export type GetNotificationsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getVolunteer>['getNotifications']>>>
export type MarkNotificationReadResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getVolunteer>['markNotificationRead']>>>
export type MarkAllNotificationsReadResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getVolunteer>['markAllNotificationsRead']>>>
