/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodosRouteImport } from './routes/todos'
import { Route as SchedulingRouteImport } from './routes/scheduling'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AvailabilityRouteImport } from './routes/availability'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SchedulingIndexRouteImport } from './routes/scheduling/index'
import { Route as SchedulingTailoringRouteImport } from './routes/scheduling/tailoring'
import { Route as SchedulingPlanningRouteImport } from './routes/scheduling/planning'
import { Route as SchedulingEventsEventIdBuilderRouteImport } from './routes/scheduling/events/$eventId/builder'

const TodosRoute = TodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedulingRoute = SchedulingRouteImport.update({
  id: '/scheduling',
  path: '/scheduling',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AvailabilityRoute = AvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedulingIndexRoute = SchedulingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SchedulingRoute,
} as any)
const SchedulingTailoringRoute = SchedulingTailoringRouteImport.update({
  id: '/tailoring',
  path: '/tailoring',
  getParentRoute: () => SchedulingRoute,
} as any)
const SchedulingPlanningRoute = SchedulingPlanningRouteImport.update({
  id: '/planning',
  path: '/planning',
  getParentRoute: () => SchedulingRoute,
} as any)
const SchedulingEventsEventIdBuilderRoute =
  SchedulingEventsEventIdBuilderRouteImport.update({
    id: '/events/$eventId/builder',
    path: '/events/$eventId/builder',
    getParentRoute: () => SchedulingRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/availability': typeof AvailabilityRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/scheduling': typeof SchedulingRouteWithChildren
  '/todos': typeof TodosRoute
  '/scheduling/planning': typeof SchedulingPlanningRoute
  '/scheduling/tailoring': typeof SchedulingTailoringRoute
  '/scheduling/': typeof SchedulingIndexRoute
  '/scheduling/events/$eventId/builder': typeof SchedulingEventsEventIdBuilderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/availability': typeof AvailabilityRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/todos': typeof TodosRoute
  '/scheduling/planning': typeof SchedulingPlanningRoute
  '/scheduling/tailoring': typeof SchedulingTailoringRoute
  '/scheduling': typeof SchedulingIndexRoute
  '/scheduling/events/$eventId/builder': typeof SchedulingEventsEventIdBuilderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/availability': typeof AvailabilityRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/scheduling': typeof SchedulingRouteWithChildren
  '/todos': typeof TodosRoute
  '/scheduling/planning': typeof SchedulingPlanningRoute
  '/scheduling/tailoring': typeof SchedulingTailoringRoute
  '/scheduling/': typeof SchedulingIndexRoute
  '/scheduling/events/$eventId/builder': typeof SchedulingEventsEventIdBuilderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/availability'
    | '/dashboard'
    | '/login'
    | '/scheduling'
    | '/todos'
    | '/scheduling/planning'
    | '/scheduling/tailoring'
    | '/scheduling/'
    | '/scheduling/events/$eventId/builder'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/availability'
    | '/dashboard'
    | '/login'
    | '/todos'
    | '/scheduling/planning'
    | '/scheduling/tailoring'
    | '/scheduling'
    | '/scheduling/events/$eventId/builder'
  id:
    | '__root__'
    | '/'
    | '/availability'
    | '/dashboard'
    | '/login'
    | '/scheduling'
    | '/todos'
    | '/scheduling/planning'
    | '/scheduling/tailoring'
    | '/scheduling/'
    | '/scheduling/events/$eventId/builder'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AvailabilityRoute: typeof AvailabilityRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  SchedulingRoute: typeof SchedulingRouteWithChildren
  TodosRoute: typeof TodosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/todos': {
      id: '/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof TodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scheduling': {
      id: '/scheduling'
      path: '/scheduling'
      fullPath: '/scheduling'
      preLoaderRoute: typeof SchedulingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/availability': {
      id: '/availability'
      path: '/availability'
      fullPath: '/availability'
      preLoaderRoute: typeof AvailabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scheduling/': {
      id: '/scheduling/'
      path: '/'
      fullPath: '/scheduling/'
      preLoaderRoute: typeof SchedulingIndexRouteImport
      parentRoute: typeof SchedulingRoute
    }
    '/scheduling/tailoring': {
      id: '/scheduling/tailoring'
      path: '/tailoring'
      fullPath: '/scheduling/tailoring'
      preLoaderRoute: typeof SchedulingTailoringRouteImport
      parentRoute: typeof SchedulingRoute
    }
    '/scheduling/planning': {
      id: '/scheduling/planning'
      path: '/planning'
      fullPath: '/scheduling/planning'
      preLoaderRoute: typeof SchedulingPlanningRouteImport
      parentRoute: typeof SchedulingRoute
    }
    '/scheduling/events/$eventId/builder': {
      id: '/scheduling/events/$eventId/builder'
      path: '/events/$eventId/builder'
      fullPath: '/scheduling/events/$eventId/builder'
      preLoaderRoute: typeof SchedulingEventsEventIdBuilderRouteImport
      parentRoute: typeof SchedulingRoute
    }
  }
}

interface SchedulingRouteChildren {
  SchedulingPlanningRoute: typeof SchedulingPlanningRoute
  SchedulingTailoringRoute: typeof SchedulingTailoringRoute
  SchedulingIndexRoute: typeof SchedulingIndexRoute
  SchedulingEventsEventIdBuilderRoute: typeof SchedulingEventsEventIdBuilderRoute
}

const SchedulingRouteChildren: SchedulingRouteChildren = {
  SchedulingPlanningRoute: SchedulingPlanningRoute,
  SchedulingTailoringRoute: SchedulingTailoringRoute,
  SchedulingIndexRoute: SchedulingIndexRoute,
  SchedulingEventsEventIdBuilderRoute: SchedulingEventsEventIdBuilderRoute,
}

const SchedulingRouteWithChildren = SchedulingRoute._addFileChildren(
  SchedulingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AvailabilityRoute: AvailabilityRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  SchedulingRoute: SchedulingRouteWithChildren,
  TodosRoute: TodosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
