/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SchedulingRouteImport } from './routes/scheduling'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AvailabilityRouteImport } from './routes/availability'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SchedulingIndexRouteImport } from './routes/scheduling/index'
import { Route as VolunteerAvailabilityRouteImport } from './routes/volunteer/availability'
import { Route as SchedulingTailoringRouteImport } from './routes/scheduling/tailoring'
import { Route as SchedulingPlanningCyclesRouteImport } from './routes/scheduling/planning-cycles'
import { Route as SchedulingTailoringIndexRouteImport } from './routes/scheduling/tailoring/index'
import { Route as SchedulingPlanningCyclesIndexRouteImport } from './routes/scheduling/planning-cycles/index'
import { Route as SchedulingTailoringMinistryIdRouteImport } from './routes/scheduling/tailoring/$ministryId'
import { Route as SchedulingRosteringPrototypeDateCardIconsRouteImport } from './routes/scheduling/rostering/prototype-date-card-icons'
import { Route as SchedulingRosteringPrototypeRouteImport } from './routes/scheduling/rostering/prototype'
import { Route as SchedulingPlanningCyclesTemplatesRouteImport } from './routes/scheduling/planning-cycles/templates'
import { Route as SchedulingPlanningCyclesNewRouteImport } from './routes/scheduling/planning-cycles/new'
import { Route as SchedulingPlanningCyclesCycleIdRouteImport } from './routes/scheduling/planning-cycles/$cycleId'
import { Route as SchedulingTailoringMinistryIdIndexRouteImport } from './routes/scheduling/tailoring/$ministryId/index'
import { Route as SchedulingTailoringMinistryIdCycleIdRouteImport } from './routes/scheduling/tailoring/$ministryId/$cycleId'
import { Route as SchedulingRosteringMinistryIdCycleIdRouteImport } from './routes/scheduling/rostering/$ministryId/$cycleId'

const SchedulingRoute = SchedulingRouteImport.update({
  id: '/scheduling',
  path: '/scheduling',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AvailabilityRoute = AvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedulingIndexRoute = SchedulingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SchedulingRoute,
} as any)
const VolunteerAvailabilityRoute = VolunteerAvailabilityRouteImport.update({
  id: '/volunteer/availability',
  path: '/volunteer/availability',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedulingTailoringRoute = SchedulingTailoringRouteImport.update({
  id: '/tailoring',
  path: '/tailoring',
  getParentRoute: () => SchedulingRoute,
} as any)
const SchedulingPlanningCyclesRoute =
  SchedulingPlanningCyclesRouteImport.update({
    id: '/planning-cycles',
    path: '/planning-cycles',
    getParentRoute: () => SchedulingRoute,
  } as any)
const SchedulingTailoringIndexRoute =
  SchedulingTailoringIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SchedulingTailoringRoute,
  } as any)
const SchedulingPlanningCyclesIndexRoute =
  SchedulingPlanningCyclesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SchedulingPlanningCyclesRoute,
  } as any)
const SchedulingTailoringMinistryIdRoute =
  SchedulingTailoringMinistryIdRouteImport.update({
    id: '/$ministryId',
    path: '/$ministryId',
    getParentRoute: () => SchedulingTailoringRoute,
  } as any)
const SchedulingRosteringPrototypeDateCardIconsRoute =
  SchedulingRosteringPrototypeDateCardIconsRouteImport.update({
    id: '/rostering/prototype-date-card-icons',
    path: '/rostering/prototype-date-card-icons',
    getParentRoute: () => SchedulingRoute,
  } as any)
const SchedulingRosteringPrototypeRoute =
  SchedulingRosteringPrototypeRouteImport.update({
    id: '/rostering/prototype',
    path: '/rostering/prototype',
    getParentRoute: () => SchedulingRoute,
  } as any)
const SchedulingPlanningCyclesTemplatesRoute =
  SchedulingPlanningCyclesTemplatesRouteImport.update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => SchedulingPlanningCyclesRoute,
  } as any)
const SchedulingPlanningCyclesNewRoute =
  SchedulingPlanningCyclesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => SchedulingPlanningCyclesRoute,
  } as any)
const SchedulingPlanningCyclesCycleIdRoute =
  SchedulingPlanningCyclesCycleIdRouteImport.update({
    id: '/$cycleId',
    path: '/$cycleId',
    getParentRoute: () => SchedulingPlanningCyclesRoute,
  } as any)
const SchedulingTailoringMinistryIdIndexRoute =
  SchedulingTailoringMinistryIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SchedulingTailoringMinistryIdRoute,
  } as any)
const SchedulingTailoringMinistryIdCycleIdRoute =
  SchedulingTailoringMinistryIdCycleIdRouteImport.update({
    id: '/$cycleId',
    path: '/$cycleId',
    getParentRoute: () => SchedulingTailoringMinistryIdRoute,
  } as any)
const SchedulingRosteringMinistryIdCycleIdRoute =
  SchedulingRosteringMinistryIdCycleIdRouteImport.update({
    id: '/rostering/$ministryId/$cycleId',
    path: '/rostering/$ministryId/$cycleId',
    getParentRoute: () => SchedulingRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/availability': typeof AvailabilityRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/scheduling': typeof SchedulingRouteWithChildren
  '/scheduling/planning-cycles': typeof SchedulingPlanningCyclesRouteWithChildren
  '/scheduling/tailoring': typeof SchedulingTailoringRouteWithChildren
  '/volunteer/availability': typeof VolunteerAvailabilityRoute
  '/scheduling/': typeof SchedulingIndexRoute
  '/scheduling/planning-cycles/$cycleId': typeof SchedulingPlanningCyclesCycleIdRoute
  '/scheduling/planning-cycles/new': typeof SchedulingPlanningCyclesNewRoute
  '/scheduling/planning-cycles/templates': typeof SchedulingPlanningCyclesTemplatesRoute
  '/scheduling/rostering/prototype': typeof SchedulingRosteringPrototypeRoute
  '/scheduling/rostering/prototype-date-card-icons': typeof SchedulingRosteringPrototypeDateCardIconsRoute
  '/scheduling/tailoring/$ministryId': typeof SchedulingTailoringMinistryIdRouteWithChildren
  '/scheduling/planning-cycles/': typeof SchedulingPlanningCyclesIndexRoute
  '/scheduling/tailoring/': typeof SchedulingTailoringIndexRoute
  '/scheduling/rostering/$ministryId/$cycleId': typeof SchedulingRosteringMinistryIdCycleIdRoute
  '/scheduling/tailoring/$ministryId/$cycleId': typeof SchedulingTailoringMinistryIdCycleIdRoute
  '/scheduling/tailoring/$ministryId/': typeof SchedulingTailoringMinistryIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/availability': typeof AvailabilityRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/volunteer/availability': typeof VolunteerAvailabilityRoute
  '/scheduling': typeof SchedulingIndexRoute
  '/scheduling/planning-cycles/$cycleId': typeof SchedulingPlanningCyclesCycleIdRoute
  '/scheduling/planning-cycles/new': typeof SchedulingPlanningCyclesNewRoute
  '/scheduling/planning-cycles/templates': typeof SchedulingPlanningCyclesTemplatesRoute
  '/scheduling/rostering/prototype': typeof SchedulingRosteringPrototypeRoute
  '/scheduling/rostering/prototype-date-card-icons': typeof SchedulingRosteringPrototypeDateCardIconsRoute
  '/scheduling/planning-cycles': typeof SchedulingPlanningCyclesIndexRoute
  '/scheduling/tailoring': typeof SchedulingTailoringIndexRoute
  '/scheduling/rostering/$ministryId/$cycleId': typeof SchedulingRosteringMinistryIdCycleIdRoute
  '/scheduling/tailoring/$ministryId/$cycleId': typeof SchedulingTailoringMinistryIdCycleIdRoute
  '/scheduling/tailoring/$ministryId': typeof SchedulingTailoringMinistryIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/availability': typeof AvailabilityRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/scheduling': typeof SchedulingRouteWithChildren
  '/scheduling/planning-cycles': typeof SchedulingPlanningCyclesRouteWithChildren
  '/scheduling/tailoring': typeof SchedulingTailoringRouteWithChildren
  '/volunteer/availability': typeof VolunteerAvailabilityRoute
  '/scheduling/': typeof SchedulingIndexRoute
  '/scheduling/planning-cycles/$cycleId': typeof SchedulingPlanningCyclesCycleIdRoute
  '/scheduling/planning-cycles/new': typeof SchedulingPlanningCyclesNewRoute
  '/scheduling/planning-cycles/templates': typeof SchedulingPlanningCyclesTemplatesRoute
  '/scheduling/rostering/prototype': typeof SchedulingRosteringPrototypeRoute
  '/scheduling/rostering/prototype-date-card-icons': typeof SchedulingRosteringPrototypeDateCardIconsRoute
  '/scheduling/tailoring/$ministryId': typeof SchedulingTailoringMinistryIdRouteWithChildren
  '/scheduling/planning-cycles/': typeof SchedulingPlanningCyclesIndexRoute
  '/scheduling/tailoring/': typeof SchedulingTailoringIndexRoute
  '/scheduling/rostering/$ministryId/$cycleId': typeof SchedulingRosteringMinistryIdCycleIdRoute
  '/scheduling/tailoring/$ministryId/$cycleId': typeof SchedulingTailoringMinistryIdCycleIdRoute
  '/scheduling/tailoring/$ministryId/': typeof SchedulingTailoringMinistryIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/availability'
    | '/dashboard'
    | '/login'
    | '/notifications'
    | '/scheduling'
    | '/scheduling/planning-cycles'
    | '/scheduling/tailoring'
    | '/volunteer/availability'
    | '/scheduling/'
    | '/scheduling/planning-cycles/$cycleId'
    | '/scheduling/planning-cycles/new'
    | '/scheduling/planning-cycles/templates'
    | '/scheduling/rostering/prototype'
    | '/scheduling/rostering/prototype-date-card-icons'
    | '/scheduling/tailoring/$ministryId'
    | '/scheduling/planning-cycles/'
    | '/scheduling/tailoring/'
    | '/scheduling/rostering/$ministryId/$cycleId'
    | '/scheduling/tailoring/$ministryId/$cycleId'
    | '/scheduling/tailoring/$ministryId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/availability'
    | '/dashboard'
    | '/login'
    | '/notifications'
    | '/volunteer/availability'
    | '/scheduling'
    | '/scheduling/planning-cycles/$cycleId'
    | '/scheduling/planning-cycles/new'
    | '/scheduling/planning-cycles/templates'
    | '/scheduling/rostering/prototype'
    | '/scheduling/rostering/prototype-date-card-icons'
    | '/scheduling/planning-cycles'
    | '/scheduling/tailoring'
    | '/scheduling/rostering/$ministryId/$cycleId'
    | '/scheduling/tailoring/$ministryId/$cycleId'
    | '/scheduling/tailoring/$ministryId'
  id:
    | '__root__'
    | '/'
    | '/availability'
    | '/dashboard'
    | '/login'
    | '/notifications'
    | '/scheduling'
    | '/scheduling/planning-cycles'
    | '/scheduling/tailoring'
    | '/volunteer/availability'
    | '/scheduling/'
    | '/scheduling/planning-cycles/$cycleId'
    | '/scheduling/planning-cycles/new'
    | '/scheduling/planning-cycles/templates'
    | '/scheduling/rostering/prototype'
    | '/scheduling/rostering/prototype-date-card-icons'
    | '/scheduling/tailoring/$ministryId'
    | '/scheduling/planning-cycles/'
    | '/scheduling/tailoring/'
    | '/scheduling/rostering/$ministryId/$cycleId'
    | '/scheduling/tailoring/$ministryId/$cycleId'
    | '/scheduling/tailoring/$ministryId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AvailabilityRoute: typeof AvailabilityRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  SchedulingRoute: typeof SchedulingRouteWithChildren
  VolunteerAvailabilityRoute: typeof VolunteerAvailabilityRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scheduling': {
      id: '/scheduling'
      path: '/scheduling'
      fullPath: '/scheduling'
      preLoaderRoute: typeof SchedulingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/availability': {
      id: '/availability'
      path: '/availability'
      fullPath: '/availability'
      preLoaderRoute: typeof AvailabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scheduling/': {
      id: '/scheduling/'
      path: '/'
      fullPath: '/scheduling/'
      preLoaderRoute: typeof SchedulingIndexRouteImport
      parentRoute: typeof SchedulingRoute
    }
    '/volunteer/availability': {
      id: '/volunteer/availability'
      path: '/volunteer/availability'
      fullPath: '/volunteer/availability'
      preLoaderRoute: typeof VolunteerAvailabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scheduling/tailoring': {
      id: '/scheduling/tailoring'
      path: '/tailoring'
      fullPath: '/scheduling/tailoring'
      preLoaderRoute: typeof SchedulingTailoringRouteImport
      parentRoute: typeof SchedulingRoute
    }
    '/scheduling/planning-cycles': {
      id: '/scheduling/planning-cycles'
      path: '/planning-cycles'
      fullPath: '/scheduling/planning-cycles'
      preLoaderRoute: typeof SchedulingPlanningCyclesRouteImport
      parentRoute: typeof SchedulingRoute
    }
    '/scheduling/tailoring/': {
      id: '/scheduling/tailoring/'
      path: '/'
      fullPath: '/scheduling/tailoring/'
      preLoaderRoute: typeof SchedulingTailoringIndexRouteImport
      parentRoute: typeof SchedulingTailoringRoute
    }
    '/scheduling/planning-cycles/': {
      id: '/scheduling/planning-cycles/'
      path: '/'
      fullPath: '/scheduling/planning-cycles/'
      preLoaderRoute: typeof SchedulingPlanningCyclesIndexRouteImport
      parentRoute: typeof SchedulingPlanningCyclesRoute
    }
    '/scheduling/tailoring/$ministryId': {
      id: '/scheduling/tailoring/$ministryId'
      path: '/$ministryId'
      fullPath: '/scheduling/tailoring/$ministryId'
      preLoaderRoute: typeof SchedulingTailoringMinistryIdRouteImport
      parentRoute: typeof SchedulingTailoringRoute
    }
    '/scheduling/rostering/prototype-date-card-icons': {
      id: '/scheduling/rostering/prototype-date-card-icons'
      path: '/rostering/prototype-date-card-icons'
      fullPath: '/scheduling/rostering/prototype-date-card-icons'
      preLoaderRoute: typeof SchedulingRosteringPrototypeDateCardIconsRouteImport
      parentRoute: typeof SchedulingRoute
    }
    '/scheduling/rostering/prototype': {
      id: '/scheduling/rostering/prototype'
      path: '/rostering/prototype'
      fullPath: '/scheduling/rostering/prototype'
      preLoaderRoute: typeof SchedulingRosteringPrototypeRouteImport
      parentRoute: typeof SchedulingRoute
    }
    '/scheduling/planning-cycles/templates': {
      id: '/scheduling/planning-cycles/templates'
      path: '/templates'
      fullPath: '/scheduling/planning-cycles/templates'
      preLoaderRoute: typeof SchedulingPlanningCyclesTemplatesRouteImport
      parentRoute: typeof SchedulingPlanningCyclesRoute
    }
    '/scheduling/planning-cycles/new': {
      id: '/scheduling/planning-cycles/new'
      path: '/new'
      fullPath: '/scheduling/planning-cycles/new'
      preLoaderRoute: typeof SchedulingPlanningCyclesNewRouteImport
      parentRoute: typeof SchedulingPlanningCyclesRoute
    }
    '/scheduling/planning-cycles/$cycleId': {
      id: '/scheduling/planning-cycles/$cycleId'
      path: '/$cycleId'
      fullPath: '/scheduling/planning-cycles/$cycleId'
      preLoaderRoute: typeof SchedulingPlanningCyclesCycleIdRouteImport
      parentRoute: typeof SchedulingPlanningCyclesRoute
    }
    '/scheduling/tailoring/$ministryId/': {
      id: '/scheduling/tailoring/$ministryId/'
      path: '/'
      fullPath: '/scheduling/tailoring/$ministryId/'
      preLoaderRoute: typeof SchedulingTailoringMinistryIdIndexRouteImport
      parentRoute: typeof SchedulingTailoringMinistryIdRoute
    }
    '/scheduling/tailoring/$ministryId/$cycleId': {
      id: '/scheduling/tailoring/$ministryId/$cycleId'
      path: '/$cycleId'
      fullPath: '/scheduling/tailoring/$ministryId/$cycleId'
      preLoaderRoute: typeof SchedulingTailoringMinistryIdCycleIdRouteImport
      parentRoute: typeof SchedulingTailoringMinistryIdRoute
    }
    '/scheduling/rostering/$ministryId/$cycleId': {
      id: '/scheduling/rostering/$ministryId/$cycleId'
      path: '/rostering/$ministryId/$cycleId'
      fullPath: '/scheduling/rostering/$ministryId/$cycleId'
      preLoaderRoute: typeof SchedulingRosteringMinistryIdCycleIdRouteImport
      parentRoute: typeof SchedulingRoute
    }
  }
}

interface SchedulingPlanningCyclesRouteChildren {
  SchedulingPlanningCyclesCycleIdRoute: typeof SchedulingPlanningCyclesCycleIdRoute
  SchedulingPlanningCyclesNewRoute: typeof SchedulingPlanningCyclesNewRoute
  SchedulingPlanningCyclesTemplatesRoute: typeof SchedulingPlanningCyclesTemplatesRoute
  SchedulingPlanningCyclesIndexRoute: typeof SchedulingPlanningCyclesIndexRoute
}

const SchedulingPlanningCyclesRouteChildren: SchedulingPlanningCyclesRouteChildren =
  {
    SchedulingPlanningCyclesCycleIdRoute: SchedulingPlanningCyclesCycleIdRoute,
    SchedulingPlanningCyclesNewRoute: SchedulingPlanningCyclesNewRoute,
    SchedulingPlanningCyclesTemplatesRoute:
      SchedulingPlanningCyclesTemplatesRoute,
    SchedulingPlanningCyclesIndexRoute: SchedulingPlanningCyclesIndexRoute,
  }

const SchedulingPlanningCyclesRouteWithChildren =
  SchedulingPlanningCyclesRoute._addFileChildren(
    SchedulingPlanningCyclesRouteChildren,
  )

interface SchedulingTailoringMinistryIdRouteChildren {
  SchedulingTailoringMinistryIdCycleIdRoute: typeof SchedulingTailoringMinistryIdCycleIdRoute
  SchedulingTailoringMinistryIdIndexRoute: typeof SchedulingTailoringMinistryIdIndexRoute
}

const SchedulingTailoringMinistryIdRouteChildren: SchedulingTailoringMinistryIdRouteChildren =
  {
    SchedulingTailoringMinistryIdCycleIdRoute:
      SchedulingTailoringMinistryIdCycleIdRoute,
    SchedulingTailoringMinistryIdIndexRoute:
      SchedulingTailoringMinistryIdIndexRoute,
  }

const SchedulingTailoringMinistryIdRouteWithChildren =
  SchedulingTailoringMinistryIdRoute._addFileChildren(
    SchedulingTailoringMinistryIdRouteChildren,
  )

interface SchedulingTailoringRouteChildren {
  SchedulingTailoringMinistryIdRoute: typeof SchedulingTailoringMinistryIdRouteWithChildren
  SchedulingTailoringIndexRoute: typeof SchedulingTailoringIndexRoute
}

const SchedulingTailoringRouteChildren: SchedulingTailoringRouteChildren = {
  SchedulingTailoringMinistryIdRoute:
    SchedulingTailoringMinistryIdRouteWithChildren,
  SchedulingTailoringIndexRoute: SchedulingTailoringIndexRoute,
}

const SchedulingTailoringRouteWithChildren =
  SchedulingTailoringRoute._addFileChildren(SchedulingTailoringRouteChildren)

interface SchedulingRouteChildren {
  SchedulingPlanningCyclesRoute: typeof SchedulingPlanningCyclesRouteWithChildren
  SchedulingTailoringRoute: typeof SchedulingTailoringRouteWithChildren
  SchedulingIndexRoute: typeof SchedulingIndexRoute
  SchedulingRosteringPrototypeRoute: typeof SchedulingRosteringPrototypeRoute
  SchedulingRosteringPrototypeDateCardIconsRoute: typeof SchedulingRosteringPrototypeDateCardIconsRoute
  SchedulingRosteringMinistryIdCycleIdRoute: typeof SchedulingRosteringMinistryIdCycleIdRoute
}

const SchedulingRouteChildren: SchedulingRouteChildren = {
  SchedulingPlanningCyclesRoute: SchedulingPlanningCyclesRouteWithChildren,
  SchedulingTailoringRoute: SchedulingTailoringRouteWithChildren,
  SchedulingIndexRoute: SchedulingIndexRoute,
  SchedulingRosteringPrototypeRoute: SchedulingRosteringPrototypeRoute,
  SchedulingRosteringPrototypeDateCardIconsRoute:
    SchedulingRosteringPrototypeDateCardIconsRoute,
  SchedulingRosteringMinistryIdCycleIdRoute:
    SchedulingRosteringMinistryIdCycleIdRoute,
}

const SchedulingRouteWithChildren = SchedulingRoute._addFileChildren(
  SchedulingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AvailabilityRoute: AvailabilityRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  SchedulingRoute: SchedulingRouteWithChildren,
  VolunteerAvailabilityRoute: VolunteerAvailabilityRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
