/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SchedulingRouteImport } from './routes/scheduling'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AvailabilityRouteImport } from './routes/availability'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SchedulingIndexRouteImport } from './routes/scheduling/index'
import { Route as VolunteerAvailabilityRouteImport } from './routes/volunteer/availability'
import { Route as SchedulingTailoringRouteImport } from './routes/scheduling/tailoring'
import { Route as SchedulingPlanningCyclesRouteImport } from './routes/scheduling/planning-cycles'
import { Route as SchedulingBuilderEventsRouteImport } from './routes/scheduling/builder-events'
import { Route as SchedulingPlanningCyclesIndexRouteImport } from './routes/scheduling/planning-cycles/index'
import { Route as SchedulingPlanningCyclesTemplatesRouteImport } from './routes/scheduling/planning-cycles/templates'
import { Route as SchedulingPlanningCyclesNewRouteImport } from './routes/scheduling/planning-cycles/new'
import { Route as SchedulingPlanningCyclesCycleIdRouteImport } from './routes/scheduling/planning-cycles/$cycleId'
import { Route as SchedulingEventsEventIdBuilderRouteImport } from './routes/scheduling/events/$eventId/builder'
import { Route as SchedulingRosteringCycleIdMinistryIdParticipationIdRouteImport } from './routes/scheduling/rostering/$cycleId/$ministryId/$participationId'

const SchedulingRoute = SchedulingRouteImport.update({
  id: '/scheduling',
  path: '/scheduling',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AvailabilityRoute = AvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedulingIndexRoute = SchedulingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SchedulingRoute,
} as any)
const VolunteerAvailabilityRoute = VolunteerAvailabilityRouteImport.update({
  id: '/volunteer/availability',
  path: '/volunteer/availability',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedulingTailoringRoute = SchedulingTailoringRouteImport.update({
  id: '/tailoring',
  path: '/tailoring',
  getParentRoute: () => SchedulingRoute,
} as any)
const SchedulingPlanningCyclesRoute =
  SchedulingPlanningCyclesRouteImport.update({
    id: '/planning-cycles',
    path: '/planning-cycles',
    getParentRoute: () => SchedulingRoute,
  } as any)
const SchedulingBuilderEventsRoute = SchedulingBuilderEventsRouteImport.update({
  id: '/builder-events',
  path: '/builder-events',
  getParentRoute: () => SchedulingRoute,
} as any)
const SchedulingPlanningCyclesIndexRoute =
  SchedulingPlanningCyclesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SchedulingPlanningCyclesRoute,
  } as any)
const SchedulingPlanningCyclesTemplatesRoute =
  SchedulingPlanningCyclesTemplatesRouteImport.update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => SchedulingPlanningCyclesRoute,
  } as any)
const SchedulingPlanningCyclesNewRoute =
  SchedulingPlanningCyclesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => SchedulingPlanningCyclesRoute,
  } as any)
const SchedulingPlanningCyclesCycleIdRoute =
  SchedulingPlanningCyclesCycleIdRouteImport.update({
    id: '/$cycleId',
    path: '/$cycleId',
    getParentRoute: () => SchedulingPlanningCyclesRoute,
  } as any)
const SchedulingEventsEventIdBuilderRoute =
  SchedulingEventsEventIdBuilderRouteImport.update({
    id: '/events/$eventId/builder',
    path: '/events/$eventId/builder',
    getParentRoute: () => SchedulingRoute,
  } as any)
const SchedulingRosteringCycleIdMinistryIdParticipationIdRoute =
  SchedulingRosteringCycleIdMinistryIdParticipationIdRouteImport.update({
    id: '/rostering/$cycleId/$ministryId/$participationId',
    path: '/rostering/$cycleId/$ministryId/$participationId',
    getParentRoute: () => SchedulingRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/availability': typeof AvailabilityRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/scheduling': typeof SchedulingRouteWithChildren
  '/scheduling/builder-events': typeof SchedulingBuilderEventsRoute
  '/scheduling/planning-cycles': typeof SchedulingPlanningCyclesRouteWithChildren
  '/scheduling/tailoring': typeof SchedulingTailoringRoute
  '/volunteer/availability': typeof VolunteerAvailabilityRoute
  '/scheduling/': typeof SchedulingIndexRoute
  '/scheduling/planning-cycles/$cycleId': typeof SchedulingPlanningCyclesCycleIdRoute
  '/scheduling/planning-cycles/new': typeof SchedulingPlanningCyclesNewRoute
  '/scheduling/planning-cycles/templates': typeof SchedulingPlanningCyclesTemplatesRoute
  '/scheduling/planning-cycles/': typeof SchedulingPlanningCyclesIndexRoute
  '/scheduling/events/$eventId/builder': typeof SchedulingEventsEventIdBuilderRoute
  '/scheduling/rostering/$cycleId/$ministryId/$participationId': typeof SchedulingRosteringCycleIdMinistryIdParticipationIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/availability': typeof AvailabilityRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/scheduling/builder-events': typeof SchedulingBuilderEventsRoute
  '/scheduling/tailoring': typeof SchedulingTailoringRoute
  '/volunteer/availability': typeof VolunteerAvailabilityRoute
  '/scheduling': typeof SchedulingIndexRoute
  '/scheduling/planning-cycles/$cycleId': typeof SchedulingPlanningCyclesCycleIdRoute
  '/scheduling/planning-cycles/new': typeof SchedulingPlanningCyclesNewRoute
  '/scheduling/planning-cycles/templates': typeof SchedulingPlanningCyclesTemplatesRoute
  '/scheduling/planning-cycles': typeof SchedulingPlanningCyclesIndexRoute
  '/scheduling/events/$eventId/builder': typeof SchedulingEventsEventIdBuilderRoute
  '/scheduling/rostering/$cycleId/$ministryId/$participationId': typeof SchedulingRosteringCycleIdMinistryIdParticipationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/availability': typeof AvailabilityRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/scheduling': typeof SchedulingRouteWithChildren
  '/scheduling/builder-events': typeof SchedulingBuilderEventsRoute
  '/scheduling/planning-cycles': typeof SchedulingPlanningCyclesRouteWithChildren
  '/scheduling/tailoring': typeof SchedulingTailoringRoute
  '/volunteer/availability': typeof VolunteerAvailabilityRoute
  '/scheduling/': typeof SchedulingIndexRoute
  '/scheduling/planning-cycles/$cycleId': typeof SchedulingPlanningCyclesCycleIdRoute
  '/scheduling/planning-cycles/new': typeof SchedulingPlanningCyclesNewRoute
  '/scheduling/planning-cycles/templates': typeof SchedulingPlanningCyclesTemplatesRoute
  '/scheduling/planning-cycles/': typeof SchedulingPlanningCyclesIndexRoute
  '/scheduling/events/$eventId/builder': typeof SchedulingEventsEventIdBuilderRoute
  '/scheduling/rostering/$cycleId/$ministryId/$participationId': typeof SchedulingRosteringCycleIdMinistryIdParticipationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/availability'
    | '/dashboard'
    | '/login'
    | '/notifications'
    | '/scheduling'
    | '/scheduling/builder-events'
    | '/scheduling/planning-cycles'
    | '/scheduling/tailoring'
    | '/volunteer/availability'
    | '/scheduling/'
    | '/scheduling/planning-cycles/$cycleId'
    | '/scheduling/planning-cycles/new'
    | '/scheduling/planning-cycles/templates'
    | '/scheduling/planning-cycles/'
    | '/scheduling/events/$eventId/builder'
    | '/scheduling/rostering/$cycleId/$ministryId/$participationId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/availability'
    | '/dashboard'
    | '/login'
    | '/notifications'
    | '/scheduling/builder-events'
    | '/scheduling/tailoring'
    | '/volunteer/availability'
    | '/scheduling'
    | '/scheduling/planning-cycles/$cycleId'
    | '/scheduling/planning-cycles/new'
    | '/scheduling/planning-cycles/templates'
    | '/scheduling/planning-cycles'
    | '/scheduling/events/$eventId/builder'
    | '/scheduling/rostering/$cycleId/$ministryId/$participationId'
  id:
    | '__root__'
    | '/'
    | '/availability'
    | '/dashboard'
    | '/login'
    | '/notifications'
    | '/scheduling'
    | '/scheduling/builder-events'
    | '/scheduling/planning-cycles'
    | '/scheduling/tailoring'
    | '/volunteer/availability'
    | '/scheduling/'
    | '/scheduling/planning-cycles/$cycleId'
    | '/scheduling/planning-cycles/new'
    | '/scheduling/planning-cycles/templates'
    | '/scheduling/planning-cycles/'
    | '/scheduling/events/$eventId/builder'
    | '/scheduling/rostering/$cycleId/$ministryId/$participationId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AvailabilityRoute: typeof AvailabilityRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  SchedulingRoute: typeof SchedulingRouteWithChildren
  VolunteerAvailabilityRoute: typeof VolunteerAvailabilityRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scheduling': {
      id: '/scheduling'
      path: '/scheduling'
      fullPath: '/scheduling'
      preLoaderRoute: typeof SchedulingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/availability': {
      id: '/availability'
      path: '/availability'
      fullPath: '/availability'
      preLoaderRoute: typeof AvailabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scheduling/': {
      id: '/scheduling/'
      path: '/'
      fullPath: '/scheduling/'
      preLoaderRoute: typeof SchedulingIndexRouteImport
      parentRoute: typeof SchedulingRoute
    }
    '/volunteer/availability': {
      id: '/volunteer/availability'
      path: '/volunteer/availability'
      fullPath: '/volunteer/availability'
      preLoaderRoute: typeof VolunteerAvailabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scheduling/tailoring': {
      id: '/scheduling/tailoring'
      path: '/tailoring'
      fullPath: '/scheduling/tailoring'
      preLoaderRoute: typeof SchedulingTailoringRouteImport
      parentRoute: typeof SchedulingRoute
    }
    '/scheduling/planning-cycles': {
      id: '/scheduling/planning-cycles'
      path: '/planning-cycles'
      fullPath: '/scheduling/planning-cycles'
      preLoaderRoute: typeof SchedulingPlanningCyclesRouteImport
      parentRoute: typeof SchedulingRoute
    }
    '/scheduling/builder-events': {
      id: '/scheduling/builder-events'
      path: '/builder-events'
      fullPath: '/scheduling/builder-events'
      preLoaderRoute: typeof SchedulingBuilderEventsRouteImport
      parentRoute: typeof SchedulingRoute
    }
    '/scheduling/planning-cycles/': {
      id: '/scheduling/planning-cycles/'
      path: '/'
      fullPath: '/scheduling/planning-cycles/'
      preLoaderRoute: typeof SchedulingPlanningCyclesIndexRouteImport
      parentRoute: typeof SchedulingPlanningCyclesRoute
    }
    '/scheduling/planning-cycles/templates': {
      id: '/scheduling/planning-cycles/templates'
      path: '/templates'
      fullPath: '/scheduling/planning-cycles/templates'
      preLoaderRoute: typeof SchedulingPlanningCyclesTemplatesRouteImport
      parentRoute: typeof SchedulingPlanningCyclesRoute
    }
    '/scheduling/planning-cycles/new': {
      id: '/scheduling/planning-cycles/new'
      path: '/new'
      fullPath: '/scheduling/planning-cycles/new'
      preLoaderRoute: typeof SchedulingPlanningCyclesNewRouteImport
      parentRoute: typeof SchedulingPlanningCyclesRoute
    }
    '/scheduling/planning-cycles/$cycleId': {
      id: '/scheduling/planning-cycles/$cycleId'
      path: '/$cycleId'
      fullPath: '/scheduling/planning-cycles/$cycleId'
      preLoaderRoute: typeof SchedulingPlanningCyclesCycleIdRouteImport
      parentRoute: typeof SchedulingPlanningCyclesRoute
    }
    '/scheduling/events/$eventId/builder': {
      id: '/scheduling/events/$eventId/builder'
      path: '/events/$eventId/builder'
      fullPath: '/scheduling/events/$eventId/builder'
      preLoaderRoute: typeof SchedulingEventsEventIdBuilderRouteImport
      parentRoute: typeof SchedulingRoute
    }
    '/scheduling/rostering/$cycleId/$ministryId/$participationId': {
      id: '/scheduling/rostering/$cycleId/$ministryId/$participationId'
      path: '/rostering/$cycleId/$ministryId/$participationId'
      fullPath: '/scheduling/rostering/$cycleId/$ministryId/$participationId'
      preLoaderRoute: typeof SchedulingRosteringCycleIdMinistryIdParticipationIdRouteImport
      parentRoute: typeof SchedulingRoute
    }
  }
}

interface SchedulingPlanningCyclesRouteChildren {
  SchedulingPlanningCyclesCycleIdRoute: typeof SchedulingPlanningCyclesCycleIdRoute
  SchedulingPlanningCyclesNewRoute: typeof SchedulingPlanningCyclesNewRoute
  SchedulingPlanningCyclesTemplatesRoute: typeof SchedulingPlanningCyclesTemplatesRoute
  SchedulingPlanningCyclesIndexRoute: typeof SchedulingPlanningCyclesIndexRoute
}

const SchedulingPlanningCyclesRouteChildren: SchedulingPlanningCyclesRouteChildren =
  {
    SchedulingPlanningCyclesCycleIdRoute: SchedulingPlanningCyclesCycleIdRoute,
    SchedulingPlanningCyclesNewRoute: SchedulingPlanningCyclesNewRoute,
    SchedulingPlanningCyclesTemplatesRoute:
      SchedulingPlanningCyclesTemplatesRoute,
    SchedulingPlanningCyclesIndexRoute: SchedulingPlanningCyclesIndexRoute,
  }

const SchedulingPlanningCyclesRouteWithChildren =
  SchedulingPlanningCyclesRoute._addFileChildren(
    SchedulingPlanningCyclesRouteChildren,
  )

interface SchedulingRouteChildren {
  SchedulingBuilderEventsRoute: typeof SchedulingBuilderEventsRoute
  SchedulingPlanningCyclesRoute: typeof SchedulingPlanningCyclesRouteWithChildren
  SchedulingTailoringRoute: typeof SchedulingTailoringRoute
  SchedulingIndexRoute: typeof SchedulingIndexRoute
  SchedulingEventsEventIdBuilderRoute: typeof SchedulingEventsEventIdBuilderRoute
  SchedulingRosteringCycleIdMinistryIdParticipationIdRoute: typeof SchedulingRosteringCycleIdMinistryIdParticipationIdRoute
}

const SchedulingRouteChildren: SchedulingRouteChildren = {
  SchedulingBuilderEventsRoute: SchedulingBuilderEventsRoute,
  SchedulingPlanningCyclesRoute: SchedulingPlanningCyclesRouteWithChildren,
  SchedulingTailoringRoute: SchedulingTailoringRoute,
  SchedulingIndexRoute: SchedulingIndexRoute,
  SchedulingEventsEventIdBuilderRoute: SchedulingEventsEventIdBuilderRoute,
  SchedulingRosteringCycleIdMinistryIdParticipationIdRoute:
    SchedulingRosteringCycleIdMinistryIdParticipationIdRoute,
}

const SchedulingRouteWithChildren = SchedulingRoute._addFileChildren(
  SchedulingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AvailabilityRoute: AvailabilityRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  SchedulingRoute: SchedulingRouteWithChildren,
  VolunteerAvailabilityRoute: VolunteerAvailabilityRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
