import { execFileSync, spawnSync } from 'node:child_process';
import {
  chmodSync,
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  realpathSync,
  rmSync,
  writeFileSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { afterEach, beforeEach, describe, expect, it } from 'bun:test';
import { renderDnsmasqConfig } from '../../worktree/dev-dns';

/**
 * Drives the real `dns:start`/`dns:stop` command from a linked worktree, with
 * `docker` and `tailscale` replaced on PATH by recorders, and checks the
 * rendered resolver config and the one Compose call it makes.
 */

const REPO_ROOT = resolve(import.meta.dir, '../../..');
const DEV_DNS_SCRIPT = resolve(REPO_ROOT, 'tooling/worktree/dev-dns.ts');
const TAILSCALE_ADDRESS = '100.64.0.7';

let sandbox: string;
let primary: string;
let feature: string;
let dockerLog: string;
let tailscaleLog: string;

interface GitInput {
  cwd: string;
  args: string[];
}

function git(input: GitInput): void {
  execFileSync('git', input.args, { cwd: input.cwd, stdio: 'ignore' });
}

interface StubInput {
  name: string;
  script: string;
}

function stub(input: StubInput): void {
  const path = join(sandbox, 'bin', input.name);
  writeFileSync(path, `#!/bin/sh\n${input.script}\n`);
  chmodSync(path, 0o755);
}

interface RunInput {
  command: string;
}

interface RunResult {
  status: number | null;
  output: string;
}

function run(input: RunInput): RunResult {
  const result = spawnSync('bun', [DEV_DNS_SCRIPT, input.command], {
    cwd: feature,
    encoding: 'utf8',
    env: {
      ...process.env,
      PATH: `${join(sandbox, 'bin')}:${process.env.PATH}`,
    },
  });
  return { status: result.status, output: result.stdout + result.stderr };
}

interface SharedValuesInput {
  content: string;
}

function writeSharedValues(input: SharedValuesInput): void {
  writeFileSync(join(primary, '.git', 'church-shared.env'), input.content);
}

function configPath(): string {
  return join(primary, '.git', 'church-dnsmasq.conf');
}

interface LogInput {
  path: string;
}

/** A recorder's last invocation; empty when it was never called. */
function readLog(input: LogInput): string {
  return existsSync(input.path) ? readFileSync(input.path, 'utf8').trim() : '';
}

beforeEach(() => {
  sandbox = realpathSync(mkdtempSync(join(tmpdir(), 'church-dev-dns-')));
  primary = join(sandbox, 'church');
  feature = join(sandbox, 'church.feature');
  dockerLog = join(sandbox, 'docker.log');
  tailscaleLog = join(sandbox, 'tailscale.log');

  mkdirSync(join(sandbox, 'bin'));
  stub({
    name: 'docker',
    script: `echo "$* address=$CHURCH_DEV_ADDRESS config=$CHURCH_DNS_CONFIG" > "${dockerLog}"`,
  });
  stub({
    name: 'tailscale',
    script: `echo "$*" > "${tailscaleLog}"\necho ${TAILSCALE_ADDRESS}`,
  });

  execFileSync('git', ['init', '-q', '-b', 'develop', primary]);
  git({
    cwd: primary,
    args: [
      '-c',
      'user.name=test',
      '-c',
      'user.email=test@example.com',
      'commit',
      '-q',
      '--allow-empty',
      '-m',
      'init',
    ],
  });
  git({
    cwd: primary,
    args: ['worktree', 'add', '-q', '-b', 'feature', feature],
  });
});

afterEach(() => {
  rmSync(sandbox, { recursive: true, force: true });
});

describe('renderDnsmasqConfig', () => {
  it('answers only the machine domain, with its address and no other record type', () => {
    expect(
      renderDnsmasqConfig({
        domain: 'laptop.dev.home.arpa',
        address: '192.168.0.42',
      }),
    ).toBe(
      [
        '# Generated by `bun run dns:start` (tooling/worktree/dev-dns.ts). Do not edit; rerun it.',
        'no-resolv',
        'no-hosts',
        'local=/laptop.dev.home.arpa/',
        'address=/laptop.dev.home.arpa/192.168.0.42',
        '',
      ].join('\n'),
    );
  });
});

describe('dns:start', () => {
  it("renders the resolver config and starts only the resolver from the primary checkout's Compose", () => {
    writeSharedValues({
      content:
        'CHURCH_DEV_DOMAIN="laptop.dev.home.arpa"\nCHURCH_DEV_ADDRESS=192.168.0.42\n',
    });

    const result = run({ command: 'start' });

    expect(result.status, result.output).toBe(0);
    expect(readFileSync(configPath(), 'utf8')).toContain(
      'address=/laptop.dev.home.arpa/192.168.0.42',
    );
    expect(readLog({ path: dockerLog })).toBe(
      `compose --file ${primary}/docker-compose.yml --profile dns up --detach --wait --force-recreate dns address=192.168.0.42 config=${configPath()}`,
    );
    expect(readLog({ path: tailscaleLog })).toBe('');
  });

  it("defaults the address to this machine's Tailscale IPv4", () => {
    writeSharedValues({ content: 'CHURCH_DEV_DOMAIN=homelab.dev.home.arpa\n' });

    const result = run({ command: 'start' });

    expect(result.status, result.output).toBe(0);
    expect(readLog({ path: tailscaleLog })).toBe('ip -4');
    expect(readFileSync(configPath(), 'utf8')).toContain(
      `address=/homelab.dev.home.arpa/${TAILSCALE_ADDRESS}`,
    );
    expect(readLog({ path: dockerLog })).toContain(
      `address=${TAILSCALE_ADDRESS}`,
    );
  });

  it('refuses to start without a machine domain, naming where to set it', () => {
    const result = run({ command: 'start' });

    expect(result.status).not.toBe(0);
    expect(result.output).toContain('CHURCH_DEV_DOMAIN');
    expect(result.output).toContain('church-shared.env');
    expect(readLog({ path: dockerLog })).toBe('');
  });

  it('refuses a malformed machine domain', () => {
    writeSharedValues({
      content: 'CHURCH_DEV_DOMAIN=Laptop\nCHURCH_DEV_ADDRESS=192.168.0.42\n',
    });

    const result = run({ command: 'start' });

    expect(result.status).not.toBe(0);
    expect(result.output).toContain('CHURCH_DEV_DOMAIN');
    expect(readLog({ path: dockerLog })).toBe('');
  });

  it('refuses an address that is not IPv4', () => {
    writeSharedValues({
      content: 'CHURCH_DEV_DOMAIN=lan\nCHURCH_DEV_ADDRESS=laptop.lan\n',
    });

    const result = run({ command: 'start' });

    expect(result.status).not.toBe(0);
    expect(result.output).toContain('CHURCH_DEV_ADDRESS');
    expect(readLog({ path: dockerLog })).toBe('');
  });

  it('asks for an explicit address when Tailscale reports none', () => {
    stub({ name: 'tailscale', script: 'echo "not running" >&2\nexit 1' });
    writeSharedValues({ content: 'CHURCH_DEV_DOMAIN=lan\n' });

    const result = run({ command: 'start' });

    expect(result.status).not.toBe(0);
    expect(result.output).toContain('CHURCH_DEV_ADDRESS');
    expect(result.output).not.toContain('    at ');
    expect(readLog({ path: dockerLog })).toBe('');
  });
});

describe('dns:stop', () => {
  it('stops only the resolver', () => {
    const result = run({ command: 'stop' });

    expect(result.status, result.output).toBe(0);
    expect(readLog({ path: dockerLog })).toStartWith(
      `compose --file ${primary}/docker-compose.yml --profile dns stop dns`,
    );
  });
});

describe('shared Compose', () => {
  interface ComposeService {
    profiles?: string[];
  }

  interface ComposeFile {
    services: Record<string, ComposeService>;
  }

  it('starts the resolver only under its opt-in profile, never with db:start', () => {
    const compose = Bun.YAML.parse(
      readFileSync(join(REPO_ROOT, 'docker-compose.yml'), 'utf8'),
    ) as ComposeFile;
    const defaultServices = Object.entries(compose.services)
      .filter(([, service]) => !service.profiles)
      .map(([name]) => name);

    expect(defaultServices).toEqual(['db']);
    expect(compose.services.dns?.profiles).toEqual(['dns']);
  });

  it('activates the resolver profile only from dns:start/dns:stop', () => {
    const activating = execFileSync(
      'git',
      [
        'grep',
        '--untracked',
        '-l',
        '-E',
        '-e',
        '--profile',
        '-e',
        'COMPOSE_PROFILES',
        '--',
        ':!*.md',
        ':!tooling/tests/worktree/dev-dns.test.ts',
      ],
      { cwd: REPO_ROOT, encoding: 'utf8' },
    )
      .trim()
      .split('\n');

    expect(activating).toEqual(['tooling/worktree/dev-dns.ts']);
  });
});
