import { execFileSync, spawnSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import { isIPv4 } from 'node:net';
import { join, resolve } from 'node:path';
import { worktreeContext } from './local-env';
import {
  readSharedValues,
  type SharedValues,
  sharedDevDomain,
  sharedValue,
} from './shared-values';

/**
 * `bun run dns:start` / `bun run dns:stop`: this machine's opt-in resolver
 * for its private worktree URLs (ADR-0005). It answers only
 * `*.<CHURCH_DEV_DOMAIN>`, with `CHURCH_DEV_ADDRESS` (default: this machine's
 * `tailscale ip -4`), listening on that address, port 53. Both values come
 * from the machine-shared `church-shared.env`; the dnsmasq config is
 * rendered beside it in the shared Git directory.
 *
 * The resolver is the `dns` service of the primary checkout's Compose file,
 * behind the `dns` profile, so `db:start` (and with it bootstrap), CI and
 * E2E never start it.
 */

const CONFIG_FILE = 'church-dnsmasq.conf';
const CONFIG_HEADER =
  '# Generated by `bun run dns:start` (tooling/worktree/dev-dns.ts). Do not edit; rerun it.';
const ADDRESS_VARIABLE = 'CHURCH_DEV_ADDRESS';
const CONFIG_VARIABLE = 'CHURCH_DNS_CONFIG';
const DNS_PROFILE = 'dns';
const DNS_SERVICE = 'dns';
const SHARED_COMPOSE = resolve(import.meta.dir, 'shared-compose.sh');

export interface DnsmasqConfigInput {
  domain: string;
  address: string;
}

/** Answers the domain and every name below it with `address` (other record
 * types with no data), and refuses everything else: no upstream servers, no
 * `/etc/hosts`. */
export function renderDnsmasqConfig(input: DnsmasqConfigInput): string {
  return [
    CONFIG_HEADER,
    'no-resolv',
    'no-hosts',
    `local=/${input.domain}/`,
    `address=/${input.domain}/${input.address}`,
    '',
  ].join('\n');
}

interface SharedInput {
  shared: SharedValues;
}

function tailscaleAddress(input: SharedInput): string {
  let address: string | undefined;
  try {
    address = execFileSync('tailscale', ['ip', '-4'], {
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'pipe'],
    })
      .split('\n')[0]
      ?.trim();
  } catch {
    address = undefined;
  }

  if (!address) {
    throw new Error(
      `\`tailscale ip -4\` reported no address. Start Tailscale, or set ${ADDRESS_VARIABLE} (e.g. this machine's LAN IP) in ${input.shared.path}, then rerun.`,
    );
  }

  return address;
}

/** `CHURCH_DEV_ADDRESS`, or this machine's Tailscale IPv4 when unset. */
function devAddress(input: SharedInput): string {
  const address =
    sharedValue({ ...input, key: ADDRESS_VARIABLE }) ?? tailscaleAddress(input);

  if (!isIPv4(address)) {
    throw new Error(
      `${ADDRESS_VARIABLE} must be this machine's IPv4 address, but resolved to "${address}". Fix it in ${input.shared.path}, then rerun.`,
    );
  }

  return address;
}

interface ComposeInput {
  args: string[];
  env?: NodeJS.ProcessEnv;
}

function sharedCompose(input: ComposeInput): number {
  const result = spawnSync(
    'sh',
    [SHARED_COMPOSE, '--profile', DNS_PROFILE, ...input.args],
    { stdio: 'inherit', env: { ...process.env, ...input.env } },
  );

  return result.status ?? 1;
}

interface CwdInput {
  cwd: string;
}

function startResolver(input: CwdInput): number {
  const { commonDir } = worktreeContext(input);
  const shared = readSharedValues({ commonDir });
  const domain = sharedDevDomain({ shared });

  if (!domain) {
    throw new Error(
      `CHURCH_DEV_DOMAIN is not set. Add this machine's domain (e.g. laptop.dev.home.arpa) to ${shared.path}, then rerun.`,
    );
  }

  const address = devAddress({ shared });
  const configPath = join(commonDir, CONFIG_FILE);
  writeFileSync(configPath, renderDnsmasqConfig({ domain, address }));
  console.log(`dns:start answering *.${domain} with ${address}`);

  // Recreated every time: a changed config file alone would not restart it.
  return sharedCompose({
    args: ['up', '--detach', '--wait', '--force-recreate', DNS_SERVICE],
    env: { [ADDRESS_VARIABLE]: address, [CONFIG_VARIABLE]: configPath },
  });
}

function stopResolver(): number {
  return sharedCompose({ args: ['stop', DNS_SERVICE] });
}

function main(): void {
  const command = process.argv[2];

  try {
    if (command === 'start')
      process.exit(startResolver({ cwd: process.cwd() }));
    if (command === 'stop') process.exit(stopResolver());
    throw new Error(`expected "start" or "stop", got "${command ?? ''}"`);
  } catch (error) {
    console.error(
      `✖ dns:${command ?? ''} failed: ${error instanceof Error ? error.message : String(error)}`,
    );
    process.exit(1);
  }
}

if (import.meta.main) {
  main();
}
