import { execFileSync, spawnSync } from 'node:child_process';
import { randomBytes } from 'node:crypto';
import { existsSync, readFileSync, renameSync, writeFileSync } from 'node:fs';
import { basename, dirname, join } from 'node:path';
import {
  WORKTREE_DATABASE_PURPOSES,
  worktreeDatabaseUrls,
} from './database-targets';
import {
  allocatePorts,
  PORT_SERVICES,
  type PortAvailabilityInput,
  type PortService,
  type PortSet,
} from './port-allocation';
import {
  deriveWorktreeIdentity,
  PRIMARY_WORKTREE_IDENTITY,
} from './worktree-identity';

/**
 * `bun run env:local [--revalidate]`: generates the worktree's one ignored
 * root `.env.local` (ADR-0005) — its identity, service ports, the URL set
 * derived from them, and a unique Better Auth secret. Reruns reproduce the
 * file. `--revalidate` (for launch) keeps it while every persisted port is
 * still free, and otherwise reallocates the whole port set and rewrites
 * every dependent URL in one atomic replace.
 *
 * Allocation runs under one kernel `flock` in the repository's shared Git
 * directory, so worktrees generating concurrently see each other's claims.
 */

const LOCAL_ENV_FILE = '.env.local';
const LEGACY_ENV_FILE = '.env';
const GENERATED_HEADER =
  '# Generated by `bun run env:local` (tooling/worktree/local-env.ts). Do not edit; rerun it.';
const LOCK_FILE = 'church-local-env.lock';
const LOCK_HELD_VARIABLE = 'CHURCH_LOCAL_ENV_LOCK_HELD';
const REVALIDATE_FLAG = '--revalidate';
// Loopback until the private `dev.home.arpa` naming lands (#259).
const URL_HOST = 'localhost';
const AUTH_SECRET_BYTES = 32;

const PORT_VARIABLES: Record<PortService, string> = {
  server: 'CHURCH_SERVER_PORT',
  web: 'CHURCH_WEB_PORT',
  e2eServer: 'PW_SERVER_PORT',
  e2eWeb: 'PW_WEB_PORT',
};

interface LocalEnv {
  worktree: string;
  ports: PortSet;
  betterAuthSecret: string;
}

interface WorktreeContext {
  root: string;
  commonDir: string;
  repository: string;
  isPrimary: boolean;
  name: string;
}

interface GitInput {
  cwd: string;
  args: string[];
}

function git(input: GitInput): string {
  return execFileSync('git', input.args, {
    cwd: input.cwd,
    encoding: 'utf8',
    stdio: ['ignore', 'pipe', 'pipe'],
  }).trim();
}

/** The checked-out branch, including an unborn one; undefined when detached. */
function currentBranch(input: CwdInput): string | undefined {
  try {
    return git({
      cwd: input.cwd,
      args: ['symbolic-ref', '--quiet', '--short', 'HEAD'],
    });
  } catch {
    return undefined;
  }
}

interface CwdInput {
  cwd: string;
}

function worktreeContext(input: CwdInput): WorktreeContext {
  const [root = '', gitDir, commonDir = ''] = git({
    cwd: input.cwd,
    args: [
      'rev-parse',
      '--path-format=absolute',
      '--show-toplevel',
      '--git-dir',
      '--git-common-dir',
    ],
  }).split('\n');

  return {
    root,
    commonDir,
    repository: basename(dirname(commonDir)),
    isPrimary: gitDir === commonDir,
    // A detached HEAD has no branch; the directory name is stable instead.
    name: currentBranch(input) ?? basename(root),
  };
}

interface ContentInput {
  content: string;
}

function parseValues(input: ContentInput): Map<string, string> {
  const values = new Map<string, string>();

  for (const line of input.content.split('\n')) {
    const separator = line.indexOf('=');
    if (separator > 0 && !line.startsWith('#')) {
      values.set(line.slice(0, separator), line.slice(separator + 1));
    }
  }

  return values;
}

interface ValuesInput {
  values: Map<string, string>;
}

function portsFrom(input: ValuesInput): PortSet | undefined {
  const ports = {} as PortSet;

  for (const service of PORT_SERVICES) {
    const port = Number(input.values.get(PORT_VARIABLES[service]));
    if (!Number.isInteger(port) || port <= 0) return undefined;
    ports[service] = port;
  }

  return ports;
}

function hasGeneratedHeader(input: ContentInput): boolean {
  return input.content.startsWith(`${GENERATED_HEADER}\n`);
}

interface PathInput {
  path: string;
}

function readContent(input: PathInput): string | undefined {
  return existsSync(input.path) ? readFileSync(input.path, 'utf8') : undefined;
}

interface LocalEnvInput {
  localEnv: LocalEnv;
}

interface WorktreeInput {
  worktree: string;
}

/**
 * One `DATABASE_URL` whose value Varlock selects from `CHURCH_EXEC_PURPOSE`,
 * so every purpose-wrapped command gets this worktree's matching database
 * from the single `.env.local`. Any other purpose (`unit`) resolves no
 * database rather than falling through to the purpose name.
 */
function databaseUrlSelector(input: WorktreeInput): string {
  const urls = worktreeDatabaseUrls({ worktree: input.worktree });
  const cases = WORKTREE_DATABASE_PURPOSES.map(
    (purpose) => `${purpose}, "${urls[purpose]}"`,
  );

  return `remap($CHURCH_EXEC_PURPOSE, ${cases.join(', ')}, regex(.*), undefined)`;
}

function renderLocalEnv(input: LocalEnvInput): string {
  const { worktree, ports, betterAuthSecret } = input.localEnv;
  const serverUrl = `http://${URL_HOST}:${ports.server}`;
  const webUrl = `http://${URL_HOST}:${ports.web}`;

  return [
    GENERATED_HEADER,
    `CHURCH_WORKTREE=${worktree}`,
    ...PORT_SERVICES.map(
      (service) => `${PORT_VARIABLES[service]}=${ports[service]}`,
    ),
    `BETTER_AUTH_URL=${serverUrl}`,
    `VITE_SERVER_URL=${serverUrl}`,
    `CORS_ORIGIN=${webUrl}`,
    `BETTER_AUTH_SECRET=${betterAuthSecret}`,
    `DATABASE_URL=${databaseUrlSelector({ worktree })}`,
    '',
  ].join('\n');
}

interface ContextInput {
  context: WorktreeContext;
}

interface OtherWorktreeClaims {
  identities: Set<string>;
  ports: Set<number>;
}

/** Identities and ports persisted in every other active worktree's
 * generated `.env.local`. */
function claimsOfOtherWorktrees(input: ContextInput): OtherWorktreeClaims {
  const roots = git({
    cwd: input.context.root,
    args: ['worktree', 'list', '--porcelain'],
  })
    .split('\n')
    .filter((line) => line.startsWith('worktree '))
    .map((line) => line.slice('worktree '.length))
    .filter((root) => root !== input.context.root);

  const claims: OtherWorktreeClaims = {
    identities: new Set(),
    ports: new Set(),
  };

  for (const root of roots) {
    const content = readContent({ path: join(root, LOCAL_ENV_FILE) });
    if (!content || !hasGeneratedHeader({ content })) continue;

    const values = parseValues({ content });
    const identity = values.get('CHURCH_WORKTREE');
    if (identity) claims.identities.add(identity);
    for (const port of Object.values(portsFrom({ values }) ?? {})) {
      claims.ports.add(port);
    }
  }

  return claims;
}

interface ListenerCheckInput {
  hostname: string;
  port: number;
}

function canListen(input: ListenerCheckInput): boolean {
  try {
    Bun.listen({ ...input, socket: { data() {} } }).stop(true);
    return true;
  } catch (error) {
    // A host without IPv6 cannot bind `::` at all; only a conflict counts.
    return (
      input.hostname === '::' &&
      (error as { code?: string }).code !== 'EADDRINUSE'
    );
  }
}

/** Free for both an IPv4 and an IPv6 listener (Vite may bind `::1`). */
function isHostPortFree(input: PortAvailabilityInput): boolean {
  return (
    canListen({ hostname: '0.0.0.0', port: input.port }) &&
    canListen({ hostname: '::', port: input.port })
  );
}

interface LegacyOverridesInput {
  root: string;
  generated: Map<string, string>;
}

/**
 * Keys whose value in the legacy root `.env` differs from the generated one.
 * Varlock and Vite prefer `.env.local`, while not-yet-migrated scripts still
 * read `.env` alone, so such keys now diverge between commands.
 */
function legacyOverrides(input: LegacyOverridesInput): string[] {
  const legacy = parseValues({
    content: readContent({ path: join(input.root, LEGACY_ENV_FILE) }) ?? '',
  });

  return [...input.generated.keys()].filter((key) => {
    const legacyValue = legacy.get(key)?.replace(/^(['"])(.*)\1$/, '$2');
    return (
      legacyValue !== undefined && legacyValue !== input.generated.get(key)
    );
  });
}

interface WriteAtomicallyInput {
  path: string;
  content: string;
}

function writeAtomically(input: WriteAtomicallyInput): void {
  // Named to match `.env*.local` in .gitignore: it holds the secret too.
  const temporary = join(dirname(input.path), `.env.${process.pid}.tmp.local`);
  writeFileSync(temporary, input.content, { mode: 0o600 });
  renameSync(temporary, input.path);
}

/** The identity in this worktree's generated `.env.local`; undefined when
 * the file is absent or was not generated by env:local. */
export function readGeneratedWorktreeIdentity(
  input: CwdInput,
): string | undefined {
  const context = worktreeContext(input);
  const content = readContent({ path: join(context.root, LOCAL_ENV_FILE) });
  if (content === undefined || !hasGeneratedHeader({ content })) {
    return undefined;
  }

  const identity = parseValues({ content }).get('CHURCH_WORKTREE');
  if (
    identity !== undefined &&
    (identity === PRIMARY_WORKTREE_IDENTITY) !== context.isPrimary
  ) {
    throw new Error(
      `${LOCAL_ENV_FILE} names worktree "${identity}", which ${context.isPrimary ? 'only a linked worktree may hold' : 'is reserved for the primary checkout'}. Delete it and rerun \`bun run env:local\`.`,
    );
  }

  return identity;
}

interface GenerateInput {
  cwd: string;
  revalidate: boolean;
}

function generateLocalEnv(input: GenerateInput): void {
  const context = worktreeContext({ cwd: input.cwd });
  const path = join(context.root, LOCAL_ENV_FILE);
  const existingContent = readContent({ path });

  if (
    existingContent !== undefined &&
    !hasGeneratedHeader({ content: existingContent })
  ) {
    throw new Error(
      `${path} was not generated by env:local. Move its values elsewhere or delete it, then rerun.`,
    );
  }

  const existing = parseValues({ content: existingContent ?? '' });
  const worktree =
    existing.get('CHURCH_WORKTREE') ??
    deriveWorktreeIdentity({
      name: context.name,
      isPrimary: context.isPrimary,
    });
  const claims = claimsOfOtherWorktrees({ context });

  if (claims.identities.has(worktree)) {
    throw new Error(
      `Worktree identity "${worktree}" is already held by another active worktree; its databases would be shared. Rename this worktree's branch or directory, then rerun.`,
    );
  }

  const isAvailable = (availability: PortAvailabilityInput): boolean =>
    !claims.ports.has(availability.port) && isHostPortFree(availability);

  const persistedPorts = portsFrom({ values: existing });
  const unavailablePorts = Object.values(persistedPorts ?? {}).filter(
    (port) => input.revalidate && !isAvailable({ port }),
  );

  if (worktree === PRIMARY_WORKTREE_IDENTITY && unavailablePorts.length > 0) {
    throw new Error(
      `The primary worktree keeps its established ports, but ${unavailablePorts.join(', ')} ${unavailablePorts.length === 1 ? 'is' : 'are'} in use. Stop whatever holds ${unavailablePorts.length === 1 ? 'it' : 'them'}, then rerun.`,
    );
  }

  const keepPersisted =
    persistedPorts !== undefined && unavailablePorts.length === 0;
  const ports = keepPersisted
    ? persistedPorts
    : allocatePorts({
        repository: context.repository,
        worktree,
        isAvailable,
      });

  const content = renderLocalEnv({
    localEnv: {
      worktree,
      ports,
      betterAuthSecret:
        existing.get('BETTER_AUTH_SECRET') ??
        randomBytes(AUTH_SECRET_BYTES).toString('hex'),
    },
  });

  const unchanged = content === existingContent;

  if (!unchanged) {
    writeAtomically({ path, content });
  }

  const summary = PORT_SERVICES.map(
    (service) => `${service}=${ports[service]}`,
  ).join(' ');
  console.log(
    `env:local ${unchanged ? 'unchanged' : 'written'}: worktree=${worktree} ${summary}`,
  );

  const overridden = legacyOverrides({
    root: context.root,
    generated: parseValues({ content }),
  });

  if (overridden.length > 0) {
    console.warn(
      `⚠ env:local overrides values from the legacy ${LEGACY_ENV_FILE} for: ${overridden.join(', ')}. Varlock-wrapped commands and Vite now use the generated values; scripts still reading ${LEGACY_ENV_FILE} directly do not.`,
    );
  }
}

interface ArgvInput {
  argv: string[];
}

/** Re-executes this script under the shared allocation lock. */
function runUnderLock(input: ArgvInput): number {
  const context = worktreeContext({ cwd: process.cwd() });
  const result = spawnSync(
    'flock',
    [
      join(context.commonDir, LOCK_FILE),
      process.execPath,
      import.meta.path,
      ...input.argv,
    ],
    {
      stdio: 'inherit',
      env: { ...process.env, [LOCK_HELD_VARIABLE]: '1' },
    },
  );

  if (result.error) {
    console.error(
      `✖ env:local could not take the allocation lock with flock: ${result.error.message}`,
    );
  }

  return result.status ?? 1;
}

function main(): void {
  const argv = process.argv.slice(2);

  try {
    if (process.env[LOCK_HELD_VARIABLE] !== '1') {
      process.exit(runUnderLock({ argv }));
    }

    generateLocalEnv({
      cwd: process.cwd(),
      revalidate: argv.includes(REVALIDATE_FLAG),
    });
  } catch (error) {
    console.error(
      `✖ env:local failed: ${error instanceof Error ? error.message : String(error)}`,
    );
    process.exit(1);
  }
}

if (import.meta.main) {
  main();
}
